/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s2[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {0, 1, 2, 6, 7, 8, 9};
static const casadi_int casadi_s6[7] = {0, 1, 2, 9, 10, 11, 12};
static const casadi_int casadi_s7[7] = {0, 3, 6, 9, 13, 17, 21};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s9[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s10[7] = {3, 4, 5, 13, 14, 15, 16};
static const casadi_int casadi_s11[7] = {1, 4, 7, 10, 14, 18, 22};
static const casadi_int casadi_s12[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s13[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s14[7] = {6, 7, 8, 17, 18, 19, 20};
static const casadi_int casadi_s15[7] = {2, 5, 8, 11, 15, 19, 23};
static const casadi_int casadi_s16[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s17[41] = {13, 13, 0, 3, 6, 9, 9, 9, 9, 13, 17, 21, 25, 25, 25, 25, 0, 1, 2, 0, 1, 2, 0, 1, 2, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9};
static const casadi_int casadi_s18[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s19[3] = {0, 0, 0};
static const casadi_int casadi_s20[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s21[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s22[16] = {0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[9] = {3., 0., 0., 0., 3., 0., 0., 0., 3.};

/* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[],i2[],i3[24])->(o0,o1[13],o2[13x13,25nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+4, *w2=w+7, *w3=w+10, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, *w29=w+44, *w30=w+68, *w31=w+71, *w32=w+74, *w33=w+83, *w34=w+96, *w35=w+99, *w36=w+102, *w37=w+111, *w38=w+115, *w39=w+119, *w40=w+123, *w41=w+127, *w42=w+130, *w43=w+133, *w44=w+136, *w45=w+139, *w46=w+148, *w47=w+152, *w48=w+155, *w49=w+164, *w50=w+167, *w51=w+170, *w52=w+173, *w53=w+177, *w54=w+186, *w55=w+195, w56, w57, w58, w59, w60, *w61=w+209, *w62=w+234, *w63=w+238, *w67=w+246, *w68=w+250, *w69=w+254, *w70=w+258, w71, w72, w73, w74, w75, w76, w77, w78, w79, w80, w81, *w82=w+272, *w83=w+279, *w84=w+281;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #6: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #7: @7 = input[3][2] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #8: @8 = input[3][3] */
  w8 = arg[3] ? arg[3][3] : 0;
  /* #9: @9 = input[3][4] */
  w9 = arg[3] ? arg[3][4] : 0;
  /* #10: @10 = input[3][5] */
  w10 = arg[3] ? arg[3][5] : 0;
  /* #11: @11 = input[3][6] */
  w11 = arg[3] ? arg[3][6] : 0;
  /* #12: @12 = input[3][7] */
  w12 = arg[3] ? arg[3][7] : 0;
  /* #13: @13 = input[3][8] */
  w13 = arg[3] ? arg[3][8] : 0;
  /* #14: @14 = input[3][9] */
  w14 = arg[3] ? arg[3][9] : 0;
  /* #15: @15 = input[3][10] */
  w15 = arg[3] ? arg[3][10] : 0;
  /* #16: @16 = input[3][11] */
  w16 = arg[3] ? arg[3][11] : 0;
  /* #17: @17 = input[3][12] */
  w17 = arg[3] ? arg[3][12] : 0;
  /* #18: @18 = input[3][13] */
  w18 = arg[3] ? arg[3][13] : 0;
  /* #19: @19 = input[3][14] */
  w19 = arg[3] ? arg[3][14] : 0;
  /* #20: @20 = input[3][15] */
  w20 = arg[3] ? arg[3][15] : 0;
  /* #21: @21 = input[3][16] */
  w21 = arg[3] ? arg[3][16] : 0;
  /* #22: @22 = input[3][17] */
  w22 = arg[3] ? arg[3][17] : 0;
  /* #23: @23 = input[3][18] */
  w23 = arg[3] ? arg[3][18] : 0;
  /* #24: @24 = input[3][19] */
  w24 = arg[3] ? arg[3][19] : 0;
  /* #25: @25 = input[3][20] */
  w25 = arg[3] ? arg[3][20] : 0;
  /* #26: @26 = input[3][21] */
  w26 = arg[3] ? arg[3][21] : 0;
  /* #27: @27 = input[3][22] */
  w27 = arg[3] ? arg[3][22] : 0;
  /* #28: @28 = input[3][23] */
  w28 = arg[3] ? arg[3][23] : 0;
  /* #29: @29 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28) */
  rr=w29;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  /* #30: @30 = @29[3:6] */
  for (rr=w30, ss=w29+3; ss!=w29+6; ss+=1) *rr++ = *ss;
  /* #31: @31 = @30' */
  casadi_copy(w30, 3, w31);
  /* #32: @4 = mac(@31,@30,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #33: @32 = @4[0, 0, 0, 0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w32, ss=(&w4); cii!=casadi_s0+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #34: @3 = (@3-@32) */
  for (i=0, rr=w3, cs=w32; i<9; ++i) (*rr++) -= (*cs++);
  /* #35: @31 = @29[:3] */
  for (rr=w31, ss=w29+0; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #36: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #37: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #38: @6 = input[0][2] */
  w6 = arg[0] ? arg[0][2] : 0;
  /* #39: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #40: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #41: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #42: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #43: @11 = input[0][7] */
  w11 = arg[0] ? arg[0][7] : 0;
  /* #44: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #45: @13 = input[0][9] */
  w13 = arg[0] ? arg[0][9] : 0;
  /* #46: @14 = input[0][10] */
  w14 = arg[0] ? arg[0][10] : 0;
  /* #47: @15 = input[0][11] */
  w15 = arg[0] ? arg[0][11] : 0;
  /* #48: @16 = input[0][12] */
  w16 = arg[0] ? arg[0][12] : 0;
  /* #49: @33 = vertcat(@4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w33;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #50: @34 = @33[:3] */
  for (rr=w34, ss=w33+0; ss!=w33+3; ss+=1) *rr++ = *ss;
  /* #51: @31 = (@31-@34) */
  for (i=0, rr=w31, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #52: @2 = mac(@3,@31,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #53: @34 = @2' */
  casadi_copy(w2, 3, w34);
  /* #54: @32 = 
  [[3, 0, 0], 
   [0, 3, 0], 
   [0, 0, 3]] */
  casadi_copy(casadi_c1, 9, w32);
  /* #55: @1 = mac(@34,@32,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #56: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #57: @4 = 0 */
  w4 = 0.;
  /* #58: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #59: @5 = dot(@30, @31) */
  w5 = casadi_dot(3, w30, w31);
  /* #60: @31 = (@5*@30) */
  for (i=0, rr=w31, cs=w30; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #61: @35 = @31' */
  casadi_copy(w31, 3, w35);
  /* #62: @36 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w36);
  /* #63: @34 = mac(@35,@36,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #64: @4 = mac(@34,@31,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #65: @0 = (@0+@4) */
  w0 += w4;
  /* #66: @4 = 0 */
  w4 = 0.;
  /* #67: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #68: @11 = (-@11) */
  w11 = (- w11 );
  /* #69: @12 = (-@12) */
  w12 = (- w12 );
  /* #70: @13 = (-@13) */
  w13 = (- w13 );
  /* #71: @37 = vertcat(@10, @11, @12, @13) */
  rr=w37;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #72: @38 = @33[6:10] */
  for (rr=w38, ss=w33+6; ss!=w33+10; ss+=1) *rr++ = *ss;
  /* #73: @10 = ||@38||_F */
  w10 = sqrt(casadi_dot(4, w38, w38));
  /* #74: @37 = (@37/@10) */
  for (i=0, rr=w37; i<4; ++i) (*rr++) /= w10;
  /* #75: {@11, @12, @13, @5} = vertsplit(@37) */
  w11 = w37[0];
  w12 = w37[1];
  w13 = w37[2];
  w5 = w37[3];
  /* #76: @39 = @29[6:10] */
  for (rr=w39, ss=w29+6; ss!=w29+10; ss+=1) *rr++ = *ss;
  /* #77: {@6, @7, @8, @9} = vertsplit(@39) */
  w6 = w39[0];
  w7 = w39[1];
  w8 = w39[2];
  w9 = w39[3];
  /* #78: @14 = (@11*@6) */
  w14  = (w11*w6);
  /* #79: @15 = (@12*@7) */
  w15  = (w12*w7);
  /* #80: @14 = (@14-@15) */
  w14 -= w15;
  /* #81: @15 = (@13*@8) */
  w15  = (w13*w8);
  /* #82: @14 = (@14-@15) */
  w14 -= w15;
  /* #83: @15 = (@5*@9) */
  w15  = (w5*w9);
  /* #84: @14 = (@14-@15) */
  w14 -= w15;
  /* #85: @15 = 0 */
  w15 = 0.;
  /* #86: @15 = (@14<@15) */
  w15  = (w14<w15);
  /* #87: @16 = (@11*@7) */
  w16  = (w11*w7);
  /* #88: @17 = (@12*@6) */
  w17  = (w12*w6);
  /* #89: @16 = (@16+@17) */
  w16 += w17;
  /* #90: @17 = (@13*@9) */
  w17  = (w13*w9);
  /* #91: @16 = (@16+@17) */
  w16 += w17;
  /* #92: @17 = (@5*@8) */
  w17  = (w5*w8);
  /* #93: @16 = (@16-@17) */
  w16 -= w17;
  /* #94: @17 = (@11*@8) */
  w17  = (w11*w8);
  /* #95: @18 = (@12*@9) */
  w18  = (w12*w9);
  /* #96: @17 = (@17-@18) */
  w17 -= w18;
  /* #97: @18 = (@13*@6) */
  w18  = (w13*w6);
  /* #98: @17 = (@17+@18) */
  w17 += w18;
  /* #99: @18 = (@5*@7) */
  w18  = (w5*w7);
  /* #100: @17 = (@17+@18) */
  w17 += w18;
  /* #101: @11 = (@11*@9) */
  w11 *= w9;
  /* #102: @12 = (@12*@8) */
  w12 *= w8;
  /* #103: @11 = (@11+@12) */
  w11 += w12;
  /* #104: @13 = (@13*@7) */
  w13 *= w7;
  /* #105: @11 = (@11-@13) */
  w11 -= w13;
  /* #106: @5 = (@5*@6) */
  w5 *= w6;
  /* #107: @11 = (@11+@5) */
  w11 += w5;
  /* #108: @39 = vertcat(@14, @16, @17, @11) */
  rr=w39;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w11;
  /* #109: @40 = (-@39) */
  for (i=0, rr=w40, cs=w39; i<4; ++i) *rr++ = (- *cs++ );
  /* #110: @40 = (@15?@40:0) */
  for (i=0, rr=w40, cs=w40; i<4; ++i) (*rr++)  = (w15?(*cs++):0);
  /* #111: @14 = (!@15) */
  w14 = (! w15 );
  /* #112: @39 = (@14?@39:0) */
  for (i=0, rr=w39, cs=w39; i<4; ++i) (*rr++)  = (w14?(*cs++):0);
  /* #113: @40 = (@40+@39) */
  for (i=0, rr=w40, cs=w39; i<4; ++i) (*rr++) += (*cs++);
  /* #114: @41 = @40[1:4] */
  for (rr=w41, ss=w40+1; ss!=w40+4; ss+=1) *rr++ = *ss;
  /* #115: @42 = (2.*@41) */
  for (i=0, rr=w42, cs=w41; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #116: @16 = ||@41||_F */
  w16 = sqrt(casadi_dot(3, w41, w41));
  /* #117: @17 = @40[0] */
  for (rr=(&w17), ss=w40+0; ss!=w40+1; ss+=1) *rr++ = *ss;
  /* #118: @11 = atan2(@16,@17) */
  w11  = atan2(w16,w17);
  /* #119: @43 = (@42*@11) */
  for (i=0, rr=w43, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w11);
  /* #120: @43 = (@43/@16) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) /= w16;
  /* #121: @44 = @43' */
  casadi_copy(w43, 3, w44);
  /* #122: @45 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w45);
  /* #123: @35 = mac(@44,@45,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w44+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #124: @4 = mac(@35,@43,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w43+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #125: @0 = (@0+@4) */
  w0 += w4;
  /* #126: @4 = 0.05 */
  w4 = 5.0000000000000003e-02;
  /* #127: @44 = @33[3:6] */
  for (rr=w44, ss=w33+3; ss!=w33+6; ss+=1) *rr++ = *ss;
  /* #128: @5 = dot(@30, @44) */
  w5 = casadi_dot(3, w30, w44);
  /* #129: @4 = (@4*@5) */
  w4 *= w5;
  /* #130: @0 = (@0-@4) */
  w0 -= w4;
  /* #131: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #132: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #133: @0 = -0.05 */
  w0 = -5.0000000000000003e-02;
  /* #134: @44 = (@0*@30) */
  for (i=0, rr=w44, cs=w30; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #135: (@33[3:6] += @44) */
  for (rr=w33+3, ss=w44; rr!=w33+6; rr+=1) *rr += *ss++;
  /* #136: @40 = (@37/@10) */
  for (i=0, rr=w40, cr=w37; i<4; ++i) (*rr++)  = ((*cr++)/w10);
  /* #137: @39 = (-@40) */
  for (i=0, rr=w39, cs=w40; i<4; ++i) *rr++ = (- *cs++ );
  /* #138: @0 = 1 */
  w0 = 1.;
  /* #139: @0 = (@14?@0:0) */
  w0  = (w14?w0:0);
  /* #140: @46 = zeros(4x1) */
  casadi_clear(w46, 4);
  /* #141: @4 = sq(@16) */
  w4 = casadi_sq( w16 );
  /* #142: @5 = sq(@17) */
  w5 = casadi_sq( w17 );
  /* #143: @4 = (@4+@5) */
  w4 += w5;
  /* #144: @5 = (@16/@4) */
  w5  = (w16/w4);
  /* #145: @35 = @35' */
  /* #146: @44 = zeros(1x3) */
  casadi_clear(w44, 3);
  /* #147: @47 = @43' */
  casadi_copy(w43, 3, w47);
  /* #148: @48 = @45' */
  for (i=0, rr=w48, cs=w45; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #149: @44 = mac(@47,@48,@44) */
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #150: @44 = @44' */
  /* #151: @35 = (@35+@44) */
  for (i=0, rr=w35, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #152: @44 = (@35/@16) */
  for (i=0, rr=w44, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #153: @13 = dot(@42, @44) */
  w13 = casadi_dot(3, w42, w44);
  /* #154: @12 = (@5*@13) */
  w12  = (w5*w13);
  /* #155: @12 = (-@12) */
  w12 = (- w12 );
  /* #156: (@46[0] += @12) */
  for (rr=w46+0, ss=(&w12); rr!=w46+1; rr+=1) *rr += *ss++;
  /* #157: @47 = (@43/@16) */
  for (i=0, rr=w47, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #158: @49 = (-@47) */
  for (i=0, rr=w49, cs=w47; i<3; ++i) *rr++ = (- *cs++ );
  /* #159: @12 = dot(@49, @35) */
  w12 = casadi_dot(3, w49, w35);
  /* #160: @18 = (@17/@4) */
  w18  = (w17/w4);
  /* #161: @19 = (@18*@13) */
  w19  = (w18*w13);
  /* #162: @12 = (@12+@19) */
  w12 += w19;
  /* #163: @12 = (@12/@16) */
  w12 /= w16;
  /* #164: @50 = (@12*@41) */
  for (i=0, rr=w50, cs=w41; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #165: @51 = (@11*@44) */
  for (i=0, rr=w51, cs=w44; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #166: @51 = (2.*@51) */
  for (i=0, rr=w51, cs=w51; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #167: @50 = (@50+@51) */
  for (i=0, rr=w50, cs=w51; i<3; ++i) (*rr++) += (*cs++);
  /* #168: (@46[1:4] += @50) */
  for (rr=w46+1, ss=w50; rr!=w46+4; rr+=1) *rr += *ss++;
  /* #169: @52 = (@0*@46) */
  for (i=0, rr=w52, cs=w46; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #170: @19 = 1 */
  w19 = 1.;
  /* #171: @19 = (@15?@19:0) */
  w19  = (w15?w19:0);
  /* #172: @46 = (@19*@46) */
  for (i=0, rr=w46, cs=w46; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #173: @52 = (@52-@46) */
  for (i=0, rr=w52, cs=w46; i<4; ++i) (*rr++) -= (*cs++);
  /* #174: {@20, @21, @22, @23} = vertsplit(@52) */
  w20 = w52[0];
  w21 = w52[1];
  w22 = w52[2];
  w23 = w52[3];
  /* #175: @24 = (@9*@23) */
  w24  = (w9*w23);
  /* #176: @25 = (@8*@22) */
  w25  = (w8*w22);
  /* #177: @24 = (@24+@25) */
  w24 += w25;
  /* #178: @25 = (@7*@21) */
  w25  = (w7*w21);
  /* #179: @24 = (@24+@25) */
  w24 += w25;
  /* #180: @25 = (@6*@20) */
  w25  = (w6*w20);
  /* #181: @24 = (@24+@25) */
  w24 += w25;
  /* #182: @25 = (@8*@23) */
  w25  = (w8*w23);
  /* #183: @26 = (@9*@22) */
  w26  = (w9*w22);
  /* #184: @25 = (@25-@26) */
  w25 -= w26;
  /* #185: @26 = (@6*@21) */
  w26  = (w6*w21);
  /* #186: @25 = (@25+@26) */
  w25 += w26;
  /* #187: @26 = (@7*@20) */
  w26  = (w7*w20);
  /* #188: @25 = (@25-@26) */
  w25 -= w26;
  /* #189: @26 = (@6*@22) */
  w26  = (w6*w22);
  /* #190: @27 = (@7*@23) */
  w27  = (w7*w23);
  /* #191: @26 = (@26-@27) */
  w26 -= w27;
  /* #192: @27 = (@9*@21) */
  w27  = (w9*w21);
  /* #193: @26 = (@26+@27) */
  w26 += w27;
  /* #194: @27 = (@8*@20) */
  w27  = (w8*w20);
  /* #195: @26 = (@26-@27) */
  w26 -= w27;
  /* #196: @23 = (@6*@23) */
  w23  = (w6*w23);
  /* #197: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #198: @23 = (@23+@22) */
  w23 += w22;
  /* #199: @21 = (@8*@21) */
  w21  = (w8*w21);
  /* #200: @23 = (@23-@21) */
  w23 -= w21;
  /* #201: @20 = (@9*@20) */
  w20  = (w9*w20);
  /* #202: @23 = (@23-@20) */
  w23 -= w20;
  /* #203: @52 = vertcat(@24, @25, @26, @23) */
  rr=w52;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w23;
  /* #204: @24 = dot(@39, @52) */
  w24 = casadi_dot(4, w39, w52);
  /* #205: @24 = (@24/@10) */
  w24 /= w10;
  /* #206: @46 = (@24*@38) */
  for (i=0, rr=w46, cs=w38; i<4; ++i) (*rr++)  = (w24*(*cs++));
  /* #207: (@33[6:10] += @46) */
  for (rr=w33+6, ss=w46; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #208: @34 = @34' */
  /* #209: @50 = zeros(1x3) */
  casadi_clear(w50, 3);
  /* #210: @31 = @31' */
  /* #211: @53 = @36' */
  for (i=0, rr=w53, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #212: @50 = mac(@31,@53,@50) */
  for (i=0, rr=w50; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w53+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #213: @50 = @50' */
  /* #214: @34 = (@34+@50) */
  for (i=0, rr=w34, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #215: @25 = dot(@30, @34) */
  w25 = casadi_dot(3, w30, w34);
  /* #216: @34 = (@25*@30) */
  for (i=0, rr=w34, cs=w30; i<3; ++i) (*rr++)  = (w25*(*cs++));
  /* #217: @50 = zeros(3x1) */
  casadi_clear(w50, 3);
  /* #218: @54 = @3' */
  for (i=0, rr=w54, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #219: @1 = @1' */
  /* #220: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #221: @2 = @2' */
  /* #222: @55 = @32' */
  for (i=0, rr=w55, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #223: @31 = mac(@2,@55,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #224: @31 = @31' */
  /* #225: @1 = (@1+@31) */
  for (i=0, rr=w1, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #226: @50 = mac(@54,@1,@50) */
  for (i=0, rr=w50; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w54+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #227: @34 = (@34+@50) */
  for (i=0, rr=w34, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #228: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #229: (@33[:3] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+3; rr+=1) *rr += *ss++;
  /* #230: {@25, @26, @23, @20, @21, @22, @27, @28, @56, @57, @58, @59, @60} = vertsplit(@33) */
  w25 = w33[0];
  w26 = w33[1];
  w23 = w33[2];
  w20 = w33[3];
  w21 = w33[4];
  w22 = w33[5];
  w27 = w33[6];
  w28 = w33[7];
  w56 = w33[8];
  w57 = w33[9];
  w58 = w33[10];
  w59 = w33[11];
  w60 = w33[12];
  /* #231: output[1][0] = @25 */
  if (res[1]) res[1][0] = w25;
  /* #232: output[1][1] = @26 */
  if (res[1]) res[1][1] = w26;
  /* #233: output[1][2] = @23 */
  if (res[1]) res[1][2] = w23;
  /* #234: output[1][3] = @20 */
  if (res[1]) res[1][3] = w20;
  /* #235: output[1][4] = @21 */
  if (res[1]) res[1][4] = w21;
  /* #236: output[1][5] = @22 */
  if (res[1]) res[1][5] = w22;
  /* #237: @46 = (@52/@10) */
  for (i=0, rr=w46, cr=w52; i<4; ++i) (*rr++)  = ((*cr++)/w10);
  /* #238: {@22, @21, @20, @23} = vertsplit(@46) */
  w22 = w46[0];
  w21 = w46[1];
  w20 = w46[2];
  w23 = w46[3];
  /* #239: @22 = (@22+@27) */
  w22 += w27;
  /* #240: output[1][6] = @22 */
  if (res[1]) res[1][6] = w22;
  /* #241: @28 = (@28-@21) */
  w28 -= w21;
  /* #242: output[1][7] = @28 */
  if (res[1]) res[1][7] = w28;
  /* #243: @56 = (@56-@20) */
  w56 -= w20;
  /* #244: output[1][8] = @56 */
  if (res[1]) res[1][8] = w56;
  /* #245: @57 = (@57-@23) */
  w57 -= w23;
  /* #246: output[1][9] = @57 */
  if (res[1]) res[1][9] = w57;
  /* #247: output[1][10] = @58 */
  if (res[1]) res[1][10] = w58;
  /* #248: output[1][11] = @59 */
  if (res[1]) res[1][11] = w59;
  /* #249: output[1][12] = @60 */
  if (res[1]) res[1][12] = w60;
  /* #250: @61 = zeros(13x13,25nz) */
  casadi_clear(w61, 25);
  /* #251: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #252: @62 = zeros(4x1) */
  casadi_clear(w62, 4);
  /* #253: @60 = 1 */
  w60 = 1.;
  /* #254: @14 = (@14?@60:0) */
  w14  = (w14?w60:0);
  /* #255: @63 = ones(13x1,8nz) */
  casadi_fill(w63, 8, 1.);
  /* #256: {@60, NULL, NULL, NULL, NULL, NULL, @59, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@63) */
  w60 = w63[0];
  w59 = w63[4];
  /* #257: @64 = 00 */
  /* #258: @65 = 00 */
  /* #259: @66 = 00 */
  /* #260: @58 = vertcat(@59, @64, @65, @66) */
  rr=(&w58);
  *rr++ = w59;
  /* #261: @58 = (@58/@10) */
  w58 /= w10;
  /* #262: @67 = dense(@58) */
  casadi_densify((&w58), casadi_s1, w67, 0);
  /* #263: @37 = (@37/@10) */
  for (i=0, rr=w37; i<4; ++i) (*rr++) /= w10;
  /* #264: @58 = project(@38) */
  casadi_sparsify(w38, (&w58), casadi_s1, 0);
  /* #265: @57 = @59[0] */
  for (rr=(&w57), ss=(&w59)+0; ss!=(&w59)+1; ss+=1) *rr++ = *ss;
  /* #266: @59 = dot(@58, @57) */
  w59 = casadi_dot(1, (&w58), (&w57));
  /* #267: @59 = (@59/@10) */
  w59 /= w10;
  /* #268: @68 = (@37*@59) */
  for (i=0, rr=w68, cr=w37; i<4; ++i) (*rr++)  = ((*cr++)*w59);
  /* #269: @67 = (@67-@68) */
  for (i=0, rr=w67, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #270: {@58, @23, @56, @20} = vertsplit(@67) */
  w58 = w67[0];
  w23 = w67[1];
  w56 = w67[2];
  w20 = w67[3];
  /* #271: @28 = (@6*@58) */
  w28  = (w6*w58);
  /* #272: @21 = (@7*@23) */
  w21  = (w7*w23);
  /* #273: @28 = (@28-@21) */
  w28 -= w21;
  /* #274: @21 = (@8*@56) */
  w21  = (w8*w56);
  /* #275: @28 = (@28-@21) */
  w28 -= w21;
  /* #276: @21 = (@9*@20) */
  w21  = (w9*w20);
  /* #277: @28 = (@28-@21) */
  w28 -= w21;
  /* #278: @21 = (@7*@58) */
  w21  = (w7*w58);
  /* #279: @22 = (@6*@23) */
  w22  = (w6*w23);
  /* #280: @21 = (@21+@22) */
  w21 += w22;
  /* #281: @22 = (@9*@56) */
  w22  = (w9*w56);
  /* #282: @21 = (@21+@22) */
  w21 += w22;
  /* #283: @22 = (@8*@20) */
  w22  = (w8*w20);
  /* #284: @21 = (@21-@22) */
  w21 -= w22;
  /* #285: @22 = (@8*@58) */
  w22  = (w8*w58);
  /* #286: @27 = (@9*@23) */
  w27  = (w9*w23);
  /* #287: @22 = (@22-@27) */
  w22 -= w27;
  /* #288: @27 = (@6*@56) */
  w27  = (w6*w56);
  /* #289: @22 = (@22+@27) */
  w22 += w27;
  /* #290: @27 = (@7*@20) */
  w27  = (w7*w20);
  /* #291: @22 = (@22+@27) */
  w22 += w27;
  /* #292: @58 = (@9*@58) */
  w58  = (w9*w58);
  /* #293: @23 = (@8*@23) */
  w23  = (w8*w23);
  /* #294: @58 = (@58+@23) */
  w58 += w23;
  /* #295: @56 = (@7*@56) */
  w56  = (w7*w56);
  /* #296: @58 = (@58-@56) */
  w58 -= w56;
  /* #297: @20 = (@6*@20) */
  w20  = (w6*w20);
  /* #298: @58 = (@58+@20) */
  w58 += w20;
  /* #299: @68 = vertcat(@28, @21, @22, @58) */
  rr=w68;
  *rr++ = w28;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w58;
  /* #300: @69 = (@14*@68) */
  for (i=0, rr=w69, cs=w68; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #301: @28 = 1 */
  w28 = 1.;
  /* #302: @15 = (@15?@28:0) */
  w15  = (w15?w28:0);
  /* #303: @68 = (@15*@68) */
  for (i=0, rr=w68, cs=w68; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #304: @69 = (@69-@68) */
  for (i=0, rr=w69, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #305: @34 = @69[1:4] */
  for (rr=w34, ss=w69+1; ss!=w69+4; ss+=1) *rr++ = *ss;
  /* #306: @28 = dot(@41, @34) */
  w28 = casadi_dot(3, w41, w34);
  /* #307: @28 = (@28/@16) */
  w28 /= w16;
  /* #308: @21 = (@28/@4) */
  w21  = (w28/w4);
  /* #309: @22 = (@5/@4) */
  w22  = (w5/w4);
  /* #310: @58 = (2.*@16) */
  w58 = (2.* w16 );
  /* #311: @20 = (@58*@28) */
  w20  = (w58*w28);
  /* #312: @56 = (2.*@17) */
  w56 = (2.* w17 );
  /* #313: @23 = @69[0] */
  for (rr=(&w23), ss=w69+0; ss!=w69+1; ss+=1) *rr++ = *ss;
  /* #314: @27 = (@56*@23) */
  w27  = (w56*w23);
  /* #315: @20 = (@20+@27) */
  w20 += w27;
  /* #316: @27 = (@22*@20) */
  w27  = (w22*w20);
  /* #317: @21 = (@21-@27) */
  w21 -= w27;
  /* #318: @21 = (@13*@21) */
  w21  = (w13*w21);
  /* #319: @50 = zeros(1x3) */
  casadi_clear(w50, 3);
  /* #320: @1 = (2.*@34) */
  for (i=0, rr=w1, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #321: @31 = (@11*@1) */
  for (i=0, rr=w31, cs=w1; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #322: @27 = sq(@16) */
  w27 = casadi_sq( w16 );
  /* #323: @26 = sq(@17) */
  w26 = casadi_sq( w17 );
  /* #324: @27 = (@27+@26) */
  w27 += w26;
  /* #325: @17 = (@17/@27) */
  w17 /= w27;
  /* #326: @26 = (@17*@28) */
  w26  = (w17*w28);
  /* #327: @27 = (@16/@27) */
  w27  = (w16/w27);
  /* #328: @25 = (@27*@23) */
  w25  = (w27*w23);
  /* #329: @26 = (@26-@25) */
  w26 -= w25;
  /* #330: @2 = (@42*@26) */
  for (i=0, rr=w2, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #331: @31 = (@31+@2) */
  for (i=0, rr=w31, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #332: @31 = (@31/@16) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w16;
  /* #333: @43 = (@43/@16) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) /= w16;
  /* #334: @2 = (@43*@28) */
  for (i=0, rr=w2, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #335: @31 = (@31-@2) */
  for (i=0, rr=w31, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #336: @2 = @31' */
  casadi_copy(w31, 3, w2);
  /* #337: @50 = mac(@2,@45,@50) */
  for (i=0, rr=w50; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #338: @50 = @50' */
  /* #339: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #340: @51 = @31' */
  casadi_copy(w31, 3, w51);
  /* #341: @2 = mac(@51,@48,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w51+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #342: @2 = @2' */
  /* #343: @50 = (@50+@2) */
  for (i=0, rr=w50, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #344: @2 = (@50/@16) */
  for (i=0, rr=w2, cr=w50; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #345: @51 = (@44/@16) */
  for (i=0, rr=w51, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #346: @70 = (@51*@28) */
  for (i=0, rr=w70, cr=w51; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #347: @2 = (@2-@70) */
  for (i=0, rr=w2, cs=w70; i<3; ++i) (*rr++) -= (*cs++);
  /* #348: @25 = dot(@42, @2) */
  w25 = casadi_dot(3, w42, w2);
  /* #349: @71 = dot(@1, @44) */
  w71 = casadi_dot(3, w1, w44);
  /* #350: @25 = (@25+@71) */
  w25 += w71;
  /* #351: @71 = (@5*@25) */
  w71  = (w5*w25);
  /* #352: @21 = (@21+@71) */
  w21 += w71;
  /* #353: @21 = (-@21) */
  w21 = (- w21 );
  /* #354: (@62[0] += @21) */
  for (rr=w62+0, ss=(&w21); rr!=w62+1; rr+=1) *rr += *ss++;
  /* #355: @21 = dot(@49, @50) */
  w21 = casadi_dot(3, w49, w50);
  /* #356: @31 = (@31/@16) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w16;
  /* #357: @47 = (@47/@16) */
  for (i=0, rr=w47; i<3; ++i) (*rr++) /= w16;
  /* #358: @50 = (@47*@28) */
  for (i=0, rr=w50, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #359: @31 = (@31-@50) */
  for (i=0, rr=w31, cs=w50; i<3; ++i) (*rr++) -= (*cs++);
  /* #360: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #361: @71 = dot(@31, @35) */
  w71 = casadi_dot(3, w31, w35);
  /* #362: @21 = (@21+@71) */
  w21 += w71;
  /* #363: @23 = (@23/@4) */
  w23 /= w4;
  /* #364: @71 = (@18/@4) */
  w71  = (w18/w4);
  /* #365: @20 = (@71*@20) */
  w20  = (w71*w20);
  /* #366: @23 = (@23-@20) */
  w23 -= w20;
  /* #367: @23 = (@13*@23) */
  w23  = (w13*w23);
  /* #368: @25 = (@18*@25) */
  w25  = (w18*w25);
  /* #369: @23 = (@23+@25) */
  w23 += w25;
  /* #370: @21 = (@21+@23) */
  w21 += w23;
  /* #371: @21 = (@21/@16) */
  w21 /= w16;
  /* #372: @23 = (@12/@16) */
  w23  = (w12/w16);
  /* #373: @28 = (@23*@28) */
  w28  = (w23*w28);
  /* #374: @21 = (@21-@28) */
  w21 -= w28;
  /* #375: @31 = (@41*@21) */
  for (i=0, rr=w31, cr=w41; i<3; ++i) (*rr++)  = ((*cr++)*w21);
  /* #376: @34 = (@12*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #377: @31 = (@31+@34) */
  for (i=0, rr=w31, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #378: @34 = (@44*@26) */
  for (i=0, rr=w34, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #379: @2 = (@11*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #380: @34 = (@34+@2) */
  for (i=0, rr=w34, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #381: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #382: @31 = (@31+@34) */
  for (i=0, rr=w31, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #383: (@62[1:4] += @31) */
  for (rr=w62+1, ss=w31; rr!=w62+4; rr+=1) *rr += *ss++;
  /* #384: @69 = (@0*@62) */
  for (i=0, rr=w69, cs=w62; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #385: @62 = (@19*@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #386: @69 = (@69-@62) */
  for (i=0, rr=w69, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #387: {@26, @21, @28, @25} = vertsplit(@69) */
  w26 = w69[0];
  w21 = w69[1];
  w28 = w69[2];
  w25 = w69[3];
  /* #388: @20 = (@9*@25) */
  w20  = (w9*w25);
  /* #389: @72 = (@8*@28) */
  w72  = (w8*w28);
  /* #390: @20 = (@20+@72) */
  w20 += w72;
  /* #391: @72 = (@7*@21) */
  w72  = (w7*w21);
  /* #392: @20 = (@20+@72) */
  w20 += w72;
  /* #393: @72 = (@6*@26) */
  w72  = (w6*w26);
  /* #394: @20 = (@20+@72) */
  w20 += w72;
  /* #395: @72 = (@8*@25) */
  w72  = (w8*w25);
  /* #396: @73 = (@9*@28) */
  w73  = (w9*w28);
  /* #397: @72 = (@72-@73) */
  w72 -= w73;
  /* #398: @73 = (@6*@21) */
  w73  = (w6*w21);
  /* #399: @72 = (@72+@73) */
  w72 += w73;
  /* #400: @73 = (@7*@26) */
  w73  = (w7*w26);
  /* #401: @72 = (@72-@73) */
  w72 -= w73;
  /* #402: @73 = (@6*@28) */
  w73  = (w6*w28);
  /* #403: @74 = (@7*@25) */
  w74  = (w7*w25);
  /* #404: @73 = (@73-@74) */
  w73 -= w74;
  /* #405: @74 = (@9*@21) */
  w74  = (w9*w21);
  /* #406: @73 = (@73+@74) */
  w73 += w74;
  /* #407: @74 = (@8*@26) */
  w74  = (w8*w26);
  /* #408: @73 = (@73-@74) */
  w73 -= w74;
  /* #409: @25 = (@6*@25) */
  w25  = (w6*w25);
  /* #410: @28 = (@7*@28) */
  w28  = (w7*w28);
  /* #411: @25 = (@25+@28) */
  w25 += w28;
  /* #412: @21 = (@8*@21) */
  w21  = (w8*w21);
  /* #413: @25 = (@25-@21) */
  w25 -= w21;
  /* #414: @26 = (@9*@26) */
  w26  = (w9*w26);
  /* #415: @25 = (@25-@26) */
  w25 -= w26;
  /* #416: @69 = vertcat(@20, @72, @73, @25) */
  rr=w69;
  *rr++ = w20;
  *rr++ = w72;
  *rr++ = w73;
  *rr++ = w25;
  /* #417: @20 = dot(@39, @69) */
  w20 = casadi_dot(4, w39, w69);
  /* #418: @67 = (@67/@10) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w10;
  /* #419: @40 = (@40/@10) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) /= w10;
  /* #420: @62 = (@40*@59) */
  for (i=0, rr=w62, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w59);
  /* #421: @67 = (@67-@62) */
  for (i=0, rr=w67, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #422: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #423: @72 = dot(@67, @52) */
  w72 = casadi_dot(4, w67, w52);
  /* #424: @20 = (@20+@72) */
  w20 += w72;
  /* #425: @20 = (@20/@10) */
  w20 /= w10;
  /* #426: @72 = (@24/@10) */
  w72  = (w24/w10);
  /* #427: @73 = (@72*@59) */
  w73  = (w72*w59);
  /* #428: @20 = (@20-@73) */
  w20 -= w73;
  /* #429: @67 = (@38*@20) */
  for (i=0, rr=w67, cr=w38; i<4; ++i) (*rr++)  = ((*cr++)*w20);
  /* #430: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #431: @62 = dense(@57) */
  casadi_densify((&w57), casadi_s1, w62, 0);
  /* #432: @67 = (@67+@62) */
  for (i=0, rr=w67, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #433: (@33[6:10] += @67) */
  for (rr=w33+6, ss=w67; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #434: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #435: @57 = project(@30) */
  casadi_sparsify(w30, (&w57), casadi_s2, 0);
  /* #436: @20 = @60[0] */
  for (rr=(&w20), ss=(&w60)+0; ss!=(&w60)+1; ss+=1) *rr++ = *ss;
  /* #437: @20 = (-@20) */
  w20 = (- w20 );
  /* #438: @60 = dot(@57, @20) */
  w60 = casadi_dot(1, (&w57), (&w20));
  /* #439: @34 = (@30*@60) */
  for (i=0, rr=w34, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #440: @2 = @34' */
  casadi_copy(w34, 3, w2);
  /* #441: @31 = mac(@2,@36,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #442: @31 = @31' */
  /* #443: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #444: @34 = @34' */
  /* #445: @2 = mac(@34,@53,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w53+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #446: @2 = @2' */
  /* #447: @31 = (@31+@2) */
  for (i=0, rr=w31, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #448: @60 = dot(@30, @31) */
  w60 = casadi_dot(3, w30, w31);
  /* #449: @31 = (@30*@60) */
  for (i=0, rr=w31, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #450: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #451: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #452: @50 = zeros(3x1) */
  casadi_clear(w50, 3);
  /* #453: @50 = mac(@3,@20,@50) */
  casadi_mtimes(w3, casadi_s4, (&w20), casadi_s2, w50, casadi_s3, w, 0);
  /* #454: @1 = @50' */
  casadi_copy(w50, 3, w1);
  /* #455: @34 = mac(@1,@32,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #456: @34 = @34' */
  /* #457: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #458: @50 = @50' */
  /* #459: @1 = mac(@50,@55,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w50+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #460: @1 = @1' */
  /* #461: @34 = (@34+@1) */
  for (i=0, rr=w34, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #462: @2 = mac(@54,@34,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w54+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #463: @31 = (@31+@2) */
  for (i=0, rr=w31, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #464: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #465: (@33[:3] += @31) */
  for (rr=w33+0, ss=w31; rr!=w33+3; rr+=1) *rr += *ss++;
  /* #466: {@20, @60, @57, @73, @25, @26, @21, @28, @74, @75, @76, @77, @78} = vertsplit(@33) */
  w20 = w33[0];
  w60 = w33[1];
  w57 = w33[2];
  w73 = w33[3];
  w25 = w33[4];
  w26 = w33[5];
  w21 = w33[6];
  w28 = w33[7];
  w74 = w33[8];
  w75 = w33[9];
  w76 = w33[10];
  w77 = w33[11];
  w78 = w33[12];
  /* #467: @69 = (@69/@10) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w10;
  /* #468: @46 = (@46/@10) */
  for (i=0, rr=w46; i<4; ++i) (*rr++) /= w10;
  /* #469: @67 = (@46*@59) */
  for (i=0, rr=w67, cr=w46; i<4; ++i) (*rr++)  = ((*cr++)*w59);
  /* #470: @69 = (@69-@67) */
  for (i=0, rr=w69, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #471: {@59, @79, @80, @81} = vertsplit(@69) */
  w59 = w69[0];
  w79 = w69[1];
  w80 = w69[2];
  w81 = w69[3];
  /* #472: @59 = (@59+@21) */
  w59 += w21;
  /* #473: @28 = (@28-@79) */
  w28 -= w79;
  /* #474: @74 = (@74-@80) */
  w74 -= w80;
  /* #475: @75 = (@75-@81) */
  w75 -= w81;
  /* #476: @33 = vertcat(@20, @60, @57, @73, @25, @26, @59, @28, @74, @75, @76, @77, @78) */
  rr=w33;
  *rr++ = w20;
  *rr++ = w60;
  *rr++ = w57;
  *rr++ = w73;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w59;
  *rr++ = w28;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w76;
  *rr++ = w77;
  *rr++ = w78;
  /* #477: @82 = @33[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w33; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #478: (@61[0, 1, 2, 9, 10, 11, 12] = @82) */
  for (cii=casadi_s6, rr=w61, ss=w82; cii!=casadi_s6+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #479: @82 = @33[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w33; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #480: (@61[0, 3, 6, 9, 13, 17, 21] = @82) */
  for (cii=casadi_s7, rr=w61, ss=w82; cii!=casadi_s7+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #481: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #482: @69 = zeros(4x1) */
  casadi_clear(w69, 4);
  /* #483: @64 = 00 */
  /* #484: @83 = ones(13x1,2nz) */
  casadi_fill(w83, 2, 1.);
  /* #485: {NULL, @20, NULL, NULL, NULL, NULL, NULL, @60, NULL, NULL, NULL, NULL, NULL} = vertsplit(@83) */
  w20 = w83[0];
  w60 = w83[1];
  /* #486: @57 = (-@60) */
  w57 = (- w60 );
  /* #487: @65 = 00 */
  /* #488: @66 = 00 */
  /* #489: @73 = vertcat(@64, @57, @65, @66) */
  rr=(&w73);
  *rr++ = w57;
  /* #490: @73 = (@73/@10) */
  w73 /= w10;
  /* #491: @67 = dense(@73) */
  casadi_densify((&w73), casadi_s8, w67, 0);
  /* #492: @73 = project(@38) */
  casadi_sparsify(w38, (&w73), casadi_s8, 0);
  /* #493: @57 = @60[0] */
  for (rr=(&w57), ss=(&w60)+0; ss!=(&w60)+1; ss+=1) *rr++ = *ss;
  /* #494: @60 = dot(@73, @57) */
  w60 = casadi_dot(1, (&w73), (&w57));
  /* #495: @60 = (@60/@10) */
  w60 /= w10;
  /* #496: @62 = (@37*@60) */
  for (i=0, rr=w62, cr=w37; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #497: @67 = (@67-@62) */
  for (i=0, rr=w67, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #498: {@73, @25, @26, @59} = vertsplit(@67) */
  w73 = w67[0];
  w25 = w67[1];
  w26 = w67[2];
  w59 = w67[3];
  /* #499: @28 = (@6*@73) */
  w28  = (w6*w73);
  /* #500: @74 = (@7*@25) */
  w74  = (w7*w25);
  /* #501: @28 = (@28-@74) */
  w28 -= w74;
  /* #502: @74 = (@8*@26) */
  w74  = (w8*w26);
  /* #503: @28 = (@28-@74) */
  w28 -= w74;
  /* #504: @74 = (@9*@59) */
  w74  = (w9*w59);
  /* #505: @28 = (@28-@74) */
  w28 -= w74;
  /* #506: @74 = (@7*@73) */
  w74  = (w7*w73);
  /* #507: @75 = (@6*@25) */
  w75  = (w6*w25);
  /* #508: @74 = (@74+@75) */
  w74 += w75;
  /* #509: @75 = (@9*@26) */
  w75  = (w9*w26);
  /* #510: @74 = (@74+@75) */
  w74 += w75;
  /* #511: @75 = (@8*@59) */
  w75  = (w8*w59);
  /* #512: @74 = (@74-@75) */
  w74 -= w75;
  /* #513: @75 = (@8*@73) */
  w75  = (w8*w73);
  /* #514: @76 = (@9*@25) */
  w76  = (w9*w25);
  /* #515: @75 = (@75-@76) */
  w75 -= w76;
  /* #516: @76 = (@6*@26) */
  w76  = (w6*w26);
  /* #517: @75 = (@75+@76) */
  w75 += w76;
  /* #518: @76 = (@7*@59) */
  w76  = (w7*w59);
  /* #519: @75 = (@75+@76) */
  w75 += w76;
  /* #520: @73 = (@9*@73) */
  w73  = (w9*w73);
  /* #521: @25 = (@8*@25) */
  w25  = (w8*w25);
  /* #522: @73 = (@73+@25) */
  w73 += w25;
  /* #523: @26 = (@7*@26) */
  w26  = (w7*w26);
  /* #524: @73 = (@73-@26) */
  w73 -= w26;
  /* #525: @59 = (@6*@59) */
  w59  = (w6*w59);
  /* #526: @73 = (@73+@59) */
  w73 += w59;
  /* #527: @62 = vertcat(@28, @74, @75, @73) */
  rr=w62;
  *rr++ = w28;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w73;
  /* #528: @68 = (@14*@62) */
  for (i=0, rr=w68, cs=w62; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #529: @62 = (@15*@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #530: @68 = (@68-@62) */
  for (i=0, rr=w68, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #531: @31 = @68[1:4] */
  for (rr=w31, ss=w68+1; ss!=w68+4; ss+=1) *rr++ = *ss;
  /* #532: @28 = dot(@41, @31) */
  w28 = casadi_dot(3, w41, w31);
  /* #533: @28 = (@28/@16) */
  w28 /= w16;
  /* #534: @74 = (@28/@4) */
  w74  = (w28/w4);
  /* #535: @75 = (@58*@28) */
  w75  = (w58*w28);
  /* #536: @73 = @68[0] */
  for (rr=(&w73), ss=w68+0; ss!=w68+1; ss+=1) *rr++ = *ss;
  /* #537: @59 = (@56*@73) */
  w59  = (w56*w73);
  /* #538: @75 = (@75+@59) */
  w75 += w59;
  /* #539: @59 = (@22*@75) */
  w59  = (w22*w75);
  /* #540: @74 = (@74-@59) */
  w74 -= w59;
  /* #541: @74 = (@13*@74) */
  w74  = (w13*w74);
  /* #542: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #543: @34 = (2.*@31) */
  for (i=0, rr=w34, cs=w31; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #544: @1 = (@11*@34) */
  for (i=0, rr=w1, cs=w34; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #545: @59 = (@17*@28) */
  w59  = (w17*w28);
  /* #546: @26 = (@27*@73) */
  w26  = (w27*w73);
  /* #547: @59 = (@59-@26) */
  w59 -= w26;
  /* #548: @50 = (@42*@59) */
  for (i=0, rr=w50, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w59);
  /* #549: @1 = (@1+@50) */
  for (i=0, rr=w1, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #550: @1 = (@1/@16) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w16;
  /* #551: @50 = (@43*@28) */
  for (i=0, rr=w50, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #552: @1 = (@1-@50) */
  for (i=0, rr=w1, cs=w50; i<3; ++i) (*rr++) -= (*cs++);
  /* #553: @50 = @1' */
  casadi_copy(w1, 3, w50);
  /* #554: @2 = mac(@50,@45,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w50+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #555: @2 = @2' */
  /* #556: @50 = zeros(1x3) */
  casadi_clear(w50, 3);
  /* #557: @70 = @1' */
  casadi_copy(w1, 3, w70);
  /* #558: @50 = mac(@70,@48,@50) */
  for (i=0, rr=w50; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w70+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #559: @50 = @50' */
  /* #560: @2 = (@2+@50) */
  for (i=0, rr=w2, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #561: @50 = (@2/@16) */
  for (i=0, rr=w50, cr=w2; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #562: @70 = (@51*@28) */
  for (i=0, rr=w70, cr=w51; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #563: @50 = (@50-@70) */
  for (i=0, rr=w50, cs=w70; i<3; ++i) (*rr++) -= (*cs++);
  /* #564: @26 = dot(@42, @50) */
  w26 = casadi_dot(3, w42, w50);
  /* #565: @25 = dot(@34, @44) */
  w25 = casadi_dot(3, w34, w44);
  /* #566: @26 = (@26+@25) */
  w26 += w25;
  /* #567: @25 = (@5*@26) */
  w25  = (w5*w26);
  /* #568: @74 = (@74+@25) */
  w74 += w25;
  /* #569: @74 = (-@74) */
  w74 = (- w74 );
  /* #570: (@69[0] += @74) */
  for (rr=w69+0, ss=(&w74); rr!=w69+1; rr+=1) *rr += *ss++;
  /* #571: @74 = dot(@49, @2) */
  w74 = casadi_dot(3, w49, w2);
  /* #572: @1 = (@1/@16) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w16;
  /* #573: @2 = (@47*@28) */
  for (i=0, rr=w2, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #574: @1 = (@1-@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #575: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #576: @25 = dot(@1, @35) */
  w25 = casadi_dot(3, w1, w35);
  /* #577: @74 = (@74+@25) */
  w74 += w25;
  /* #578: @73 = (@73/@4) */
  w73 /= w4;
  /* #579: @75 = (@71*@75) */
  w75  = (w71*w75);
  /* #580: @73 = (@73-@75) */
  w73 -= w75;
  /* #581: @73 = (@13*@73) */
  w73  = (w13*w73);
  /* #582: @26 = (@18*@26) */
  w26  = (w18*w26);
  /* #583: @73 = (@73+@26) */
  w73 += w26;
  /* #584: @74 = (@74+@73) */
  w74 += w73;
  /* #585: @74 = (@74/@16) */
  w74 /= w16;
  /* #586: @28 = (@23*@28) */
  w28  = (w23*w28);
  /* #587: @74 = (@74-@28) */
  w74 -= w28;
  /* #588: @1 = (@41*@74) */
  for (i=0, rr=w1, cr=w41; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #589: @31 = (@12*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #590: @1 = (@1+@31) */
  for (i=0, rr=w1, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #591: @31 = (@44*@59) */
  for (i=0, rr=w31, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w59);
  /* #592: @50 = (@11*@50) */
  for (i=0, rr=w50, cs=w50; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #593: @31 = (@31+@50) */
  for (i=0, rr=w31, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #594: @31 = (2.*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #595: @1 = (@1+@31) */
  for (i=0, rr=w1, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #596: (@69[1:4] += @1) */
  for (rr=w69+1, ss=w1; rr!=w69+4; rr+=1) *rr += *ss++;
  /* #597: @68 = (@0*@69) */
  for (i=0, rr=w68, cs=w69; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #598: @69 = (@19*@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #599: @68 = (@68-@69) */
  for (i=0, rr=w68, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #600: {@59, @74, @28, @73} = vertsplit(@68) */
  w59 = w68[0];
  w74 = w68[1];
  w28 = w68[2];
  w73 = w68[3];
  /* #601: @26 = (@9*@73) */
  w26  = (w9*w73);
  /* #602: @75 = (@8*@28) */
  w75  = (w8*w28);
  /* #603: @26 = (@26+@75) */
  w26 += w75;
  /* #604: @75 = (@7*@74) */
  w75  = (w7*w74);
  /* #605: @26 = (@26+@75) */
  w26 += w75;
  /* #606: @75 = (@6*@59) */
  w75  = (w6*w59);
  /* #607: @26 = (@26+@75) */
  w26 += w75;
  /* #608: @75 = (@8*@73) */
  w75  = (w8*w73);
  /* #609: @25 = (@9*@28) */
  w25  = (w9*w28);
  /* #610: @75 = (@75-@25) */
  w75 -= w25;
  /* #611: @25 = (@6*@74) */
  w25  = (w6*w74);
  /* #612: @75 = (@75+@25) */
  w75 += w25;
  /* #613: @25 = (@7*@59) */
  w25  = (w7*w59);
  /* #614: @75 = (@75-@25) */
  w75 -= w25;
  /* #615: @25 = (@6*@28) */
  w25  = (w6*w28);
  /* #616: @76 = (@7*@73) */
  w76  = (w7*w73);
  /* #617: @25 = (@25-@76) */
  w25 -= w76;
  /* #618: @76 = (@9*@74) */
  w76  = (w9*w74);
  /* #619: @25 = (@25+@76) */
  w25 += w76;
  /* #620: @76 = (@8*@59) */
  w76  = (w8*w59);
  /* #621: @25 = (@25-@76) */
  w25 -= w76;
  /* #622: @73 = (@6*@73) */
  w73  = (w6*w73);
  /* #623: @28 = (@7*@28) */
  w28  = (w7*w28);
  /* #624: @73 = (@73+@28) */
  w73 += w28;
  /* #625: @74 = (@8*@74) */
  w74  = (w8*w74);
  /* #626: @73 = (@73-@74) */
  w73 -= w74;
  /* #627: @59 = (@9*@59) */
  w59  = (w9*w59);
  /* #628: @73 = (@73-@59) */
  w73 -= w59;
  /* #629: @68 = vertcat(@26, @75, @25, @73) */
  rr=w68;
  *rr++ = w26;
  *rr++ = w75;
  *rr++ = w25;
  *rr++ = w73;
  /* #630: @26 = dot(@39, @68) */
  w26 = casadi_dot(4, w39, w68);
  /* #631: @67 = (@67/@10) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w10;
  /* #632: @69 = (@40*@60) */
  for (i=0, rr=w69, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #633: @67 = (@67-@69) */
  for (i=0, rr=w67, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #634: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #635: @75 = dot(@67, @52) */
  w75 = casadi_dot(4, w67, w52);
  /* #636: @26 = (@26+@75) */
  w26 += w75;
  /* #637: @26 = (@26/@10) */
  w26 /= w10;
  /* #638: @75 = (@72*@60) */
  w75  = (w72*w60);
  /* #639: @26 = (@26-@75) */
  w26 -= w75;
  /* #640: @67 = (@38*@26) */
  for (i=0, rr=w67, cr=w38; i<4; ++i) (*rr++)  = ((*cr++)*w26);
  /* #641: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #642: @69 = dense(@57) */
  casadi_densify((&w57), casadi_s8, w69, 0);
  /* #643: @67 = (@67+@69) */
  for (i=0, rr=w67, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #644: (@33[6:10] += @67) */
  for (rr=w33+6, ss=w67; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #645: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #646: @57 = project(@30) */
  casadi_sparsify(w30, (&w57), casadi_s9, 0);
  /* #647: @26 = @20[0] */
  for (rr=(&w26), ss=(&w20)+0; ss!=(&w20)+1; ss+=1) *rr++ = *ss;
  /* #648: @26 = (-@26) */
  w26 = (- w26 );
  /* #649: @20 = dot(@57, @26) */
  w20 = casadi_dot(1, (&w57), (&w26));
  /* #650: @31 = (@30*@20) */
  for (i=0, rr=w31, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w20);
  /* #651: @50 = @31' */
  casadi_copy(w31, 3, w50);
  /* #652: @1 = mac(@50,@36,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w50+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #653: @1 = @1' */
  /* #654: @50 = zeros(1x3) */
  casadi_clear(w50, 3);
  /* #655: @31 = @31' */
  /* #656: @50 = mac(@31,@53,@50) */
  for (i=0, rr=w50; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w53+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #657: @50 = @50' */
  /* #658: @1 = (@1+@50) */
  for (i=0, rr=w1, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #659: @20 = dot(@30, @1) */
  w20 = casadi_dot(3, w30, w1);
  /* #660: @1 = (@30*@20) */
  for (i=0, rr=w1, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w20);
  /* #661: @50 = zeros(3x1) */
  casadi_clear(w50, 3);
  /* #662: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #663: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #664: @2 = mac(@3,@26,@2) */
  casadi_mtimes(w3, casadi_s4, (&w26), casadi_s9, w2, casadi_s3, w, 0);
  /* #665: @34 = @2' */
  casadi_copy(w2, 3, w34);
  /* #666: @31 = mac(@34,@32,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #667: @31 = @31' */
  /* #668: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #669: @2 = @2' */
  /* #670: @34 = mac(@2,@55,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #671: @34 = @34' */
  /* #672: @31 = (@31+@34) */
  for (i=0, rr=w31, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #673: @50 = mac(@54,@31,@50) */
  for (i=0, rr=w50; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w54+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #674: @1 = (@1+@50) */
  for (i=0, rr=w1, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #675: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #676: (@33[:3] += @1) */
  for (rr=w33+0, ss=w1; rr!=w33+3; rr+=1) *rr += *ss++;
  /* #677: {@26, @20, @57, @75, @25, @73, @59, @74, @28, @76, @77, @78, @81} = vertsplit(@33) */
  w26 = w33[0];
  w20 = w33[1];
  w57 = w33[2];
  w75 = w33[3];
  w25 = w33[4];
  w73 = w33[5];
  w59 = w33[6];
  w74 = w33[7];
  w28 = w33[8];
  w76 = w33[9];
  w77 = w33[10];
  w78 = w33[11];
  w81 = w33[12];
  /* #678: @68 = (@68/@10) */
  for (i=0, rr=w68; i<4; ++i) (*rr++) /= w10;
  /* #679: @67 = (@46*@60) */
  for (i=0, rr=w67, cr=w46; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #680: @68 = (@68-@67) */
  for (i=0, rr=w68, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #681: {@60, @80, @79, @21} = vertsplit(@68) */
  w60 = w68[0];
  w80 = w68[1];
  w79 = w68[2];
  w21 = w68[3];
  /* #682: @60 = (@60+@59) */
  w60 += w59;
  /* #683: @74 = (@74-@80) */
  w74 -= w80;
  /* #684: @28 = (@28-@79) */
  w28 -= w79;
  /* #685: @76 = (@76-@21) */
  w76 -= w21;
  /* #686: @33 = vertcat(@26, @20, @57, @75, @25, @73, @60, @74, @28, @76, @77, @78, @81) */
  rr=w33;
  *rr++ = w26;
  *rr++ = w20;
  *rr++ = w57;
  *rr++ = w75;
  *rr++ = w25;
  *rr++ = w73;
  *rr++ = w60;
  *rr++ = w74;
  *rr++ = w28;
  *rr++ = w76;
  *rr++ = w77;
  *rr++ = w78;
  *rr++ = w81;
  /* #687: @82 = @33[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w33; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #688: (@61[3, 4, 5, 13, 14, 15, 16] = @82) */
  for (cii=casadi_s10, rr=w61, ss=w82; cii!=casadi_s10+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #689: @82 = @33[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w33; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #690: (@61[1, 4, 7, 10, 14, 18, 22] = @82) */
  for (cii=casadi_s11, rr=w61, ss=w82; cii!=casadi_s11+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #691: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #692: @68 = zeros(4x1) */
  casadi_clear(w68, 4);
  /* #693: @64 = 00 */
  /* #694: @65 = 00 */
  /* #695: @83 = ones(13x1,2nz) */
  casadi_fill(w83, 2, 1.);
  /* #696: {NULL, NULL, @26, NULL, NULL, NULL, NULL, NULL, @20, NULL, NULL, NULL, NULL} = vertsplit(@83) */
  w26 = w83[0];
  w20 = w83[1];
  /* #697: @57 = (-@20) */
  w57 = (- w20 );
  /* #698: @66 = 00 */
  /* #699: @75 = vertcat(@64, @65, @57, @66) */
  rr=(&w75);
  *rr++ = w57;
  /* #700: @75 = (@75/@10) */
  w75 /= w10;
  /* #701: @67 = dense(@75) */
  casadi_densify((&w75), casadi_s12, w67, 0);
  /* #702: @75 = project(@38) */
  casadi_sparsify(w38, (&w75), casadi_s12, 0);
  /* #703: @57 = @20[0] */
  for (rr=(&w57), ss=(&w20)+0; ss!=(&w20)+1; ss+=1) *rr++ = *ss;
  /* #704: @20 = dot(@75, @57) */
  w20 = casadi_dot(1, (&w75), (&w57));
  /* #705: @20 = (@20/@10) */
  w20 /= w10;
  /* #706: @69 = (@37*@20) */
  for (i=0, rr=w69, cr=w37; i<4; ++i) (*rr++)  = ((*cr++)*w20);
  /* #707: @67 = (@67-@69) */
  for (i=0, rr=w67, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #708: {@75, @25, @73, @60} = vertsplit(@67) */
  w75 = w67[0];
  w25 = w67[1];
  w73 = w67[2];
  w60 = w67[3];
  /* #709: @74 = (@6*@75) */
  w74  = (w6*w75);
  /* #710: @28 = (@7*@25) */
  w28  = (w7*w25);
  /* #711: @74 = (@74-@28) */
  w74 -= w28;
  /* #712: @28 = (@8*@73) */
  w28  = (w8*w73);
  /* #713: @74 = (@74-@28) */
  w74 -= w28;
  /* #714: @28 = (@9*@60) */
  w28  = (w9*w60);
  /* #715: @74 = (@74-@28) */
  w74 -= w28;
  /* #716: @28 = (@7*@75) */
  w28  = (w7*w75);
  /* #717: @76 = (@6*@25) */
  w76  = (w6*w25);
  /* #718: @28 = (@28+@76) */
  w28 += w76;
  /* #719: @76 = (@9*@73) */
  w76  = (w9*w73);
  /* #720: @28 = (@28+@76) */
  w28 += w76;
  /* #721: @76 = (@8*@60) */
  w76  = (w8*w60);
  /* #722: @28 = (@28-@76) */
  w28 -= w76;
  /* #723: @76 = (@8*@75) */
  w76  = (w8*w75);
  /* #724: @77 = (@9*@25) */
  w77  = (w9*w25);
  /* #725: @76 = (@76-@77) */
  w76 -= w77;
  /* #726: @77 = (@6*@73) */
  w77  = (w6*w73);
  /* #727: @76 = (@76+@77) */
  w76 += w77;
  /* #728: @77 = (@7*@60) */
  w77  = (w7*w60);
  /* #729: @76 = (@76+@77) */
  w76 += w77;
  /* #730: @75 = (@9*@75) */
  w75  = (w9*w75);
  /* #731: @25 = (@8*@25) */
  w25  = (w8*w25);
  /* #732: @75 = (@75+@25) */
  w75 += w25;
  /* #733: @73 = (@7*@73) */
  w73  = (w7*w73);
  /* #734: @75 = (@75-@73) */
  w75 -= w73;
  /* #735: @60 = (@6*@60) */
  w60  = (w6*w60);
  /* #736: @75 = (@75+@60) */
  w75 += w60;
  /* #737: @69 = vertcat(@74, @28, @76, @75) */
  rr=w69;
  *rr++ = w74;
  *rr++ = w28;
  *rr++ = w76;
  *rr++ = w75;
  /* #738: @62 = (@14*@69) */
  for (i=0, rr=w62, cs=w69; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #739: @69 = (@15*@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #740: @62 = (@62-@69) */
  for (i=0, rr=w62, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #741: @1 = @62[1:4] */
  for (rr=w1, ss=w62+1; ss!=w62+4; ss+=1) *rr++ = *ss;
  /* #742: @74 = dot(@41, @1) */
  w74 = casadi_dot(3, w41, w1);
  /* #743: @74 = (@74/@16) */
  w74 /= w16;
  /* #744: @28 = (@74/@4) */
  w28  = (w74/w4);
  /* #745: @76 = (@58*@74) */
  w76  = (w58*w74);
  /* #746: @75 = @62[0] */
  for (rr=(&w75), ss=w62+0; ss!=w62+1; ss+=1) *rr++ = *ss;
  /* #747: @60 = (@56*@75) */
  w60  = (w56*w75);
  /* #748: @76 = (@76+@60) */
  w76 += w60;
  /* #749: @60 = (@22*@76) */
  w60  = (w22*w76);
  /* #750: @28 = (@28-@60) */
  w28 -= w60;
  /* #751: @28 = (@13*@28) */
  w28  = (w13*w28);
  /* #752: @50 = zeros(1x3) */
  casadi_clear(w50, 3);
  /* #753: @31 = (2.*@1) */
  for (i=0, rr=w31, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #754: @34 = (@11*@31) */
  for (i=0, rr=w34, cs=w31; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #755: @60 = (@17*@74) */
  w60  = (w17*w74);
  /* #756: @73 = (@27*@75) */
  w73  = (w27*w75);
  /* #757: @60 = (@60-@73) */
  w60 -= w73;
  /* #758: @2 = (@42*@60) */
  for (i=0, rr=w2, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #759: @34 = (@34+@2) */
  for (i=0, rr=w34, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #760: @34 = (@34/@16) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) /= w16;
  /* #761: @2 = (@43*@74) */
  for (i=0, rr=w2, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #762: @34 = (@34-@2) */
  for (i=0, rr=w34, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #763: @2 = @34' */
  casadi_copy(w34, 3, w2);
  /* #764: @50 = mac(@2,@45,@50) */
  for (i=0, rr=w50; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #765: @50 = @50' */
  /* #766: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #767: @70 = @34' */
  casadi_copy(w34, 3, w70);
  /* #768: @2 = mac(@70,@48,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w70+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #769: @2 = @2' */
  /* #770: @50 = (@50+@2) */
  for (i=0, rr=w50, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #771: @2 = (@50/@16) */
  for (i=0, rr=w2, cr=w50; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #772: @70 = (@51*@74) */
  for (i=0, rr=w70, cr=w51; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #773: @2 = (@2-@70) */
  for (i=0, rr=w2, cs=w70; i<3; ++i) (*rr++) -= (*cs++);
  /* #774: @73 = dot(@42, @2) */
  w73 = casadi_dot(3, w42, w2);
  /* #775: @25 = dot(@31, @44) */
  w25 = casadi_dot(3, w31, w44);
  /* #776: @73 = (@73+@25) */
  w73 += w25;
  /* #777: @25 = (@5*@73) */
  w25  = (w5*w73);
  /* #778: @28 = (@28+@25) */
  w28 += w25;
  /* #779: @28 = (-@28) */
  w28 = (- w28 );
  /* #780: (@68[0] += @28) */
  for (rr=w68+0, ss=(&w28); rr!=w68+1; rr+=1) *rr += *ss++;
  /* #781: @28 = dot(@49, @50) */
  w28 = casadi_dot(3, w49, w50);
  /* #782: @34 = (@34/@16) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) /= w16;
  /* #783: @50 = (@47*@74) */
  for (i=0, rr=w50, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #784: @34 = (@34-@50) */
  for (i=0, rr=w34, cs=w50; i<3; ++i) (*rr++) -= (*cs++);
  /* #785: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #786: @25 = dot(@34, @35) */
  w25 = casadi_dot(3, w34, w35);
  /* #787: @28 = (@28+@25) */
  w28 += w25;
  /* #788: @75 = (@75/@4) */
  w75 /= w4;
  /* #789: @76 = (@71*@76) */
  w76  = (w71*w76);
  /* #790: @75 = (@75-@76) */
  w75 -= w76;
  /* #791: @75 = (@13*@75) */
  w75  = (w13*w75);
  /* #792: @73 = (@18*@73) */
  w73  = (w18*w73);
  /* #793: @75 = (@75+@73) */
  w75 += w73;
  /* #794: @28 = (@28+@75) */
  w28 += w75;
  /* #795: @28 = (@28/@16) */
  w28 /= w16;
  /* #796: @74 = (@23*@74) */
  w74  = (w23*w74);
  /* #797: @28 = (@28-@74) */
  w28 -= w74;
  /* #798: @34 = (@41*@28) */
  for (i=0, rr=w34, cr=w41; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #799: @1 = (@12*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #800: @34 = (@34+@1) */
  for (i=0, rr=w34, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #801: @1 = (@44*@60) */
  for (i=0, rr=w1, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #802: @2 = (@11*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #803: @1 = (@1+@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #804: @1 = (2.*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #805: @34 = (@34+@1) */
  for (i=0, rr=w34, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #806: (@68[1:4] += @34) */
  for (rr=w68+1, ss=w34; rr!=w68+4; rr+=1) *rr += *ss++;
  /* #807: @62 = (@0*@68) */
  for (i=0, rr=w62, cs=w68; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #808: @68 = (@19*@68) */
  for (i=0, rr=w68, cs=w68; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #809: @62 = (@62-@68) */
  for (i=0, rr=w62, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #810: {@60, @28, @74, @75} = vertsplit(@62) */
  w60 = w62[0];
  w28 = w62[1];
  w74 = w62[2];
  w75 = w62[3];
  /* #811: @73 = (@9*@75) */
  w73  = (w9*w75);
  /* #812: @76 = (@8*@74) */
  w76  = (w8*w74);
  /* #813: @73 = (@73+@76) */
  w73 += w76;
  /* #814: @76 = (@7*@28) */
  w76  = (w7*w28);
  /* #815: @73 = (@73+@76) */
  w73 += w76;
  /* #816: @76 = (@6*@60) */
  w76  = (w6*w60);
  /* #817: @73 = (@73+@76) */
  w73 += w76;
  /* #818: @76 = (@8*@75) */
  w76  = (w8*w75);
  /* #819: @25 = (@9*@74) */
  w25  = (w9*w74);
  /* #820: @76 = (@76-@25) */
  w76 -= w25;
  /* #821: @25 = (@6*@28) */
  w25  = (w6*w28);
  /* #822: @76 = (@76+@25) */
  w76 += w25;
  /* #823: @25 = (@7*@60) */
  w25  = (w7*w60);
  /* #824: @76 = (@76-@25) */
  w76 -= w25;
  /* #825: @25 = (@6*@74) */
  w25  = (w6*w74);
  /* #826: @77 = (@7*@75) */
  w77  = (w7*w75);
  /* #827: @25 = (@25-@77) */
  w25 -= w77;
  /* #828: @77 = (@9*@28) */
  w77  = (w9*w28);
  /* #829: @25 = (@25+@77) */
  w25 += w77;
  /* #830: @77 = (@8*@60) */
  w77  = (w8*w60);
  /* #831: @25 = (@25-@77) */
  w25 -= w77;
  /* #832: @75 = (@6*@75) */
  w75  = (w6*w75);
  /* #833: @74 = (@7*@74) */
  w74  = (w7*w74);
  /* #834: @75 = (@75+@74) */
  w75 += w74;
  /* #835: @28 = (@8*@28) */
  w28  = (w8*w28);
  /* #836: @75 = (@75-@28) */
  w75 -= w28;
  /* #837: @60 = (@9*@60) */
  w60  = (w9*w60);
  /* #838: @75 = (@75-@60) */
  w75 -= w60;
  /* #839: @62 = vertcat(@73, @76, @25, @75) */
  rr=w62;
  *rr++ = w73;
  *rr++ = w76;
  *rr++ = w25;
  *rr++ = w75;
  /* #840: @73 = dot(@39, @62) */
  w73 = casadi_dot(4, w39, w62);
  /* #841: @67 = (@67/@10) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w10;
  /* #842: @68 = (@40*@20) */
  for (i=0, rr=w68, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w20);
  /* #843: @67 = (@67-@68) */
  for (i=0, rr=w67, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #844: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #845: @76 = dot(@67, @52) */
  w76 = casadi_dot(4, w67, w52);
  /* #846: @73 = (@73+@76) */
  w73 += w76;
  /* #847: @73 = (@73/@10) */
  w73 /= w10;
  /* #848: @76 = (@72*@20) */
  w76  = (w72*w20);
  /* #849: @73 = (@73-@76) */
  w73 -= w76;
  /* #850: @67 = (@38*@73) */
  for (i=0, rr=w67, cr=w38; i<4; ++i) (*rr++)  = ((*cr++)*w73);
  /* #851: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #852: @68 = dense(@57) */
  casadi_densify((&w57), casadi_s12, w68, 0);
  /* #853: @67 = (@67+@68) */
  for (i=0, rr=w67, cs=w68; i<4; ++i) (*rr++) += (*cs++);
  /* #854: (@33[6:10] += @67) */
  for (rr=w33+6, ss=w67; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #855: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #856: @57 = project(@30) */
  casadi_sparsify(w30, (&w57), casadi_s13, 0);
  /* #857: @73 = @26[0] */
  for (rr=(&w73), ss=(&w26)+0; ss!=(&w26)+1; ss+=1) *rr++ = *ss;
  /* #858: @73 = (-@73) */
  w73 = (- w73 );
  /* #859: @26 = dot(@57, @73) */
  w26 = casadi_dot(1, (&w57), (&w73));
  /* #860: @1 = (@30*@26) */
  for (i=0, rr=w1, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #861: @2 = @1' */
  casadi_copy(w1, 3, w2);
  /* #862: @34 = mac(@2,@36,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #863: @34 = @34' */
  /* #864: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #865: @1 = @1' */
  /* #866: @2 = mac(@1,@53,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w53+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #867: @2 = @2' */
  /* #868: @34 = (@34+@2) */
  for (i=0, rr=w34, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #869: @26 = dot(@30, @34) */
  w26 = casadi_dot(3, w30, w34);
  /* #870: @30 = (@30*@26) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) *= w26;
  /* #871: @34 = zeros(3x1) */
  casadi_clear(w34, 3);
  /* #872: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #873: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #874: @1 = mac(@3,@73,@1) */
  casadi_mtimes(w3, casadi_s4, (&w73), casadi_s13, w1, casadi_s3, w, 0);
  /* #875: @50 = @1' */
  casadi_copy(w1, 3, w50);
  /* #876: @2 = mac(@50,@32,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w50+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #877: @2 = @2' */
  /* #878: @50 = zeros(1x3) */
  casadi_clear(w50, 3);
  /* #879: @1 = @1' */
  /* #880: @50 = mac(@1,@55,@50) */
  for (i=0, rr=w50; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #881: @50 = @50' */
  /* #882: @2 = (@2+@50) */
  for (i=0, rr=w2, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #883: @34 = mac(@54,@2,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w54+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #884: @30 = (@30+@34) */
  for (i=0, rr=w30, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #885: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #886: (@33[:3] += @30) */
  for (rr=w33+0, ss=w30; rr!=w33+3; rr+=1) *rr += *ss++;
  /* #887: {@73, @26, @57, @76, @25, @75, @60, @28, @74, @77, @78, @81, @21} = vertsplit(@33) */
  w73 = w33[0];
  w26 = w33[1];
  w57 = w33[2];
  w76 = w33[3];
  w25 = w33[4];
  w75 = w33[5];
  w60 = w33[6];
  w28 = w33[7];
  w74 = w33[8];
  w77 = w33[9];
  w78 = w33[10];
  w81 = w33[11];
  w21 = w33[12];
  /* #888: @62 = (@62/@10) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w10;
  /* #889: @67 = (@46*@20) */
  for (i=0, rr=w67, cr=w46; i<4; ++i) (*rr++)  = ((*cr++)*w20);
  /* #890: @62 = (@62-@67) */
  for (i=0, rr=w62, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #891: {@20, @79, @80, @59} = vertsplit(@62) */
  w20 = w62[0];
  w79 = w62[1];
  w80 = w62[2];
  w59 = w62[3];
  /* #892: @20 = (@20+@60) */
  w20 += w60;
  /* #893: @28 = (@28-@79) */
  w28 -= w79;
  /* #894: @74 = (@74-@80) */
  w74 -= w80;
  /* #895: @77 = (@77-@59) */
  w77 -= w59;
  /* #896: @33 = vertcat(@73, @26, @57, @76, @25, @75, @20, @28, @74, @77, @78, @81, @21) */
  rr=w33;
  *rr++ = w73;
  *rr++ = w26;
  *rr++ = w57;
  *rr++ = w76;
  *rr++ = w25;
  *rr++ = w75;
  *rr++ = w20;
  *rr++ = w28;
  *rr++ = w74;
  *rr++ = w77;
  *rr++ = w78;
  *rr++ = w81;
  *rr++ = w21;
  /* #897: @82 = @33[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w33; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #898: (@61[6, 7, 8, 17, 18, 19, 20] = @82) */
  for (cii=casadi_s14, rr=w61, ss=w82; cii!=casadi_s14+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #899: @82 = @33[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w33; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #900: (@61[2, 5, 8, 11, 15, 19, 23] = @82) */
  for (cii=casadi_s15, rr=w61, ss=w82; cii!=casadi_s15+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #901: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #902: @62 = zeros(4x1) */
  casadi_clear(w62, 4);
  /* #903: @64 = 00 */
  /* #904: @65 = 00 */
  /* #905: @66 = 00 */
  /* #906: @73 = ones(13x1,1nz) */
  w73 = 1.;
  /* #907: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @26, NULL, NULL, NULL} = vertsplit(@73) */
  w26 = w73;
  /* #908: @73 = (-@26) */
  w73 = (- w26 );
  /* #909: @57 = vertcat(@64, @65, @66, @73) */
  rr=(&w57);
  *rr++ = w73;
  /* #910: @57 = (@57/@10) */
  w57 /= w10;
  /* #911: @67 = dense(@57) */
  casadi_densify((&w57), casadi_s16, w67, 0);
  /* #912: @57 = project(@38) */
  casadi_sparsify(w38, (&w57), casadi_s16, 0);
  /* #913: @73 = @26[0] */
  for (rr=(&w73), ss=(&w26)+0; ss!=(&w26)+1; ss+=1) *rr++ = *ss;
  /* #914: @26 = dot(@57, @73) */
  w26 = casadi_dot(1, (&w57), (&w73));
  /* #915: @26 = (@26/@10) */
  w26 /= w10;
  /* #916: @37 = (@37*@26) */
  for (i=0, rr=w37; i<4; ++i) (*rr++) *= w26;
  /* #917: @67 = (@67-@37) */
  for (i=0, rr=w67, cs=w37; i<4; ++i) (*rr++) -= (*cs++);
  /* #918: {@57, @76, @25, @75} = vertsplit(@67) */
  w57 = w67[0];
  w76 = w67[1];
  w25 = w67[2];
  w75 = w67[3];
  /* #919: @20 = (@6*@57) */
  w20  = (w6*w57);
  /* #920: @28 = (@7*@76) */
  w28  = (w7*w76);
  /* #921: @20 = (@20-@28) */
  w20 -= w28;
  /* #922: @28 = (@8*@25) */
  w28  = (w8*w25);
  /* #923: @20 = (@20-@28) */
  w20 -= w28;
  /* #924: @28 = (@9*@75) */
  w28  = (w9*w75);
  /* #925: @20 = (@20-@28) */
  w20 -= w28;
  /* #926: @28 = (@7*@57) */
  w28  = (w7*w57);
  /* #927: @74 = (@6*@76) */
  w74  = (w6*w76);
  /* #928: @28 = (@28+@74) */
  w28 += w74;
  /* #929: @74 = (@9*@25) */
  w74  = (w9*w25);
  /* #930: @28 = (@28+@74) */
  w28 += w74;
  /* #931: @74 = (@8*@75) */
  w74  = (w8*w75);
  /* #932: @28 = (@28-@74) */
  w28 -= w74;
  /* #933: @74 = (@8*@57) */
  w74  = (w8*w57);
  /* #934: @77 = (@9*@76) */
  w77  = (w9*w76);
  /* #935: @74 = (@74-@77) */
  w74 -= w77;
  /* #936: @77 = (@6*@25) */
  w77  = (w6*w25);
  /* #937: @74 = (@74+@77) */
  w74 += w77;
  /* #938: @77 = (@7*@75) */
  w77  = (w7*w75);
  /* #939: @74 = (@74+@77) */
  w74 += w77;
  /* #940: @57 = (@9*@57) */
  w57  = (w9*w57);
  /* #941: @76 = (@8*@76) */
  w76  = (w8*w76);
  /* #942: @57 = (@57+@76) */
  w57 += w76;
  /* #943: @25 = (@7*@25) */
  w25  = (w7*w25);
  /* #944: @57 = (@57-@25) */
  w57 -= w25;
  /* #945: @75 = (@6*@75) */
  w75  = (w6*w75);
  /* #946: @57 = (@57+@75) */
  w57 += w75;
  /* #947: @37 = vertcat(@20, @28, @74, @57) */
  rr=w37;
  *rr++ = w20;
  *rr++ = w28;
  *rr++ = w74;
  *rr++ = w57;
  /* #948: @68 = (@14*@37) */
  for (i=0, rr=w68, cs=w37; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #949: @37 = (@15*@37) */
  for (i=0, rr=w37, cs=w37; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #950: @68 = (@68-@37) */
  for (i=0, rr=w68, cs=w37; i<4; ++i) (*rr++) -= (*cs++);
  /* #951: @30 = @68[1:4] */
  for (rr=w30, ss=w68+1; ss!=w68+4; ss+=1) *rr++ = *ss;
  /* #952: @15 = dot(@41, @30) */
  w15 = casadi_dot(3, w41, w30);
  /* #953: @15 = (@15/@16) */
  w15 /= w16;
  /* #954: @14 = (@15/@4) */
  w14  = (w15/w4);
  /* #955: @58 = (@58*@15) */
  w58 *= w15;
  /* #956: @20 = @68[0] */
  for (rr=(&w20), ss=w68+0; ss!=w68+1; ss+=1) *rr++ = *ss;
  /* #957: @56 = (@56*@20) */
  w56 *= w20;
  /* #958: @58 = (@58+@56) */
  w58 += w56;
  /* #959: @22 = (@22*@58) */
  w22 *= w58;
  /* #960: @14 = (@14-@22) */
  w14 -= w22;
  /* #961: @14 = (@13*@14) */
  w14  = (w13*w14);
  /* #962: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #963: @2 = (2.*@30) */
  for (i=0, rr=w2, cs=w30; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #964: @50 = (@11*@2) */
  for (i=0, rr=w50, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #965: @17 = (@17*@15) */
  w17 *= w15;
  /* #966: @27 = (@27*@20) */
  w27 *= w20;
  /* #967: @17 = (@17-@27) */
  w17 -= w27;
  /* #968: @1 = (@42*@17) */
  for (i=0, rr=w1, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #969: @50 = (@50+@1) */
  for (i=0, rr=w50, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #970: @50 = (@50/@16) */
  for (i=0, rr=w50; i<3; ++i) (*rr++) /= w16;
  /* #971: @43 = (@43*@15) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) *= w15;
  /* #972: @50 = (@50-@43) */
  for (i=0, rr=w50, cs=w43; i<3; ++i) (*rr++) -= (*cs++);
  /* #973: @43 = @50' */
  casadi_copy(w50, 3, w43);
  /* #974: @34 = mac(@43,@45,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #975: @34 = @34' */
  /* #976: @43 = zeros(1x3) */
  casadi_clear(w43, 3);
  /* #977: @1 = @50' */
  casadi_copy(w50, 3, w1);
  /* #978: @43 = mac(@1,@48,@43) */
  for (i=0, rr=w43; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #979: @43 = @43' */
  /* #980: @34 = (@34+@43) */
  for (i=0, rr=w34, cs=w43; i<3; ++i) (*rr++) += (*cs++);
  /* #981: @43 = (@34/@16) */
  for (i=0, rr=w43, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #982: @51 = (@51*@15) */
  for (i=0, rr=w51; i<3; ++i) (*rr++) *= w15;
  /* #983: @43 = (@43-@51) */
  for (i=0, rr=w43, cs=w51; i<3; ++i) (*rr++) -= (*cs++);
  /* #984: @27 = dot(@42, @43) */
  w27 = casadi_dot(3, w42, w43);
  /* #985: @22 = dot(@2, @44) */
  w22 = casadi_dot(3, w2, w44);
  /* #986: @27 = (@27+@22) */
  w27 += w22;
  /* #987: @5 = (@5*@27) */
  w5 *= w27;
  /* #988: @14 = (@14+@5) */
  w14 += w5;
  /* #989: @14 = (-@14) */
  w14 = (- w14 );
  /* #990: (@62[0] += @14) */
  for (rr=w62+0, ss=(&w14); rr!=w62+1; rr+=1) *rr += *ss++;
  /* #991: @14 = dot(@49, @34) */
  w14 = casadi_dot(3, w49, w34);
  /* #992: @50 = (@50/@16) */
  for (i=0, rr=w50; i<3; ++i) (*rr++) /= w16;
  /* #993: @47 = (@47*@15) */
  for (i=0, rr=w47; i<3; ++i) (*rr++) *= w15;
  /* #994: @50 = (@50-@47) */
  for (i=0, rr=w50, cs=w47; i<3; ++i) (*rr++) -= (*cs++);
  /* #995: @50 = (-@50) */
  for (i=0, rr=w50, cs=w50; i<3; ++i) *rr++ = (- *cs++ );
  /* #996: @5 = dot(@50, @35) */
  w5 = casadi_dot(3, w50, w35);
  /* #997: @14 = (@14+@5) */
  w14 += w5;
  /* #998: @20 = (@20/@4) */
  w20 /= w4;
  /* #999: @71 = (@71*@58) */
  w71 *= w58;
  /* #1000: @20 = (@20-@71) */
  w20 -= w71;
  /* #1001: @13 = (@13*@20) */
  w13 *= w20;
  /* #1002: @18 = (@18*@27) */
  w18 *= w27;
  /* #1003: @13 = (@13+@18) */
  w13 += w18;
  /* #1004: @14 = (@14+@13) */
  w14 += w13;
  /* #1005: @14 = (@14/@16) */
  w14 /= w16;
  /* #1006: @23 = (@23*@15) */
  w23 *= w15;
  /* #1007: @14 = (@14-@23) */
  w14 -= w23;
  /* #1008: @41 = (@41*@14) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) *= w14;
  /* #1009: @30 = (@12*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #1010: @41 = (@41+@30) */
  for (i=0, rr=w41, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #1011: @44 = (@44*@17) */
  for (i=0, rr=w44; i<3; ++i) (*rr++) *= w17;
  /* #1012: @43 = (@11*@43) */
  for (i=0, rr=w43, cs=w43; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #1013: @44 = (@44+@43) */
  for (i=0, rr=w44, cs=w43; i<3; ++i) (*rr++) += (*cs++);
  /* #1014: @44 = (2.*@44) */
  for (i=0, rr=w44, cs=w44; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1015: @41 = (@41+@44) */
  for (i=0, rr=w41, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #1016: (@62[1:4] += @41) */
  for (rr=w62+1, ss=w41; rr!=w62+4; rr+=1) *rr += *ss++;
  /* #1017: @68 = (@0*@62) */
  for (i=0, rr=w68, cs=w62; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #1018: @62 = (@19*@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #1019: @68 = (@68-@62) */
  for (i=0, rr=w68, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #1020: {@19, @0, @11, @17} = vertsplit(@68) */
  w19 = w68[0];
  w0 = w68[1];
  w11 = w68[2];
  w17 = w68[3];
  /* #1021: @12 = (@9*@17) */
  w12  = (w9*w17);
  /* #1022: @14 = (@8*@11) */
  w14  = (w8*w11);
  /* #1023: @12 = (@12+@14) */
  w12 += w14;
  /* #1024: @14 = (@7*@0) */
  w14  = (w7*w0);
  /* #1025: @12 = (@12+@14) */
  w12 += w14;
  /* #1026: @14 = (@6*@19) */
  w14  = (w6*w19);
  /* #1027: @12 = (@12+@14) */
  w12 += w14;
  /* #1028: @14 = (@8*@17) */
  w14  = (w8*w17);
  /* #1029: @23 = (@9*@11) */
  w23  = (w9*w11);
  /* #1030: @14 = (@14-@23) */
  w14 -= w23;
  /* #1031: @23 = (@6*@0) */
  w23  = (w6*w0);
  /* #1032: @14 = (@14+@23) */
  w14 += w23;
  /* #1033: @23 = (@7*@19) */
  w23  = (w7*w19);
  /* #1034: @14 = (@14-@23) */
  w14 -= w23;
  /* #1035: @23 = (@6*@11) */
  w23  = (w6*w11);
  /* #1036: @15 = (@7*@17) */
  w15  = (w7*w17);
  /* #1037: @23 = (@23-@15) */
  w23 -= w15;
  /* #1038: @15 = (@9*@0) */
  w15  = (w9*w0);
  /* #1039: @23 = (@23+@15) */
  w23 += w15;
  /* #1040: @15 = (@8*@19) */
  w15  = (w8*w19);
  /* #1041: @23 = (@23-@15) */
  w23 -= w15;
  /* #1042: @6 = (@6*@17) */
  w6 *= w17;
  /* #1043: @7 = (@7*@11) */
  w7 *= w11;
  /* #1044: @6 = (@6+@7) */
  w6 += w7;
  /* #1045: @8 = (@8*@0) */
  w8 *= w0;
  /* #1046: @6 = (@6-@8) */
  w6 -= w8;
  /* #1047: @9 = (@9*@19) */
  w9 *= w19;
  /* #1048: @6 = (@6-@9) */
  w6 -= w9;
  /* #1049: @68 = vertcat(@12, @14, @23, @6) */
  rr=w68;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w23;
  *rr++ = w6;
  /* #1050: @12 = dot(@39, @68) */
  w12 = casadi_dot(4, w39, w68);
  /* #1051: @67 = (@67/@10) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w10;
  /* #1052: @40 = (@40*@26) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) *= w26;
  /* #1053: @67 = (@67-@40) */
  for (i=0, rr=w67, cs=w40; i<4; ++i) (*rr++) -= (*cs++);
  /* #1054: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #1055: @14 = dot(@67, @52) */
  w14 = casadi_dot(4, w67, w52);
  /* #1056: @12 = (@12+@14) */
  w12 += w14;
  /* #1057: @12 = (@12/@10) */
  w12 /= w10;
  /* #1058: @72 = (@72*@26) */
  w72 *= w26;
  /* #1059: @12 = (@12-@72) */
  w12 -= w72;
  /* #1060: @38 = (@38*@12) */
  for (i=0, rr=w38; i<4; ++i) (*rr++) *= w12;
  /* #1061: @24 = (@24*@73) */
  w24 *= w73;
  /* #1062: @67 = dense(@24) */
  casadi_densify((&w24), casadi_s16, w67, 0);
  /* #1063: @38 = (@38+@67) */
  for (i=0, rr=w38, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #1064: (@33[6:10] += @38) */
  for (rr=w33+6, ss=w38; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #1065: {@24, @73, @12, @72, @14, @23, @6, @9, @19, @8, @0, @7, @11} = vertsplit(@33) */
  w24 = w33[0];
  w73 = w33[1];
  w12 = w33[2];
  w72 = w33[3];
  w14 = w33[4];
  w23 = w33[5];
  w6 = w33[6];
  w9 = w33[7];
  w19 = w33[8];
  w8 = w33[9];
  w0 = w33[10];
  w7 = w33[11];
  w11 = w33[12];
  /* #1066: @68 = (@68/@10) */
  for (i=0, rr=w68; i<4; ++i) (*rr++) /= w10;
  /* #1067: @46 = (@46*@26) */
  for (i=0, rr=w46; i<4; ++i) (*rr++) *= w26;
  /* #1068: @68 = (@68-@46) */
  for (i=0, rr=w68, cs=w46; i<4; ++i) (*rr++) -= (*cs++);
  /* #1069: {@26, @10, @17, @15} = vertsplit(@68) */
  w26 = w68[0];
  w10 = w68[1];
  w17 = w68[2];
  w15 = w68[3];
  /* #1070: @26 = (@26+@6) */
  w26 += w6;
  /* #1071: @9 = (@9-@10) */
  w9 -= w10;
  /* #1072: @19 = (@19-@17) */
  w19 -= w17;
  /* #1073: @8 = (@8-@15) */
  w8 -= w15;
  /* #1074: @33 = vertcat(@24, @73, @12, @72, @14, @23, @26, @9, @19, @8, @0, @7, @11) */
  rr=w33;
  *rr++ = w24;
  *rr++ = w73;
  *rr++ = w12;
  *rr++ = w72;
  *rr++ = w14;
  *rr++ = w23;
  *rr++ = w26;
  *rr++ = w9;
  *rr++ = w19;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w7;
  *rr++ = w11;
  /* #1075: @68 = @33[6:10] */
  for (rr=w68, ss=w33+6; ss!=w33+10; ss+=1) *rr++ = *ss;
  /* #1076: (@61[21:25] = @68) */
  for (rr=w61+21, ss=w68; rr!=w61+25; rr+=1) *rr = *ss++;
  /* #1077: @68 = @33[6:10] */
  for (rr=w68, ss=w33+6; ss!=w33+10; ss+=1) *rr++ = *ss;
  /* #1078: (@61[12:28:4] = @68) */
  for (rr=w61+12, ss=w68; rr!=w61+28; rr+=4) *rr = *ss++;
  /* #1079: @84 = @61' */
  casadi_trans(w61,casadi_s17, w84, casadi_s17, iw);
  /* #1080: output[2][0] = @84 */
  casadi_copy(w84, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s19;
    case 2: return casadi_s19;
    case 3: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s21;
    case 1: return casadi_s18;
    case 2: return casadi_s17;
    case 3: return casadi_s19;
    case 4: return casadi_s22;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 28;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 306;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
