/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s4[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s5[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s6[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s7[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s8[11] = {0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13};
static const casadi_int casadi_s9[11] = {0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28};
static const casadi_int casadi_s10[11] = {0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37};
static const casadi_int casadi_s11[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s12[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s13[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s14[11] = {4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32};
static const casadi_int casadi_s15[11] = {1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38};
static const casadi_int casadi_s16[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s17[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s18[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s19[11] = {8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36};
static const casadi_int casadi_s20[11] = {2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39};
static const casadi_int casadi_s21[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s22[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s23[61] = {17, 17, 0, 4, 8, 12, 16, 19, 22, 25, 25, 25, 25, 29, 33, 37, 41, 41, 41, 41, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13};
static const casadi_int casadi_s24[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s25[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s26[3] = {0, 0, 0};
static const casadi_int casadi_s27[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s28[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s29[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s30[20] = {0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[9] = {3., 0., 0., 0., 3., 0., 0., 0., 3.};
static const casadi_real casadi_c2[16] = {2.0000000000000000e-03, 0., 0., 0., 0., 200., 0., 0., 0., 0., 200., 0., 0., 0., 0., 200.};

/* Drone_ode_complete_cost_ext_cost_fun_jac_hess:(i0[13],i1[4],i2[],i3[24])->(o0,o1[17],o2[17x17,41nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+4, *w2=w+7, *w3=w+10, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, *w29=w+44, *w30=w+68, *w31=w+71, *w32=w+74, *w33=w+83, *w34=w+96, *w35=w+99, *w36=w+102, *w37=w+111, *w38=w+115, *w39=w+119, *w40=w+123, *w41=w+127, *w42=w+130, *w43=w+133, *w44=w+136, *w45=w+139, *w46=w+148, *w47=w+152, *w48=w+168, *w49=w+184, *w50=w+187, *w51=w+196, *w52=w+199, *w53=w+202, *w54=w+205, *w55=w+209, *w56=w+218, *w57=w+227, w58, w59, w60, w61, w62, *w63=w+241, *w64=w+282, *w65=w+286, *w69=w+295, *w70=w+299, w71, w72, *w73=w+305, w74, w75, *w76=w+311, w77, w78, w79, w80, w81, w82, w83, w84, w85, w86, w87, *w88=w+325, *w89=w+342, *w90=w+353, *w91=w+355, *w92=w+363;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #6: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #7: @7 = input[3][2] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #8: @8 = input[3][3] */
  w8 = arg[3] ? arg[3][3] : 0;
  /* #9: @9 = input[3][4] */
  w9 = arg[3] ? arg[3][4] : 0;
  /* #10: @10 = input[3][5] */
  w10 = arg[3] ? arg[3][5] : 0;
  /* #11: @11 = input[3][6] */
  w11 = arg[3] ? arg[3][6] : 0;
  /* #12: @12 = input[3][7] */
  w12 = arg[3] ? arg[3][7] : 0;
  /* #13: @13 = input[3][8] */
  w13 = arg[3] ? arg[3][8] : 0;
  /* #14: @14 = input[3][9] */
  w14 = arg[3] ? arg[3][9] : 0;
  /* #15: @15 = input[3][10] */
  w15 = arg[3] ? arg[3][10] : 0;
  /* #16: @16 = input[3][11] */
  w16 = arg[3] ? arg[3][11] : 0;
  /* #17: @17 = input[3][12] */
  w17 = arg[3] ? arg[3][12] : 0;
  /* #18: @18 = input[3][13] */
  w18 = arg[3] ? arg[3][13] : 0;
  /* #19: @19 = input[3][14] */
  w19 = arg[3] ? arg[3][14] : 0;
  /* #20: @20 = input[3][15] */
  w20 = arg[3] ? arg[3][15] : 0;
  /* #21: @21 = input[3][16] */
  w21 = arg[3] ? arg[3][16] : 0;
  /* #22: @22 = input[3][17] */
  w22 = arg[3] ? arg[3][17] : 0;
  /* #23: @23 = input[3][18] */
  w23 = arg[3] ? arg[3][18] : 0;
  /* #24: @24 = input[3][19] */
  w24 = arg[3] ? arg[3][19] : 0;
  /* #25: @25 = input[3][20] */
  w25 = arg[3] ? arg[3][20] : 0;
  /* #26: @26 = input[3][21] */
  w26 = arg[3] ? arg[3][21] : 0;
  /* #27: @27 = input[3][22] */
  w27 = arg[3] ? arg[3][22] : 0;
  /* #28: @28 = input[3][23] */
  w28 = arg[3] ? arg[3][23] : 0;
  /* #29: @29 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28) */
  rr=w29;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  /* #30: @30 = @29[3:6] */
  for (rr=w30, ss=w29+3; ss!=w29+6; ss+=1) *rr++ = *ss;
  /* #31: @31 = @30' */
  casadi_copy(w30, 3, w31);
  /* #32: @4 = mac(@31,@30,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #33: @32 = @4[0, 0, 0, 0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w32, ss=(&w4); cii!=casadi_s0+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #34: @3 = (@3-@32) */
  for (i=0, rr=w3, cs=w32; i<9; ++i) (*rr++) -= (*cs++);
  /* #35: @31 = @29[:3] */
  for (rr=w31, ss=w29+0; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #36: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #37: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #38: @6 = input[0][2] */
  w6 = arg[0] ? arg[0][2] : 0;
  /* #39: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #40: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #41: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #42: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #43: @11 = input[0][7] */
  w11 = arg[0] ? arg[0][7] : 0;
  /* #44: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #45: @13 = input[0][9] */
  w13 = arg[0] ? arg[0][9] : 0;
  /* #46: @14 = input[0][10] */
  w14 = arg[0] ? arg[0][10] : 0;
  /* #47: @15 = input[0][11] */
  w15 = arg[0] ? arg[0][11] : 0;
  /* #48: @16 = input[0][12] */
  w16 = arg[0] ? arg[0][12] : 0;
  /* #49: @33 = vertcat(@4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w33;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #50: @34 = @33[:3] */
  for (rr=w34, ss=w33+0; ss!=w33+3; ss+=1) *rr++ = *ss;
  /* #51: @31 = (@31-@34) */
  for (i=0, rr=w31, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #52: @2 = mac(@3,@31,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #53: @34 = @2' */
  casadi_copy(w2, 3, w34);
  /* #54: @32 = 
  [[3, 0, 0], 
   [0, 3, 0], 
   [0, 0, 3]] */
  casadi_copy(casadi_c1, 9, w32);
  /* #55: @1 = mac(@34,@32,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #56: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #57: @4 = 0 */
  w4 = 0.;
  /* #58: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #59: @5 = dot(@30, @31) */
  w5 = casadi_dot(3, w30, w31);
  /* #60: @31 = (@5*@30) */
  for (i=0, rr=w31, cs=w30; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #61: @35 = @31' */
  casadi_copy(w31, 3, w35);
  /* #62: @36 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w36);
  /* #63: @34 = mac(@35,@36,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #64: @4 = mac(@34,@31,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #65: @0 = (@0+@4) */
  w0 += w4;
  /* #66: @4 = 0 */
  w4 = 0.;
  /* #67: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #68: @11 = (-@11) */
  w11 = (- w11 );
  /* #69: @12 = (-@12) */
  w12 = (- w12 );
  /* #70: @13 = (-@13) */
  w13 = (- w13 );
  /* #71: @37 = vertcat(@10, @11, @12, @13) */
  rr=w37;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #72: @38 = @33[6:10] */
  for (rr=w38, ss=w33+6; ss!=w33+10; ss+=1) *rr++ = *ss;
  /* #73: @10 = ||@38||_F */
  w10 = sqrt(casadi_dot(4, w38, w38));
  /* #74: @37 = (@37/@10) */
  for (i=0, rr=w37; i<4; ++i) (*rr++) /= w10;
  /* #75: {@11, @12, @13, @5} = vertsplit(@37) */
  w11 = w37[0];
  w12 = w37[1];
  w13 = w37[2];
  w5 = w37[3];
  /* #76: @39 = @29[6:10] */
  for (rr=w39, ss=w29+6; ss!=w29+10; ss+=1) *rr++ = *ss;
  /* #77: {@6, @7, @8, @9} = vertsplit(@39) */
  w6 = w39[0];
  w7 = w39[1];
  w8 = w39[2];
  w9 = w39[3];
  /* #78: @14 = (@11*@6) */
  w14  = (w11*w6);
  /* #79: @15 = (@12*@7) */
  w15  = (w12*w7);
  /* #80: @14 = (@14-@15) */
  w14 -= w15;
  /* #81: @15 = (@13*@8) */
  w15  = (w13*w8);
  /* #82: @14 = (@14-@15) */
  w14 -= w15;
  /* #83: @15 = (@5*@9) */
  w15  = (w5*w9);
  /* #84: @14 = (@14-@15) */
  w14 -= w15;
  /* #85: @15 = 0 */
  w15 = 0.;
  /* #86: @15 = (@14<@15) */
  w15  = (w14<w15);
  /* #87: @16 = (@11*@7) */
  w16  = (w11*w7);
  /* #88: @17 = (@12*@6) */
  w17  = (w12*w6);
  /* #89: @16 = (@16+@17) */
  w16 += w17;
  /* #90: @17 = (@13*@9) */
  w17  = (w13*w9);
  /* #91: @16 = (@16+@17) */
  w16 += w17;
  /* #92: @17 = (@5*@8) */
  w17  = (w5*w8);
  /* #93: @16 = (@16-@17) */
  w16 -= w17;
  /* #94: @17 = (@11*@8) */
  w17  = (w11*w8);
  /* #95: @18 = (@12*@9) */
  w18  = (w12*w9);
  /* #96: @17 = (@17-@18) */
  w17 -= w18;
  /* #97: @18 = (@13*@6) */
  w18  = (w13*w6);
  /* #98: @17 = (@17+@18) */
  w17 += w18;
  /* #99: @18 = (@5*@7) */
  w18  = (w5*w7);
  /* #100: @17 = (@17+@18) */
  w17 += w18;
  /* #101: @11 = (@11*@9) */
  w11 *= w9;
  /* #102: @12 = (@12*@8) */
  w12 *= w8;
  /* #103: @11 = (@11+@12) */
  w11 += w12;
  /* #104: @13 = (@13*@7) */
  w13 *= w7;
  /* #105: @11 = (@11-@13) */
  w11 -= w13;
  /* #106: @5 = (@5*@6) */
  w5 *= w6;
  /* #107: @11 = (@11+@5) */
  w11 += w5;
  /* #108: @39 = vertcat(@14, @16, @17, @11) */
  rr=w39;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w11;
  /* #109: @40 = (-@39) */
  for (i=0, rr=w40, cs=w39; i<4; ++i) *rr++ = (- *cs++ );
  /* #110: @40 = (@15?@40:0) */
  for (i=0, rr=w40, cs=w40; i<4; ++i) (*rr++)  = (w15?(*cs++):0);
  /* #111: @14 = (!@15) */
  w14 = (! w15 );
  /* #112: @39 = (@14?@39:0) */
  for (i=0, rr=w39, cs=w39; i<4; ++i) (*rr++)  = (w14?(*cs++):0);
  /* #113: @40 = (@40+@39) */
  for (i=0, rr=w40, cs=w39; i<4; ++i) (*rr++) += (*cs++);
  /* #114: @41 = @40[1:4] */
  for (rr=w41, ss=w40+1; ss!=w40+4; ss+=1) *rr++ = *ss;
  /* #115: @42 = (2.*@41) */
  for (i=0, rr=w42, cs=w41; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #116: @16 = ||@41||_F */
  w16 = sqrt(casadi_dot(3, w41, w41));
  /* #117: @17 = @40[0] */
  for (rr=(&w17), ss=w40+0; ss!=w40+1; ss+=1) *rr++ = *ss;
  /* #118: @11 = atan2(@16,@17) */
  w11  = atan2(w16,w17);
  /* #119: @43 = (@42*@11) */
  for (i=0, rr=w43, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w11);
  /* #120: @43 = (@43/@16) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) /= w16;
  /* #121: @44 = @43' */
  casadi_copy(w43, 3, w44);
  /* #122: @45 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w45);
  /* #123: @35 = mac(@44,@45,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w44+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #124: @4 = mac(@35,@43,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w43+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #125: @0 = (@0+@4) */
  w0 += w4;
  /* #126: @4 = 0 */
  w4 = 0.;
  /* #127: @40 = zeros(1x4) */
  casadi_clear(w40, 4);
  /* #128: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #129: @13 = input[1][1] */
  w13 = arg[1] ? arg[1][1] : 0;
  /* #130: @12 = input[1][2] */
  w12 = arg[1] ? arg[1][2] : 0;
  /* #131: @18 = input[1][3] */
  w18 = arg[1] ? arg[1][3] : 0;
  /* #132: @39 = vertcat(@5, @13, @12, @18) */
  rr=w39;
  *rr++ = w5;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w18;
  /* #133: @46 = @39' */
  casadi_copy(w39, 4, w46);
  /* #134: @47 = 
  [[0.002, 0, 0, 0], 
   [0, 200, 0, 0], 
   [0, 0, 200, 0], 
   [0, 0, 0, 200]] */
  casadi_copy(casadi_c2, 16, w47);
  /* #135: @40 = mac(@46,@47,@40) */
  for (i=0, rr=w40; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w46+j, tt=w47+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #136: @4 = mac(@40,@39,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w40+j, tt=w39+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #137: @0 = (@0+@4) */
  w0 += w4;
  /* #138: @4 = 0.05 */
  w4 = 5.0000000000000003e-02;
  /* #139: @44 = @33[3:6] */
  for (rr=w44, ss=w33+3; ss!=w33+6; ss+=1) *rr++ = *ss;
  /* #140: @5 = dot(@30, @44) */
  w5 = casadi_dot(3, w30, w44);
  /* #141: @4 = (@4*@5) */
  w4 *= w5;
  /* #142: @0 = (@0-@4) */
  w0 -= w4;
  /* #143: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #144: @40 = @40' */
  /* #145: @46 = zeros(1x4) */
  casadi_clear(w46, 4);
  /* #146: @39 = @39' */
  /* #147: @48 = @47' */
  for (i=0, rr=w48, cs=w47; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #148: @46 = mac(@39,@48,@46) */
  for (i=0, rr=w46; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w39+j, tt=w48+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #149: @46 = @46' */
  /* #150: @40 = (@40+@46) */
  for (i=0, rr=w40, cs=w46; i<4; ++i) (*rr++) += (*cs++);
  /* #151: {@0, @4, @5, @13} = vertsplit(@40) */
  w0 = w40[0];
  w4 = w40[1];
  w5 = w40[2];
  w13 = w40[3];
  /* #152: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #153: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #154: output[1][2] = @5 */
  if (res[1]) res[1][2] = w5;
  /* #155: output[1][3] = @13 */
  if (res[1]) res[1][3] = w13;
  /* #156: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #157: @13 = -0.05 */
  w13 = -5.0000000000000003e-02;
  /* #158: @44 = (@13*@30) */
  for (i=0, rr=w44, cs=w30; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #159: (@33[3:6] += @44) */
  for (rr=w33+3, ss=w44; rr!=w33+6; rr+=1) *rr += *ss++;
  /* #160: @40 = (@37/@10) */
  for (i=0, rr=w40, cr=w37; i<4; ++i) (*rr++)  = ((*cr++)/w10);
  /* #161: @46 = (-@40) */
  for (i=0, rr=w46, cs=w40; i<4; ++i) *rr++ = (- *cs++ );
  /* #162: @13 = 1 */
  w13 = 1.;
  /* #163: @13 = (@14?@13:0) */
  w13  = (w14?w13:0);
  /* #164: @39 = zeros(4x1) */
  casadi_clear(w39, 4);
  /* #165: @5 = sq(@16) */
  w5 = casadi_sq( w16 );
  /* #166: @4 = sq(@17) */
  w4 = casadi_sq( w17 );
  /* #167: @5 = (@5+@4) */
  w5 += w4;
  /* #168: @4 = (@16/@5) */
  w4  = (w16/w5);
  /* #169: @35 = @35' */
  /* #170: @44 = zeros(1x3) */
  casadi_clear(w44, 3);
  /* #171: @49 = @43' */
  casadi_copy(w43, 3, w49);
  /* #172: @50 = @45' */
  for (i=0, rr=w50, cs=w45; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #173: @44 = mac(@49,@50,@44) */
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w49+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #174: @44 = @44' */
  /* #175: @35 = (@35+@44) */
  for (i=0, rr=w35, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #176: @44 = (@35/@16) */
  for (i=0, rr=w44, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #177: @0 = dot(@42, @44) */
  w0 = casadi_dot(3, w42, w44);
  /* #178: @12 = (@4*@0) */
  w12  = (w4*w0);
  /* #179: @12 = (-@12) */
  w12 = (- w12 );
  /* #180: (@39[0] += @12) */
  for (rr=w39+0, ss=(&w12); rr!=w39+1; rr+=1) *rr += *ss++;
  /* #181: @49 = (@43/@16) */
  for (i=0, rr=w49, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #182: @51 = (-@49) */
  for (i=0, rr=w51, cs=w49; i<3; ++i) *rr++ = (- *cs++ );
  /* #183: @12 = dot(@51, @35) */
  w12 = casadi_dot(3, w51, w35);
  /* #184: @18 = (@17/@5) */
  w18  = (w17/w5);
  /* #185: @19 = (@18*@0) */
  w19  = (w18*w0);
  /* #186: @12 = (@12+@19) */
  w12 += w19;
  /* #187: @12 = (@12/@16) */
  w12 /= w16;
  /* #188: @52 = (@12*@41) */
  for (i=0, rr=w52, cs=w41; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #189: @53 = (@11*@44) */
  for (i=0, rr=w53, cs=w44; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #190: @53 = (2.*@53) */
  for (i=0, rr=w53, cs=w53; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #191: @52 = (@52+@53) */
  for (i=0, rr=w52, cs=w53; i<3; ++i) (*rr++) += (*cs++);
  /* #192: (@39[1:4] += @52) */
  for (rr=w39+1, ss=w52; rr!=w39+4; rr+=1) *rr += *ss++;
  /* #193: @54 = (@13*@39) */
  for (i=0, rr=w54, cs=w39; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #194: @19 = 1 */
  w19 = 1.;
  /* #195: @19 = (@15?@19:0) */
  w19  = (w15?w19:0);
  /* #196: @39 = (@19*@39) */
  for (i=0, rr=w39, cs=w39; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #197: @54 = (@54-@39) */
  for (i=0, rr=w54, cs=w39; i<4; ++i) (*rr++) -= (*cs++);
  /* #198: {@20, @21, @22, @23} = vertsplit(@54) */
  w20 = w54[0];
  w21 = w54[1];
  w22 = w54[2];
  w23 = w54[3];
  /* #199: @24 = (@9*@23) */
  w24  = (w9*w23);
  /* #200: @25 = (@8*@22) */
  w25  = (w8*w22);
  /* #201: @24 = (@24+@25) */
  w24 += w25;
  /* #202: @25 = (@7*@21) */
  w25  = (w7*w21);
  /* #203: @24 = (@24+@25) */
  w24 += w25;
  /* #204: @25 = (@6*@20) */
  w25  = (w6*w20);
  /* #205: @24 = (@24+@25) */
  w24 += w25;
  /* #206: @25 = (@8*@23) */
  w25  = (w8*w23);
  /* #207: @26 = (@9*@22) */
  w26  = (w9*w22);
  /* #208: @25 = (@25-@26) */
  w25 -= w26;
  /* #209: @26 = (@6*@21) */
  w26  = (w6*w21);
  /* #210: @25 = (@25+@26) */
  w25 += w26;
  /* #211: @26 = (@7*@20) */
  w26  = (w7*w20);
  /* #212: @25 = (@25-@26) */
  w25 -= w26;
  /* #213: @26 = (@6*@22) */
  w26  = (w6*w22);
  /* #214: @27 = (@7*@23) */
  w27  = (w7*w23);
  /* #215: @26 = (@26-@27) */
  w26 -= w27;
  /* #216: @27 = (@9*@21) */
  w27  = (w9*w21);
  /* #217: @26 = (@26+@27) */
  w26 += w27;
  /* #218: @27 = (@8*@20) */
  w27  = (w8*w20);
  /* #219: @26 = (@26-@27) */
  w26 -= w27;
  /* #220: @23 = (@6*@23) */
  w23  = (w6*w23);
  /* #221: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #222: @23 = (@23+@22) */
  w23 += w22;
  /* #223: @21 = (@8*@21) */
  w21  = (w8*w21);
  /* #224: @23 = (@23-@21) */
  w23 -= w21;
  /* #225: @20 = (@9*@20) */
  w20  = (w9*w20);
  /* #226: @23 = (@23-@20) */
  w23 -= w20;
  /* #227: @54 = vertcat(@24, @25, @26, @23) */
  rr=w54;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w23;
  /* #228: @24 = dot(@46, @54) */
  w24 = casadi_dot(4, w46, w54);
  /* #229: @24 = (@24/@10) */
  w24 /= w10;
  /* #230: @39 = (@24*@38) */
  for (i=0, rr=w39, cs=w38; i<4; ++i) (*rr++)  = (w24*(*cs++));
  /* #231: (@33[6:10] += @39) */
  for (rr=w33+6, ss=w39; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #232: @34 = @34' */
  /* #233: @52 = zeros(1x3) */
  casadi_clear(w52, 3);
  /* #234: @31 = @31' */
  /* #235: @55 = @36' */
  for (i=0, rr=w55, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #236: @52 = mac(@31,@55,@52) */
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #237: @52 = @52' */
  /* #238: @34 = (@34+@52) */
  for (i=0, rr=w34, cs=w52; i<3; ++i) (*rr++) += (*cs++);
  /* #239: @25 = dot(@30, @34) */
  w25 = casadi_dot(3, w30, w34);
  /* #240: @34 = (@25*@30) */
  for (i=0, rr=w34, cs=w30; i<3; ++i) (*rr++)  = (w25*(*cs++));
  /* #241: @52 = zeros(3x1) */
  casadi_clear(w52, 3);
  /* #242: @56 = @3' */
  for (i=0, rr=w56, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #243: @1 = @1' */
  /* #244: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #245: @2 = @2' */
  /* #246: @57 = @32' */
  for (i=0, rr=w57, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #247: @31 = mac(@2,@57,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w57+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #248: @31 = @31' */
  /* #249: @1 = (@1+@31) */
  for (i=0, rr=w1, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #250: @52 = mac(@56,@1,@52) */
  for (i=0, rr=w52; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w56+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #251: @34 = (@34+@52) */
  for (i=0, rr=w34, cs=w52; i<3; ++i) (*rr++) += (*cs++);
  /* #252: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #253: (@33[:3] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+3; rr+=1) *rr += *ss++;
  /* #254: {@25, @26, @23, @20, @21, @22, @27, @28, @58, @59, @60, @61, @62} = vertsplit(@33) */
  w25 = w33[0];
  w26 = w33[1];
  w23 = w33[2];
  w20 = w33[3];
  w21 = w33[4];
  w22 = w33[5];
  w27 = w33[6];
  w28 = w33[7];
  w58 = w33[8];
  w59 = w33[9];
  w60 = w33[10];
  w61 = w33[11];
  w62 = w33[12];
  /* #255: output[1][4] = @25 */
  if (res[1]) res[1][4] = w25;
  /* #256: output[1][5] = @26 */
  if (res[1]) res[1][5] = w26;
  /* #257: output[1][6] = @23 */
  if (res[1]) res[1][6] = w23;
  /* #258: output[1][7] = @20 */
  if (res[1]) res[1][7] = w20;
  /* #259: output[1][8] = @21 */
  if (res[1]) res[1][8] = w21;
  /* #260: output[1][9] = @22 */
  if (res[1]) res[1][9] = w22;
  /* #261: @39 = (@54/@10) */
  for (i=0, rr=w39, cr=w54; i<4; ++i) (*rr++)  = ((*cr++)/w10);
  /* #262: {@22, @21, @20, @23} = vertsplit(@39) */
  w22 = w39[0];
  w21 = w39[1];
  w20 = w39[2];
  w23 = w39[3];
  /* #263: @22 = (@22+@27) */
  w22 += w27;
  /* #264: output[1][10] = @22 */
  if (res[1]) res[1][10] = w22;
  /* #265: @28 = (@28-@21) */
  w28 -= w21;
  /* #266: output[1][11] = @28 */
  if (res[1]) res[1][11] = w28;
  /* #267: @58 = (@58-@20) */
  w58 -= w20;
  /* #268: output[1][12] = @58 */
  if (res[1]) res[1][12] = w58;
  /* #269: @59 = (@59-@23) */
  w59 -= w23;
  /* #270: output[1][13] = @59 */
  if (res[1]) res[1][13] = w59;
  /* #271: output[1][14] = @60 */
  if (res[1]) res[1][14] = w60;
  /* #272: output[1][15] = @61 */
  if (res[1]) res[1][15] = w61;
  /* #273: output[1][16] = @62 */
  if (res[1]) res[1][16] = w62;
  /* #274: @63 = zeros(17x17,41nz) */
  casadi_clear(w63, 41);
  /* #275: @64 = zeros(1x4) */
  casadi_clear(w64, 4);
  /* #276: @65 = ones(17x1,9nz) */
  casadi_fill(w65, 9, 1.);
  /* #277: {@62, NULL, NULL, NULL, @61, NULL, NULL, NULL, NULL, NULL, @60, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@65) */
  w62 = w65[0];
  w61 = w65[1];
  w60 = w65[5];
  /* #278: @66 = 00 */
  /* #279: @67 = 00 */
  /* #280: @68 = 00 */
  /* #281: @59 = vertcat(@62, @66, @67, @68) */
  rr=(&w59);
  *rr++ = w62;
  /* #282: @62 = @59' */
  casadi_copy((&w59), 1, (&w62));
  /* #283: @64 = mac(@62,@47,@64) */
  casadi_mtimes((&w62), casadi_s3, w47, casadi_s2, w64, casadi_s1, w, 0);
  /* #284: @64 = @64' */
  /* #285: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #286: @59 = @59' */
  /* #287: @69 = mac(@59,@48,@69) */
  casadi_mtimes((&w59), casadi_s3, w48, casadi_s2, w69, casadi_s1, w, 0);
  /* #288: @69 = @69' */
  /* #289: @64 = (@64+@69) */
  for (i=0, rr=w64, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #290: {@59, @62, @23, @58} = vertsplit(@64) */
  w59 = w64[0];
  w62 = w64[1];
  w23 = w64[2];
  w58 = w64[3];
  /* #291: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #292: @64 = zeros(4x1) */
  casadi_clear(w64, 4);
  /* #293: @20 = 1 */
  w20 = 1.;
  /* #294: @14 = (@14?@20:0) */
  w14  = (w14?w20:0);
  /* #295: @66 = 00 */
  /* #296: @67 = 00 */
  /* #297: @68 = 00 */
  /* #298: @20 = vertcat(@60, @66, @67, @68) */
  rr=(&w20);
  *rr++ = w60;
  /* #299: @20 = (@20/@10) */
  w20 /= w10;
  /* #300: @69 = dense(@20) */
  casadi_densify((&w20), casadi_s4, w69, 0);
  /* #301: @37 = (@37/@10) */
  for (i=0, rr=w37; i<4; ++i) (*rr++) /= w10;
  /* #302: @20 = project(@38) */
  casadi_sparsify(w38, (&w20), casadi_s4, 0);
  /* #303: @28 = @60[0] */
  for (rr=(&w28), ss=(&w60)+0; ss!=(&w60)+1; ss+=1) *rr++ = *ss;
  /* #304: @60 = dot(@20, @28) */
  w60 = casadi_dot(1, (&w20), (&w28));
  /* #305: @60 = (@60/@10) */
  w60 /= w10;
  /* #306: @70 = (@37*@60) */
  for (i=0, rr=w70, cr=w37; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #307: @69 = (@69-@70) */
  for (i=0, rr=w69, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #308: {@20, @21, @22, @27} = vertsplit(@69) */
  w20 = w69[0];
  w21 = w69[1];
  w22 = w69[2];
  w27 = w69[3];
  /* #309: @26 = (@6*@20) */
  w26  = (w6*w20);
  /* #310: @25 = (@7*@21) */
  w25  = (w7*w21);
  /* #311: @26 = (@26-@25) */
  w26 -= w25;
  /* #312: @25 = (@8*@22) */
  w25  = (w8*w22);
  /* #313: @26 = (@26-@25) */
  w26 -= w25;
  /* #314: @25 = (@9*@27) */
  w25  = (w9*w27);
  /* #315: @26 = (@26-@25) */
  w26 -= w25;
  /* #316: @25 = (@7*@20) */
  w25  = (w7*w20);
  /* #317: @71 = (@6*@21) */
  w71  = (w6*w21);
  /* #318: @25 = (@25+@71) */
  w25 += w71;
  /* #319: @71 = (@9*@22) */
  w71  = (w9*w22);
  /* #320: @25 = (@25+@71) */
  w25 += w71;
  /* #321: @71 = (@8*@27) */
  w71  = (w8*w27);
  /* #322: @25 = (@25-@71) */
  w25 -= w71;
  /* #323: @71 = (@8*@20) */
  w71  = (w8*w20);
  /* #324: @72 = (@9*@21) */
  w72  = (w9*w21);
  /* #325: @71 = (@71-@72) */
  w71 -= w72;
  /* #326: @72 = (@6*@22) */
  w72  = (w6*w22);
  /* #327: @71 = (@71+@72) */
  w71 += w72;
  /* #328: @72 = (@7*@27) */
  w72  = (w7*w27);
  /* #329: @71 = (@71+@72) */
  w71 += w72;
  /* #330: @20 = (@9*@20) */
  w20  = (w9*w20);
  /* #331: @21 = (@8*@21) */
  w21  = (w8*w21);
  /* #332: @20 = (@20+@21) */
  w20 += w21;
  /* #333: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #334: @20 = (@20-@22) */
  w20 -= w22;
  /* #335: @27 = (@6*@27) */
  w27  = (w6*w27);
  /* #336: @20 = (@20+@27) */
  w20 += w27;
  /* #337: @70 = vertcat(@26, @25, @71, @20) */
  rr=w70;
  *rr++ = w26;
  *rr++ = w25;
  *rr++ = w71;
  *rr++ = w20;
  /* #338: @73 = (@14*@70) */
  for (i=0, rr=w73, cs=w70; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #339: @26 = 1 */
  w26 = 1.;
  /* #340: @15 = (@15?@26:0) */
  w15  = (w15?w26:0);
  /* #341: @70 = (@15*@70) */
  for (i=0, rr=w70, cs=w70; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #342: @73 = (@73-@70) */
  for (i=0, rr=w73, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #343: @34 = @73[1:4] */
  for (rr=w34, ss=w73+1; ss!=w73+4; ss+=1) *rr++ = *ss;
  /* #344: @26 = dot(@41, @34) */
  w26 = casadi_dot(3, w41, w34);
  /* #345: @26 = (@26/@16) */
  w26 /= w16;
  /* #346: @25 = (@26/@5) */
  w25  = (w26/w5);
  /* #347: @71 = (@4/@5) */
  w71  = (w4/w5);
  /* #348: @20 = (2.*@16) */
  w20 = (2.* w16 );
  /* #349: @27 = (@20*@26) */
  w27  = (w20*w26);
  /* #350: @22 = (2.*@17) */
  w22 = (2.* w17 );
  /* #351: @21 = @73[0] */
  for (rr=(&w21), ss=w73+0; ss!=w73+1; ss+=1) *rr++ = *ss;
  /* #352: @72 = (@22*@21) */
  w72  = (w22*w21);
  /* #353: @27 = (@27+@72) */
  w27 += w72;
  /* #354: @72 = (@71*@27) */
  w72  = (w71*w27);
  /* #355: @25 = (@25-@72) */
  w25 -= w72;
  /* #356: @25 = (@0*@25) */
  w25  = (w0*w25);
  /* #357: @52 = zeros(1x3) */
  casadi_clear(w52, 3);
  /* #358: @1 = (2.*@34) */
  for (i=0, rr=w1, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #359: @31 = (@11*@1) */
  for (i=0, rr=w31, cs=w1; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #360: @72 = sq(@16) */
  w72 = casadi_sq( w16 );
  /* #361: @74 = sq(@17) */
  w74 = casadi_sq( w17 );
  /* #362: @72 = (@72+@74) */
  w72 += w74;
  /* #363: @17 = (@17/@72) */
  w17 /= w72;
  /* #364: @74 = (@17*@26) */
  w74  = (w17*w26);
  /* #365: @72 = (@16/@72) */
  w72  = (w16/w72);
  /* #366: @75 = (@72*@21) */
  w75  = (w72*w21);
  /* #367: @74 = (@74-@75) */
  w74 -= w75;
  /* #368: @2 = (@42*@74) */
  for (i=0, rr=w2, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #369: @31 = (@31+@2) */
  for (i=0, rr=w31, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #370: @31 = (@31/@16) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w16;
  /* #371: @43 = (@43/@16) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) /= w16;
  /* #372: @2 = (@43*@26) */
  for (i=0, rr=w2, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #373: @31 = (@31-@2) */
  for (i=0, rr=w31, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #374: @2 = @31' */
  casadi_copy(w31, 3, w2);
  /* #375: @52 = mac(@2,@45,@52) */
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #376: @52 = @52' */
  /* #377: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #378: @53 = @31' */
  casadi_copy(w31, 3, w53);
  /* #379: @2 = mac(@53,@50,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w53+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #380: @2 = @2' */
  /* #381: @52 = (@52+@2) */
  for (i=0, rr=w52, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #382: @2 = (@52/@16) */
  for (i=0, rr=w2, cr=w52; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #383: @53 = (@44/@16) */
  for (i=0, rr=w53, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #384: @76 = (@53*@26) */
  for (i=0, rr=w76, cr=w53; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #385: @2 = (@2-@76) */
  for (i=0, rr=w2, cs=w76; i<3; ++i) (*rr++) -= (*cs++);
  /* #386: @75 = dot(@42, @2) */
  w75 = casadi_dot(3, w42, w2);
  /* #387: @77 = dot(@1, @44) */
  w77 = casadi_dot(3, w1, w44);
  /* #388: @75 = (@75+@77) */
  w75 += w77;
  /* #389: @77 = (@4*@75) */
  w77  = (w4*w75);
  /* #390: @25 = (@25+@77) */
  w25 += w77;
  /* #391: @25 = (-@25) */
  w25 = (- w25 );
  /* #392: (@64[0] += @25) */
  for (rr=w64+0, ss=(&w25); rr!=w64+1; rr+=1) *rr += *ss++;
  /* #393: @25 = dot(@51, @52) */
  w25 = casadi_dot(3, w51, w52);
  /* #394: @31 = (@31/@16) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w16;
  /* #395: @49 = (@49/@16) */
  for (i=0, rr=w49; i<3; ++i) (*rr++) /= w16;
  /* #396: @52 = (@49*@26) */
  for (i=0, rr=w52, cr=w49; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #397: @31 = (@31-@52) */
  for (i=0, rr=w31, cs=w52; i<3; ++i) (*rr++) -= (*cs++);
  /* #398: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #399: @77 = dot(@31, @35) */
  w77 = casadi_dot(3, w31, w35);
  /* #400: @25 = (@25+@77) */
  w25 += w77;
  /* #401: @21 = (@21/@5) */
  w21 /= w5;
  /* #402: @77 = (@18/@5) */
  w77  = (w18/w5);
  /* #403: @27 = (@77*@27) */
  w27  = (w77*w27);
  /* #404: @21 = (@21-@27) */
  w21 -= w27;
  /* #405: @21 = (@0*@21) */
  w21  = (w0*w21);
  /* #406: @75 = (@18*@75) */
  w75  = (w18*w75);
  /* #407: @21 = (@21+@75) */
  w21 += w75;
  /* #408: @25 = (@25+@21) */
  w25 += w21;
  /* #409: @25 = (@25/@16) */
  w25 /= w16;
  /* #410: @21 = (@12/@16) */
  w21  = (w12/w16);
  /* #411: @26 = (@21*@26) */
  w26  = (w21*w26);
  /* #412: @25 = (@25-@26) */
  w25 -= w26;
  /* #413: @31 = (@41*@25) */
  for (i=0, rr=w31, cr=w41; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #414: @34 = (@12*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #415: @31 = (@31+@34) */
  for (i=0, rr=w31, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #416: @34 = (@44*@74) */
  for (i=0, rr=w34, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #417: @2 = (@11*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #418: @34 = (@34+@2) */
  for (i=0, rr=w34, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #419: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #420: @31 = (@31+@34) */
  for (i=0, rr=w31, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #421: (@64[1:4] += @31) */
  for (rr=w64+1, ss=w31; rr!=w64+4; rr+=1) *rr += *ss++;
  /* #422: @73 = (@13*@64) */
  for (i=0, rr=w73, cs=w64; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #423: @64 = (@19*@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #424: @73 = (@73-@64) */
  for (i=0, rr=w73, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #425: {@74, @25, @26, @75} = vertsplit(@73) */
  w74 = w73[0];
  w25 = w73[1];
  w26 = w73[2];
  w75 = w73[3];
  /* #426: @27 = (@9*@75) */
  w27  = (w9*w75);
  /* #427: @78 = (@8*@26) */
  w78  = (w8*w26);
  /* #428: @27 = (@27+@78) */
  w27 += w78;
  /* #429: @78 = (@7*@25) */
  w78  = (w7*w25);
  /* #430: @27 = (@27+@78) */
  w27 += w78;
  /* #431: @78 = (@6*@74) */
  w78  = (w6*w74);
  /* #432: @27 = (@27+@78) */
  w27 += w78;
  /* #433: @78 = (@8*@75) */
  w78  = (w8*w75);
  /* #434: @79 = (@9*@26) */
  w79  = (w9*w26);
  /* #435: @78 = (@78-@79) */
  w78 -= w79;
  /* #436: @79 = (@6*@25) */
  w79  = (w6*w25);
  /* #437: @78 = (@78+@79) */
  w78 += w79;
  /* #438: @79 = (@7*@74) */
  w79  = (w7*w74);
  /* #439: @78 = (@78-@79) */
  w78 -= w79;
  /* #440: @79 = (@6*@26) */
  w79  = (w6*w26);
  /* #441: @80 = (@7*@75) */
  w80  = (w7*w75);
  /* #442: @79 = (@79-@80) */
  w79 -= w80;
  /* #443: @80 = (@9*@25) */
  w80  = (w9*w25);
  /* #444: @79 = (@79+@80) */
  w79 += w80;
  /* #445: @80 = (@8*@74) */
  w80  = (w8*w74);
  /* #446: @79 = (@79-@80) */
  w79 -= w80;
  /* #447: @75 = (@6*@75) */
  w75  = (w6*w75);
  /* #448: @26 = (@7*@26) */
  w26  = (w7*w26);
  /* #449: @75 = (@75+@26) */
  w75 += w26;
  /* #450: @25 = (@8*@25) */
  w25  = (w8*w25);
  /* #451: @75 = (@75-@25) */
  w75 -= w25;
  /* #452: @74 = (@9*@74) */
  w74  = (w9*w74);
  /* #453: @75 = (@75-@74) */
  w75 -= w74;
  /* #454: @73 = vertcat(@27, @78, @79, @75) */
  rr=w73;
  *rr++ = w27;
  *rr++ = w78;
  *rr++ = w79;
  *rr++ = w75;
  /* #455: @27 = dot(@46, @73) */
  w27 = casadi_dot(4, w46, w73);
  /* #456: @69 = (@69/@10) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w10;
  /* #457: @40 = (@40/@10) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) /= w10;
  /* #458: @64 = (@40*@60) */
  for (i=0, rr=w64, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #459: @69 = (@69-@64) */
  for (i=0, rr=w69, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #460: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #461: @78 = dot(@69, @54) */
  w78 = casadi_dot(4, w69, w54);
  /* #462: @27 = (@27+@78) */
  w27 += w78;
  /* #463: @27 = (@27/@10) */
  w27 /= w10;
  /* #464: @78 = (@24/@10) */
  w78  = (w24/w10);
  /* #465: @79 = (@78*@60) */
  w79  = (w78*w60);
  /* #466: @27 = (@27-@79) */
  w27 -= w79;
  /* #467: @69 = (@38*@27) */
  for (i=0, rr=w69, cr=w38; i<4; ++i) (*rr++)  = ((*cr++)*w27);
  /* #468: @28 = (@24*@28) */
  w28  = (w24*w28);
  /* #469: @64 = dense(@28) */
  casadi_densify((&w28), casadi_s4, w64, 0);
  /* #470: @69 = (@69+@64) */
  for (i=0, rr=w69, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #471: (@33[6:10] += @69) */
  for (rr=w33+6, ss=w69; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #472: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #473: @28 = project(@30) */
  casadi_sparsify(w30, (&w28), casadi_s5, 0);
  /* #474: @27 = @61[0] */
  for (rr=(&w27), ss=(&w61)+0; ss!=(&w61)+1; ss+=1) *rr++ = *ss;
  /* #475: @27 = (-@27) */
  w27 = (- w27 );
  /* #476: @61 = dot(@28, @27) */
  w61 = casadi_dot(1, (&w28), (&w27));
  /* #477: @34 = (@30*@61) */
  for (i=0, rr=w34, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w61);
  /* #478: @2 = @34' */
  casadi_copy(w34, 3, w2);
  /* #479: @31 = mac(@2,@36,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #480: @31 = @31' */
  /* #481: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #482: @34 = @34' */
  /* #483: @2 = mac(@34,@55,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #484: @2 = @2' */
  /* #485: @31 = (@31+@2) */
  for (i=0, rr=w31, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #486: @61 = dot(@30, @31) */
  w61 = casadi_dot(3, w30, w31);
  /* #487: @31 = (@30*@61) */
  for (i=0, rr=w31, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w61);
  /* #488: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #489: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #490: @52 = zeros(3x1) */
  casadi_clear(w52, 3);
  /* #491: @52 = mac(@3,@27,@52) */
  casadi_mtimes(w3, casadi_s7, (&w27), casadi_s5, w52, casadi_s6, w, 0);
  /* #492: @1 = @52' */
  casadi_copy(w52, 3, w1);
  /* #493: @34 = mac(@1,@32,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #494: @34 = @34' */
  /* #495: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #496: @52 = @52' */
  /* #497: @1 = mac(@52,@57,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w52+j, tt=w57+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #498: @1 = @1' */
  /* #499: @34 = (@34+@1) */
  for (i=0, rr=w34, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #500: @2 = mac(@56,@34,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w56+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #501: @31 = (@31+@2) */
  for (i=0, rr=w31, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #502: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #503: (@33[:3] += @31) */
  for (rr=w33+0, ss=w31; rr!=w33+3; rr+=1) *rr += *ss++;
  /* #504: {@27, @61, @28, @79, @75, @74, @25, @26, @80, @81, @82, @83, @84} = vertsplit(@33) */
  w27 = w33[0];
  w61 = w33[1];
  w28 = w33[2];
  w79 = w33[3];
  w75 = w33[4];
  w74 = w33[5];
  w25 = w33[6];
  w26 = w33[7];
  w80 = w33[8];
  w81 = w33[9];
  w82 = w33[10];
  w83 = w33[11];
  w84 = w33[12];
  /* #505: @73 = (@73/@10) */
  for (i=0, rr=w73; i<4; ++i) (*rr++) /= w10;
  /* #506: @39 = (@39/@10) */
  for (i=0, rr=w39; i<4; ++i) (*rr++) /= w10;
  /* #507: @69 = (@39*@60) */
  for (i=0, rr=w69, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #508: @73 = (@73-@69) */
  for (i=0, rr=w73, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #509: {@60, @85, @86, @87} = vertsplit(@73) */
  w60 = w73[0];
  w85 = w73[1];
  w86 = w73[2];
  w87 = w73[3];
  /* #510: @60 = (@60+@25) */
  w60 += w25;
  /* #511: @26 = (@26-@85) */
  w26 -= w85;
  /* #512: @80 = (@80-@86) */
  w80 -= w86;
  /* #513: @81 = (@81-@87) */
  w81 -= w87;
  /* #514: @88 = vertcat(@59, @62, @23, @58, @27, @61, @28, @79, @75, @74, @60, @26, @80, @81, @82, @83, @84) */
  rr=w88;
  *rr++ = w59;
  *rr++ = w62;
  *rr++ = w23;
  *rr++ = w58;
  *rr++ = w27;
  *rr++ = w61;
  *rr++ = w28;
  *rr++ = w79;
  *rr++ = w75;
  *rr++ = w74;
  *rr++ = w60;
  *rr++ = w26;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w84;
  /* #515: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #516: (@63[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @89) */
  for (cii=casadi_s9, rr=w63, ss=w89; cii!=casadi_s9+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #517: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #518: (@63[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @89) */
  for (cii=casadi_s10, rr=w63, ss=w89; cii!=casadi_s10+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #519: @73 = zeros(1x4) */
  casadi_clear(w73, 4);
  /* #520: @66 = 00 */
  /* #521: @31 = ones(17x1,3nz) */
  casadi_fill(w31, 3, 1.);
  /* #522: {NULL, @59, NULL, NULL, NULL, @62, NULL, NULL, NULL, NULL, NULL, @23, NULL, NULL, NULL, NULL, NULL} = vertsplit(@31) */
  w59 = w31[0];
  w62 = w31[1];
  w23 = w31[2];
  /* #523: @67 = 00 */
  /* #524: @68 = 00 */
  /* #525: @58 = vertcat(@66, @59, @67, @68) */
  rr=(&w58);
  *rr++ = w59;
  /* #526: @59 = @58' */
  casadi_copy((&w58), 1, (&w59));
  /* #527: @73 = mac(@59,@47,@73) */
  casadi_mtimes((&w59), casadi_s11, w47, casadi_s2, w73, casadi_s1, w, 0);
  /* #528: @73 = @73' */
  /* #529: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #530: @58 = @58' */
  /* #531: @69 = mac(@58,@48,@69) */
  casadi_mtimes((&w58), casadi_s11, w48, casadi_s2, w69, casadi_s1, w, 0);
  /* #532: @69 = @69' */
  /* #533: @73 = (@73+@69) */
  for (i=0, rr=w73, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #534: {@58, @59, @27, @61} = vertsplit(@73) */
  w58 = w73[0];
  w59 = w73[1];
  w27 = w73[2];
  w61 = w73[3];
  /* #535: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #536: @73 = zeros(4x1) */
  casadi_clear(w73, 4);
  /* #537: @66 = 00 */
  /* #538: @28 = (-@23) */
  w28 = (- w23 );
  /* #539: @67 = 00 */
  /* #540: @68 = 00 */
  /* #541: @79 = vertcat(@66, @28, @67, @68) */
  rr=(&w79);
  *rr++ = w28;
  /* #542: @79 = (@79/@10) */
  w79 /= w10;
  /* #543: @69 = dense(@79) */
  casadi_densify((&w79), casadi_s12, w69, 0);
  /* #544: @79 = project(@38) */
  casadi_sparsify(w38, (&w79), casadi_s12, 0);
  /* #545: @28 = @23[0] */
  for (rr=(&w28), ss=(&w23)+0; ss!=(&w23)+1; ss+=1) *rr++ = *ss;
  /* #546: @23 = dot(@79, @28) */
  w23 = casadi_dot(1, (&w79), (&w28));
  /* #547: @23 = (@23/@10) */
  w23 /= w10;
  /* #548: @64 = (@37*@23) */
  for (i=0, rr=w64, cr=w37; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #549: @69 = (@69-@64) */
  for (i=0, rr=w69, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #550: {@79, @75, @74, @60} = vertsplit(@69) */
  w79 = w69[0];
  w75 = w69[1];
  w74 = w69[2];
  w60 = w69[3];
  /* #551: @26 = (@6*@79) */
  w26  = (w6*w79);
  /* #552: @80 = (@7*@75) */
  w80  = (w7*w75);
  /* #553: @26 = (@26-@80) */
  w26 -= w80;
  /* #554: @80 = (@8*@74) */
  w80  = (w8*w74);
  /* #555: @26 = (@26-@80) */
  w26 -= w80;
  /* #556: @80 = (@9*@60) */
  w80  = (w9*w60);
  /* #557: @26 = (@26-@80) */
  w26 -= w80;
  /* #558: @80 = (@7*@79) */
  w80  = (w7*w79);
  /* #559: @81 = (@6*@75) */
  w81  = (w6*w75);
  /* #560: @80 = (@80+@81) */
  w80 += w81;
  /* #561: @81 = (@9*@74) */
  w81  = (w9*w74);
  /* #562: @80 = (@80+@81) */
  w80 += w81;
  /* #563: @81 = (@8*@60) */
  w81  = (w8*w60);
  /* #564: @80 = (@80-@81) */
  w80 -= w81;
  /* #565: @81 = (@8*@79) */
  w81  = (w8*w79);
  /* #566: @82 = (@9*@75) */
  w82  = (w9*w75);
  /* #567: @81 = (@81-@82) */
  w81 -= w82;
  /* #568: @82 = (@6*@74) */
  w82  = (w6*w74);
  /* #569: @81 = (@81+@82) */
  w81 += w82;
  /* #570: @82 = (@7*@60) */
  w82  = (w7*w60);
  /* #571: @81 = (@81+@82) */
  w81 += w82;
  /* #572: @79 = (@9*@79) */
  w79  = (w9*w79);
  /* #573: @75 = (@8*@75) */
  w75  = (w8*w75);
  /* #574: @79 = (@79+@75) */
  w79 += w75;
  /* #575: @74 = (@7*@74) */
  w74  = (w7*w74);
  /* #576: @79 = (@79-@74) */
  w79 -= w74;
  /* #577: @60 = (@6*@60) */
  w60  = (w6*w60);
  /* #578: @79 = (@79+@60) */
  w79 += w60;
  /* #579: @64 = vertcat(@26, @80, @81, @79) */
  rr=w64;
  *rr++ = w26;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w79;
  /* #580: @70 = (@14*@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #581: @64 = (@15*@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #582: @70 = (@70-@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #583: @31 = @70[1:4] */
  for (rr=w31, ss=w70+1; ss!=w70+4; ss+=1) *rr++ = *ss;
  /* #584: @26 = dot(@41, @31) */
  w26 = casadi_dot(3, w41, w31);
  /* #585: @26 = (@26/@16) */
  w26 /= w16;
  /* #586: @80 = (@26/@5) */
  w80  = (w26/w5);
  /* #587: @81 = (@20*@26) */
  w81  = (w20*w26);
  /* #588: @79 = @70[0] */
  for (rr=(&w79), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  /* #589: @60 = (@22*@79) */
  w60  = (w22*w79);
  /* #590: @81 = (@81+@60) */
  w81 += w60;
  /* #591: @60 = (@71*@81) */
  w60  = (w71*w81);
  /* #592: @80 = (@80-@60) */
  w80 -= w60;
  /* #593: @80 = (@0*@80) */
  w80  = (w0*w80);
  /* #594: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #595: @34 = (2.*@31) */
  for (i=0, rr=w34, cs=w31; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #596: @1 = (@11*@34) */
  for (i=0, rr=w1, cs=w34; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #597: @60 = (@17*@26) */
  w60  = (w17*w26);
  /* #598: @74 = (@72*@79) */
  w74  = (w72*w79);
  /* #599: @60 = (@60-@74) */
  w60 -= w74;
  /* #600: @52 = (@42*@60) */
  for (i=0, rr=w52, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #601: @1 = (@1+@52) */
  for (i=0, rr=w1, cs=w52; i<3; ++i) (*rr++) += (*cs++);
  /* #602: @1 = (@1/@16) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w16;
  /* #603: @52 = (@43*@26) */
  for (i=0, rr=w52, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #604: @1 = (@1-@52) */
  for (i=0, rr=w1, cs=w52; i<3; ++i) (*rr++) -= (*cs++);
  /* #605: @52 = @1' */
  casadi_copy(w1, 3, w52);
  /* #606: @2 = mac(@52,@45,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w52+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #607: @2 = @2' */
  /* #608: @52 = zeros(1x3) */
  casadi_clear(w52, 3);
  /* #609: @76 = @1' */
  casadi_copy(w1, 3, w76);
  /* #610: @52 = mac(@76,@50,@52) */
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w76+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #611: @52 = @52' */
  /* #612: @2 = (@2+@52) */
  for (i=0, rr=w2, cs=w52; i<3; ++i) (*rr++) += (*cs++);
  /* #613: @52 = (@2/@16) */
  for (i=0, rr=w52, cr=w2; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #614: @76 = (@53*@26) */
  for (i=0, rr=w76, cr=w53; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #615: @52 = (@52-@76) */
  for (i=0, rr=w52, cs=w76; i<3; ++i) (*rr++) -= (*cs++);
  /* #616: @74 = dot(@42, @52) */
  w74 = casadi_dot(3, w42, w52);
  /* #617: @75 = dot(@34, @44) */
  w75 = casadi_dot(3, w34, w44);
  /* #618: @74 = (@74+@75) */
  w74 += w75;
  /* #619: @75 = (@4*@74) */
  w75  = (w4*w74);
  /* #620: @80 = (@80+@75) */
  w80 += w75;
  /* #621: @80 = (-@80) */
  w80 = (- w80 );
  /* #622: (@73[0] += @80) */
  for (rr=w73+0, ss=(&w80); rr!=w73+1; rr+=1) *rr += *ss++;
  /* #623: @80 = dot(@51, @2) */
  w80 = casadi_dot(3, w51, w2);
  /* #624: @1 = (@1/@16) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w16;
  /* #625: @2 = (@49*@26) */
  for (i=0, rr=w2, cr=w49; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #626: @1 = (@1-@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #627: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #628: @75 = dot(@1, @35) */
  w75 = casadi_dot(3, w1, w35);
  /* #629: @80 = (@80+@75) */
  w80 += w75;
  /* #630: @79 = (@79/@5) */
  w79 /= w5;
  /* #631: @81 = (@77*@81) */
  w81  = (w77*w81);
  /* #632: @79 = (@79-@81) */
  w79 -= w81;
  /* #633: @79 = (@0*@79) */
  w79  = (w0*w79);
  /* #634: @74 = (@18*@74) */
  w74  = (w18*w74);
  /* #635: @79 = (@79+@74) */
  w79 += w74;
  /* #636: @80 = (@80+@79) */
  w80 += w79;
  /* #637: @80 = (@80/@16) */
  w80 /= w16;
  /* #638: @26 = (@21*@26) */
  w26  = (w21*w26);
  /* #639: @80 = (@80-@26) */
  w80 -= w26;
  /* #640: @1 = (@41*@80) */
  for (i=0, rr=w1, cr=w41; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #641: @31 = (@12*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #642: @1 = (@1+@31) */
  for (i=0, rr=w1, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #643: @31 = (@44*@60) */
  for (i=0, rr=w31, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #644: @52 = (@11*@52) */
  for (i=0, rr=w52, cs=w52; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #645: @31 = (@31+@52) */
  for (i=0, rr=w31, cs=w52; i<3; ++i) (*rr++) += (*cs++);
  /* #646: @31 = (2.*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #647: @1 = (@1+@31) */
  for (i=0, rr=w1, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #648: (@73[1:4] += @1) */
  for (rr=w73+1, ss=w1; rr!=w73+4; rr+=1) *rr += *ss++;
  /* #649: @70 = (@13*@73) */
  for (i=0, rr=w70, cs=w73; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #650: @73 = (@19*@73) */
  for (i=0, rr=w73, cs=w73; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #651: @70 = (@70-@73) */
  for (i=0, rr=w70, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #652: {@60, @80, @26, @79} = vertsplit(@70) */
  w60 = w70[0];
  w80 = w70[1];
  w26 = w70[2];
  w79 = w70[3];
  /* #653: @74 = (@9*@79) */
  w74  = (w9*w79);
  /* #654: @81 = (@8*@26) */
  w81  = (w8*w26);
  /* #655: @74 = (@74+@81) */
  w74 += w81;
  /* #656: @81 = (@7*@80) */
  w81  = (w7*w80);
  /* #657: @74 = (@74+@81) */
  w74 += w81;
  /* #658: @81 = (@6*@60) */
  w81  = (w6*w60);
  /* #659: @74 = (@74+@81) */
  w74 += w81;
  /* #660: @81 = (@8*@79) */
  w81  = (w8*w79);
  /* #661: @75 = (@9*@26) */
  w75  = (w9*w26);
  /* #662: @81 = (@81-@75) */
  w81 -= w75;
  /* #663: @75 = (@6*@80) */
  w75  = (w6*w80);
  /* #664: @81 = (@81+@75) */
  w81 += w75;
  /* #665: @75 = (@7*@60) */
  w75  = (w7*w60);
  /* #666: @81 = (@81-@75) */
  w81 -= w75;
  /* #667: @75 = (@6*@26) */
  w75  = (w6*w26);
  /* #668: @82 = (@7*@79) */
  w82  = (w7*w79);
  /* #669: @75 = (@75-@82) */
  w75 -= w82;
  /* #670: @82 = (@9*@80) */
  w82  = (w9*w80);
  /* #671: @75 = (@75+@82) */
  w75 += w82;
  /* #672: @82 = (@8*@60) */
  w82  = (w8*w60);
  /* #673: @75 = (@75-@82) */
  w75 -= w82;
  /* #674: @79 = (@6*@79) */
  w79  = (w6*w79);
  /* #675: @26 = (@7*@26) */
  w26  = (w7*w26);
  /* #676: @79 = (@79+@26) */
  w79 += w26;
  /* #677: @80 = (@8*@80) */
  w80  = (w8*w80);
  /* #678: @79 = (@79-@80) */
  w79 -= w80;
  /* #679: @60 = (@9*@60) */
  w60  = (w9*w60);
  /* #680: @79 = (@79-@60) */
  w79 -= w60;
  /* #681: @70 = vertcat(@74, @81, @75, @79) */
  rr=w70;
  *rr++ = w74;
  *rr++ = w81;
  *rr++ = w75;
  *rr++ = w79;
  /* #682: @74 = dot(@46, @70) */
  w74 = casadi_dot(4, w46, w70);
  /* #683: @69 = (@69/@10) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w10;
  /* #684: @73 = (@40*@23) */
  for (i=0, rr=w73, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #685: @69 = (@69-@73) */
  for (i=0, rr=w69, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #686: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #687: @81 = dot(@69, @54) */
  w81 = casadi_dot(4, w69, w54);
  /* #688: @74 = (@74+@81) */
  w74 += w81;
  /* #689: @74 = (@74/@10) */
  w74 /= w10;
  /* #690: @81 = (@78*@23) */
  w81  = (w78*w23);
  /* #691: @74 = (@74-@81) */
  w74 -= w81;
  /* #692: @69 = (@38*@74) */
  for (i=0, rr=w69, cr=w38; i<4; ++i) (*rr++)  = ((*cr++)*w74);
  /* #693: @28 = (@24*@28) */
  w28  = (w24*w28);
  /* #694: @73 = dense(@28) */
  casadi_densify((&w28), casadi_s12, w73, 0);
  /* #695: @69 = (@69+@73) */
  for (i=0, rr=w69, cs=w73; i<4; ++i) (*rr++) += (*cs++);
  /* #696: (@33[6:10] += @69) */
  for (rr=w33+6, ss=w69; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #697: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #698: @28 = project(@30) */
  casadi_sparsify(w30, (&w28), casadi_s13, 0);
  /* #699: @74 = @62[0] */
  for (rr=(&w74), ss=(&w62)+0; ss!=(&w62)+1; ss+=1) *rr++ = *ss;
  /* #700: @74 = (-@74) */
  w74 = (- w74 );
  /* #701: @62 = dot(@28, @74) */
  w62 = casadi_dot(1, (&w28), (&w74));
  /* #702: @31 = (@30*@62) */
  for (i=0, rr=w31, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #703: @52 = @31' */
  casadi_copy(w31, 3, w52);
  /* #704: @1 = mac(@52,@36,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w52+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #705: @1 = @1' */
  /* #706: @52 = zeros(1x3) */
  casadi_clear(w52, 3);
  /* #707: @31 = @31' */
  /* #708: @52 = mac(@31,@55,@52) */
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #709: @52 = @52' */
  /* #710: @1 = (@1+@52) */
  for (i=0, rr=w1, cs=w52; i<3; ++i) (*rr++) += (*cs++);
  /* #711: @62 = dot(@30, @1) */
  w62 = casadi_dot(3, w30, w1);
  /* #712: @1 = (@30*@62) */
  for (i=0, rr=w1, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #713: @52 = zeros(3x1) */
  casadi_clear(w52, 3);
  /* #714: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #715: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #716: @2 = mac(@3,@74,@2) */
  casadi_mtimes(w3, casadi_s7, (&w74), casadi_s13, w2, casadi_s6, w, 0);
  /* #717: @34 = @2' */
  casadi_copy(w2, 3, w34);
  /* #718: @31 = mac(@34,@32,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #719: @31 = @31' */
  /* #720: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #721: @2 = @2' */
  /* #722: @34 = mac(@2,@57,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w57+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #723: @34 = @34' */
  /* #724: @31 = (@31+@34) */
  for (i=0, rr=w31, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #725: @52 = mac(@56,@31,@52) */
  for (i=0, rr=w52; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w56+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #726: @1 = (@1+@52) */
  for (i=0, rr=w1, cs=w52; i<3; ++i) (*rr++) += (*cs++);
  /* #727: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #728: (@33[:3] += @1) */
  for (rr=w33+0, ss=w1; rr!=w33+3; rr+=1) *rr += *ss++;
  /* #729: {@74, @62, @28, @81, @75, @79, @60, @80, @26, @82, @83, @84, @87} = vertsplit(@33) */
  w74 = w33[0];
  w62 = w33[1];
  w28 = w33[2];
  w81 = w33[3];
  w75 = w33[4];
  w79 = w33[5];
  w60 = w33[6];
  w80 = w33[7];
  w26 = w33[8];
  w82 = w33[9];
  w83 = w33[10];
  w84 = w33[11];
  w87 = w33[12];
  /* #730: @70 = (@70/@10) */
  for (i=0, rr=w70; i<4; ++i) (*rr++) /= w10;
  /* #731: @69 = (@39*@23) */
  for (i=0, rr=w69, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #732: @70 = (@70-@69) */
  for (i=0, rr=w70, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #733: {@23, @86, @85, @25} = vertsplit(@70) */
  w23 = w70[0];
  w86 = w70[1];
  w85 = w70[2];
  w25 = w70[3];
  /* #734: @23 = (@23+@60) */
  w23 += w60;
  /* #735: @80 = (@80-@86) */
  w80 -= w86;
  /* #736: @26 = (@26-@85) */
  w26 -= w85;
  /* #737: @82 = (@82-@25) */
  w82 -= w25;
  /* #738: @88 = vertcat(@58, @59, @27, @61, @74, @62, @28, @81, @75, @79, @23, @80, @26, @82, @83, @84, @87) */
  rr=w88;
  *rr++ = w58;
  *rr++ = w59;
  *rr++ = w27;
  *rr++ = w61;
  *rr++ = w74;
  *rr++ = w62;
  *rr++ = w28;
  *rr++ = w81;
  *rr++ = w75;
  *rr++ = w79;
  *rr++ = w23;
  *rr++ = w80;
  *rr++ = w26;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w84;
  *rr++ = w87;
  /* #739: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #740: (@63[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @89) */
  for (cii=casadi_s14, rr=w63, ss=w89; cii!=casadi_s14+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #741: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #742: (@63[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @89) */
  for (cii=casadi_s15, rr=w63, ss=w89; cii!=casadi_s15+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #743: @70 = zeros(1x4) */
  casadi_clear(w70, 4);
  /* #744: @66 = 00 */
  /* #745: @67 = 00 */
  /* #746: @1 = ones(17x1,3nz) */
  casadi_fill(w1, 3, 1.);
  /* #747: {NULL, NULL, @58, NULL, NULL, NULL, @59, NULL, NULL, NULL, NULL, NULL, @27, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w58 = w1[0];
  w59 = w1[1];
  w27 = w1[2];
  /* #748: @68 = 00 */
  /* #749: @61 = vertcat(@66, @67, @58, @68) */
  rr=(&w61);
  *rr++ = w58;
  /* #750: @58 = @61' */
  casadi_copy((&w61), 1, (&w58));
  /* #751: @70 = mac(@58,@47,@70) */
  casadi_mtimes((&w58), casadi_s16, w47, casadi_s2, w70, casadi_s1, w, 0);
  /* #752: @70 = @70' */
  /* #753: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #754: @61 = @61' */
  /* #755: @69 = mac(@61,@48,@69) */
  casadi_mtimes((&w61), casadi_s16, w48, casadi_s2, w69, casadi_s1, w, 0);
  /* #756: @69 = @69' */
  /* #757: @70 = (@70+@69) */
  for (i=0, rr=w70, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #758: {@61, @58, @74, @62} = vertsplit(@70) */
  w61 = w70[0];
  w58 = w70[1];
  w74 = w70[2];
  w62 = w70[3];
  /* #759: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #760: @70 = zeros(4x1) */
  casadi_clear(w70, 4);
  /* #761: @66 = 00 */
  /* #762: @67 = 00 */
  /* #763: @28 = (-@27) */
  w28 = (- w27 );
  /* #764: @68 = 00 */
  /* #765: @81 = vertcat(@66, @67, @28, @68) */
  rr=(&w81);
  *rr++ = w28;
  /* #766: @81 = (@81/@10) */
  w81 /= w10;
  /* #767: @69 = dense(@81) */
  casadi_densify((&w81), casadi_s17, w69, 0);
  /* #768: @81 = project(@38) */
  casadi_sparsify(w38, (&w81), casadi_s17, 0);
  /* #769: @28 = @27[0] */
  for (rr=(&w28), ss=(&w27)+0; ss!=(&w27)+1; ss+=1) *rr++ = *ss;
  /* #770: @27 = dot(@81, @28) */
  w27 = casadi_dot(1, (&w81), (&w28));
  /* #771: @27 = (@27/@10) */
  w27 /= w10;
  /* #772: @73 = (@37*@27) */
  for (i=0, rr=w73, cr=w37; i<4; ++i) (*rr++)  = ((*cr++)*w27);
  /* #773: @69 = (@69-@73) */
  for (i=0, rr=w69, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #774: {@81, @75, @79, @23} = vertsplit(@69) */
  w81 = w69[0];
  w75 = w69[1];
  w79 = w69[2];
  w23 = w69[3];
  /* #775: @80 = (@6*@81) */
  w80  = (w6*w81);
  /* #776: @26 = (@7*@75) */
  w26  = (w7*w75);
  /* #777: @80 = (@80-@26) */
  w80 -= w26;
  /* #778: @26 = (@8*@79) */
  w26  = (w8*w79);
  /* #779: @80 = (@80-@26) */
  w80 -= w26;
  /* #780: @26 = (@9*@23) */
  w26  = (w9*w23);
  /* #781: @80 = (@80-@26) */
  w80 -= w26;
  /* #782: @26 = (@7*@81) */
  w26  = (w7*w81);
  /* #783: @82 = (@6*@75) */
  w82  = (w6*w75);
  /* #784: @26 = (@26+@82) */
  w26 += w82;
  /* #785: @82 = (@9*@79) */
  w82  = (w9*w79);
  /* #786: @26 = (@26+@82) */
  w26 += w82;
  /* #787: @82 = (@8*@23) */
  w82  = (w8*w23);
  /* #788: @26 = (@26-@82) */
  w26 -= w82;
  /* #789: @82 = (@8*@81) */
  w82  = (w8*w81);
  /* #790: @83 = (@9*@75) */
  w83  = (w9*w75);
  /* #791: @82 = (@82-@83) */
  w82 -= w83;
  /* #792: @83 = (@6*@79) */
  w83  = (w6*w79);
  /* #793: @82 = (@82+@83) */
  w82 += w83;
  /* #794: @83 = (@7*@23) */
  w83  = (w7*w23);
  /* #795: @82 = (@82+@83) */
  w82 += w83;
  /* #796: @81 = (@9*@81) */
  w81  = (w9*w81);
  /* #797: @75 = (@8*@75) */
  w75  = (w8*w75);
  /* #798: @81 = (@81+@75) */
  w81 += w75;
  /* #799: @79 = (@7*@79) */
  w79  = (w7*w79);
  /* #800: @81 = (@81-@79) */
  w81 -= w79;
  /* #801: @23 = (@6*@23) */
  w23  = (w6*w23);
  /* #802: @81 = (@81+@23) */
  w81 += w23;
  /* #803: @73 = vertcat(@80, @26, @82, @81) */
  rr=w73;
  *rr++ = w80;
  *rr++ = w26;
  *rr++ = w82;
  *rr++ = w81;
  /* #804: @64 = (@14*@73) */
  for (i=0, rr=w64, cs=w73; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #805: @73 = (@15*@73) */
  for (i=0, rr=w73, cs=w73; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #806: @64 = (@64-@73) */
  for (i=0, rr=w64, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #807: @1 = @64[1:4] */
  for (rr=w1, ss=w64+1; ss!=w64+4; ss+=1) *rr++ = *ss;
  /* #808: @80 = dot(@41, @1) */
  w80 = casadi_dot(3, w41, w1);
  /* #809: @80 = (@80/@16) */
  w80 /= w16;
  /* #810: @26 = (@80/@5) */
  w26  = (w80/w5);
  /* #811: @82 = (@20*@80) */
  w82  = (w20*w80);
  /* #812: @81 = @64[0] */
  for (rr=(&w81), ss=w64+0; ss!=w64+1; ss+=1) *rr++ = *ss;
  /* #813: @23 = (@22*@81) */
  w23  = (w22*w81);
  /* #814: @82 = (@82+@23) */
  w82 += w23;
  /* #815: @23 = (@71*@82) */
  w23  = (w71*w82);
  /* #816: @26 = (@26-@23) */
  w26 -= w23;
  /* #817: @26 = (@0*@26) */
  w26  = (w0*w26);
  /* #818: @52 = zeros(1x3) */
  casadi_clear(w52, 3);
  /* #819: @31 = (2.*@1) */
  for (i=0, rr=w31, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #820: @34 = (@11*@31) */
  for (i=0, rr=w34, cs=w31; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #821: @23 = (@17*@80) */
  w23  = (w17*w80);
  /* #822: @79 = (@72*@81) */
  w79  = (w72*w81);
  /* #823: @23 = (@23-@79) */
  w23 -= w79;
  /* #824: @2 = (@42*@23) */
  for (i=0, rr=w2, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w23);
  /* #825: @34 = (@34+@2) */
  for (i=0, rr=w34, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #826: @34 = (@34/@16) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) /= w16;
  /* #827: @2 = (@43*@80) */
  for (i=0, rr=w2, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #828: @34 = (@34-@2) */
  for (i=0, rr=w34, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #829: @2 = @34' */
  casadi_copy(w34, 3, w2);
  /* #830: @52 = mac(@2,@45,@52) */
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #831: @52 = @52' */
  /* #832: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #833: @76 = @34' */
  casadi_copy(w34, 3, w76);
  /* #834: @2 = mac(@76,@50,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w76+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #835: @2 = @2' */
  /* #836: @52 = (@52+@2) */
  for (i=0, rr=w52, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #837: @2 = (@52/@16) */
  for (i=0, rr=w2, cr=w52; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #838: @76 = (@53*@80) */
  for (i=0, rr=w76, cr=w53; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #839: @2 = (@2-@76) */
  for (i=0, rr=w2, cs=w76; i<3; ++i) (*rr++) -= (*cs++);
  /* #840: @79 = dot(@42, @2) */
  w79 = casadi_dot(3, w42, w2);
  /* #841: @75 = dot(@31, @44) */
  w75 = casadi_dot(3, w31, w44);
  /* #842: @79 = (@79+@75) */
  w79 += w75;
  /* #843: @75 = (@4*@79) */
  w75  = (w4*w79);
  /* #844: @26 = (@26+@75) */
  w26 += w75;
  /* #845: @26 = (-@26) */
  w26 = (- w26 );
  /* #846: (@70[0] += @26) */
  for (rr=w70+0, ss=(&w26); rr!=w70+1; rr+=1) *rr += *ss++;
  /* #847: @26 = dot(@51, @52) */
  w26 = casadi_dot(3, w51, w52);
  /* #848: @34 = (@34/@16) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) /= w16;
  /* #849: @52 = (@49*@80) */
  for (i=0, rr=w52, cr=w49; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #850: @34 = (@34-@52) */
  for (i=0, rr=w34, cs=w52; i<3; ++i) (*rr++) -= (*cs++);
  /* #851: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #852: @75 = dot(@34, @35) */
  w75 = casadi_dot(3, w34, w35);
  /* #853: @26 = (@26+@75) */
  w26 += w75;
  /* #854: @81 = (@81/@5) */
  w81 /= w5;
  /* #855: @82 = (@77*@82) */
  w82  = (w77*w82);
  /* #856: @81 = (@81-@82) */
  w81 -= w82;
  /* #857: @81 = (@0*@81) */
  w81  = (w0*w81);
  /* #858: @79 = (@18*@79) */
  w79  = (w18*w79);
  /* #859: @81 = (@81+@79) */
  w81 += w79;
  /* #860: @26 = (@26+@81) */
  w26 += w81;
  /* #861: @26 = (@26/@16) */
  w26 /= w16;
  /* #862: @80 = (@21*@80) */
  w80  = (w21*w80);
  /* #863: @26 = (@26-@80) */
  w26 -= w80;
  /* #864: @34 = (@41*@26) */
  for (i=0, rr=w34, cr=w41; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #865: @1 = (@12*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #866: @34 = (@34+@1) */
  for (i=0, rr=w34, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #867: @1 = (@44*@23) */
  for (i=0, rr=w1, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w23);
  /* #868: @2 = (@11*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #869: @1 = (@1+@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #870: @1 = (2.*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #871: @34 = (@34+@1) */
  for (i=0, rr=w34, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #872: (@70[1:4] += @34) */
  for (rr=w70+1, ss=w34; rr!=w70+4; rr+=1) *rr += *ss++;
  /* #873: @64 = (@13*@70) */
  for (i=0, rr=w64, cs=w70; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #874: @70 = (@19*@70) */
  for (i=0, rr=w70, cs=w70; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #875: @64 = (@64-@70) */
  for (i=0, rr=w64, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #876: {@23, @26, @80, @81} = vertsplit(@64) */
  w23 = w64[0];
  w26 = w64[1];
  w80 = w64[2];
  w81 = w64[3];
  /* #877: @79 = (@9*@81) */
  w79  = (w9*w81);
  /* #878: @82 = (@8*@80) */
  w82  = (w8*w80);
  /* #879: @79 = (@79+@82) */
  w79 += w82;
  /* #880: @82 = (@7*@26) */
  w82  = (w7*w26);
  /* #881: @79 = (@79+@82) */
  w79 += w82;
  /* #882: @82 = (@6*@23) */
  w82  = (w6*w23);
  /* #883: @79 = (@79+@82) */
  w79 += w82;
  /* #884: @82 = (@8*@81) */
  w82  = (w8*w81);
  /* #885: @75 = (@9*@80) */
  w75  = (w9*w80);
  /* #886: @82 = (@82-@75) */
  w82 -= w75;
  /* #887: @75 = (@6*@26) */
  w75  = (w6*w26);
  /* #888: @82 = (@82+@75) */
  w82 += w75;
  /* #889: @75 = (@7*@23) */
  w75  = (w7*w23);
  /* #890: @82 = (@82-@75) */
  w82 -= w75;
  /* #891: @75 = (@6*@80) */
  w75  = (w6*w80);
  /* #892: @83 = (@7*@81) */
  w83  = (w7*w81);
  /* #893: @75 = (@75-@83) */
  w75 -= w83;
  /* #894: @83 = (@9*@26) */
  w83  = (w9*w26);
  /* #895: @75 = (@75+@83) */
  w75 += w83;
  /* #896: @83 = (@8*@23) */
  w83  = (w8*w23);
  /* #897: @75 = (@75-@83) */
  w75 -= w83;
  /* #898: @81 = (@6*@81) */
  w81  = (w6*w81);
  /* #899: @80 = (@7*@80) */
  w80  = (w7*w80);
  /* #900: @81 = (@81+@80) */
  w81 += w80;
  /* #901: @26 = (@8*@26) */
  w26  = (w8*w26);
  /* #902: @81 = (@81-@26) */
  w81 -= w26;
  /* #903: @23 = (@9*@23) */
  w23  = (w9*w23);
  /* #904: @81 = (@81-@23) */
  w81 -= w23;
  /* #905: @64 = vertcat(@79, @82, @75, @81) */
  rr=w64;
  *rr++ = w79;
  *rr++ = w82;
  *rr++ = w75;
  *rr++ = w81;
  /* #906: @79 = dot(@46, @64) */
  w79 = casadi_dot(4, w46, w64);
  /* #907: @69 = (@69/@10) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w10;
  /* #908: @70 = (@40*@27) */
  for (i=0, rr=w70, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w27);
  /* #909: @69 = (@69-@70) */
  for (i=0, rr=w69, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #910: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #911: @82 = dot(@69, @54) */
  w82 = casadi_dot(4, w69, w54);
  /* #912: @79 = (@79+@82) */
  w79 += w82;
  /* #913: @79 = (@79/@10) */
  w79 /= w10;
  /* #914: @82 = (@78*@27) */
  w82  = (w78*w27);
  /* #915: @79 = (@79-@82) */
  w79 -= w82;
  /* #916: @69 = (@38*@79) */
  for (i=0, rr=w69, cr=w38; i<4; ++i) (*rr++)  = ((*cr++)*w79);
  /* #917: @28 = (@24*@28) */
  w28  = (w24*w28);
  /* #918: @70 = dense(@28) */
  casadi_densify((&w28), casadi_s17, w70, 0);
  /* #919: @69 = (@69+@70) */
  for (i=0, rr=w69, cs=w70; i<4; ++i) (*rr++) += (*cs++);
  /* #920: (@33[6:10] += @69) */
  for (rr=w33+6, ss=w69; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #921: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #922: @28 = project(@30) */
  casadi_sparsify(w30, (&w28), casadi_s18, 0);
  /* #923: @79 = @59[0] */
  for (rr=(&w79), ss=(&w59)+0; ss!=(&w59)+1; ss+=1) *rr++ = *ss;
  /* #924: @79 = (-@79) */
  w79 = (- w79 );
  /* #925: @59 = dot(@28, @79) */
  w59 = casadi_dot(1, (&w28), (&w79));
  /* #926: @1 = (@30*@59) */
  for (i=0, rr=w1, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w59);
  /* #927: @2 = @1' */
  casadi_copy(w1, 3, w2);
  /* #928: @34 = mac(@2,@36,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #929: @34 = @34' */
  /* #930: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #931: @1 = @1' */
  /* #932: @2 = mac(@1,@55,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #933: @2 = @2' */
  /* #934: @34 = (@34+@2) */
  for (i=0, rr=w34, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #935: @59 = dot(@30, @34) */
  w59 = casadi_dot(3, w30, w34);
  /* #936: @30 = (@30*@59) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) *= w59;
  /* #937: @34 = zeros(3x1) */
  casadi_clear(w34, 3);
  /* #938: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #939: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #940: @1 = mac(@3,@79,@1) */
  casadi_mtimes(w3, casadi_s7, (&w79), casadi_s18, w1, casadi_s6, w, 0);
  /* #941: @52 = @1' */
  casadi_copy(w1, 3, w52);
  /* #942: @2 = mac(@52,@32,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w52+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #943: @2 = @2' */
  /* #944: @52 = zeros(1x3) */
  casadi_clear(w52, 3);
  /* #945: @1 = @1' */
  /* #946: @52 = mac(@1,@57,@52) */
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w57+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #947: @52 = @52' */
  /* #948: @2 = (@2+@52) */
  for (i=0, rr=w2, cs=w52; i<3; ++i) (*rr++) += (*cs++);
  /* #949: @34 = mac(@56,@2,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w56+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #950: @30 = (@30+@34) */
  for (i=0, rr=w30, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #951: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #952: (@33[:3] += @30) */
  for (rr=w33+0, ss=w30; rr!=w33+3; rr+=1) *rr += *ss++;
  /* #953: {@79, @59, @28, @82, @75, @81, @23, @26, @80, @83, @84, @87, @25} = vertsplit(@33) */
  w79 = w33[0];
  w59 = w33[1];
  w28 = w33[2];
  w82 = w33[3];
  w75 = w33[4];
  w81 = w33[5];
  w23 = w33[6];
  w26 = w33[7];
  w80 = w33[8];
  w83 = w33[9];
  w84 = w33[10];
  w87 = w33[11];
  w25 = w33[12];
  /* #954: @64 = (@64/@10) */
  for (i=0, rr=w64; i<4; ++i) (*rr++) /= w10;
  /* #955: @69 = (@39*@27) */
  for (i=0, rr=w69, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)*w27);
  /* #956: @64 = (@64-@69) */
  for (i=0, rr=w64, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #957: {@27, @85, @86, @60} = vertsplit(@64) */
  w27 = w64[0];
  w85 = w64[1];
  w86 = w64[2];
  w60 = w64[3];
  /* #958: @27 = (@27+@23) */
  w27 += w23;
  /* #959: @26 = (@26-@85) */
  w26 -= w85;
  /* #960: @80 = (@80-@86) */
  w80 -= w86;
  /* #961: @83 = (@83-@60) */
  w83 -= w60;
  /* #962: @88 = vertcat(@61, @58, @74, @62, @79, @59, @28, @82, @75, @81, @27, @26, @80, @83, @84, @87, @25) */
  rr=w88;
  *rr++ = w61;
  *rr++ = w58;
  *rr++ = w74;
  *rr++ = w62;
  *rr++ = w79;
  *rr++ = w59;
  *rr++ = w28;
  *rr++ = w82;
  *rr++ = w75;
  *rr++ = w81;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w80;
  *rr++ = w83;
  *rr++ = w84;
  *rr++ = w87;
  *rr++ = w25;
  /* #963: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #964: (@63[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @89) */
  for (cii=casadi_s19, rr=w63, ss=w89; cii!=casadi_s19+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #965: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #966: (@63[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @89) */
  for (cii=casadi_s20, rr=w63, ss=w89; cii!=casadi_s20+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #967: @64 = zeros(1x4) */
  casadi_clear(w64, 4);
  /* #968: @66 = 00 */
  /* #969: @67 = 00 */
  /* #970: @68 = 00 */
  /* #971: @90 = ones(17x1,2nz) */
  casadi_fill(w90, 2, 1.);
  /* #972: {NULL, NULL, NULL, @61, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @58, NULL, NULL, NULL} = vertsplit(@90) */
  w61 = w90[0];
  w58 = w90[1];
  /* #973: @74 = vertcat(@66, @67, @68, @61) */
  rr=(&w74);
  *rr++ = w61;
  /* #974: @61 = @74' */
  casadi_copy((&w74), 1, (&w61));
  /* #975: @64 = mac(@61,@47,@64) */
  casadi_mtimes((&w61), casadi_s21, w47, casadi_s2, w64, casadi_s1, w, 0);
  /* #976: @64 = @64' */
  /* #977: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #978: @74 = @74' */
  /* #979: @69 = mac(@74,@48,@69) */
  casadi_mtimes((&w74), casadi_s21, w48, casadi_s2, w69, casadi_s1, w, 0);
  /* #980: @69 = @69' */
  /* #981: @64 = (@64+@69) */
  for (i=0, rr=w64, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #982: {@74, @61, @62, @79} = vertsplit(@64) */
  w74 = w64[0];
  w61 = w64[1];
  w62 = w64[2];
  w79 = w64[3];
  /* #983: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #984: @64 = zeros(4x1) */
  casadi_clear(w64, 4);
  /* #985: @66 = 00 */
  /* #986: @67 = 00 */
  /* #987: @68 = 00 */
  /* #988: @59 = (-@58) */
  w59 = (- w58 );
  /* #989: @28 = vertcat(@66, @67, @68, @59) */
  rr=(&w28);
  *rr++ = w59;
  /* #990: @28 = (@28/@10) */
  w28 /= w10;
  /* #991: @69 = dense(@28) */
  casadi_densify((&w28), casadi_s22, w69, 0);
  /* #992: @28 = project(@38) */
  casadi_sparsify(w38, (&w28), casadi_s22, 0);
  /* #993: @59 = @58[0] */
  for (rr=(&w59), ss=(&w58)+0; ss!=(&w58)+1; ss+=1) *rr++ = *ss;
  /* #994: @58 = dot(@28, @59) */
  w58 = casadi_dot(1, (&w28), (&w59));
  /* #995: @58 = (@58/@10) */
  w58 /= w10;
  /* #996: @37 = (@37*@58) */
  for (i=0, rr=w37; i<4; ++i) (*rr++) *= w58;
  /* #997: @69 = (@69-@37) */
  for (i=0, rr=w69, cs=w37; i<4; ++i) (*rr++) -= (*cs++);
  /* #998: {@28, @82, @75, @81} = vertsplit(@69) */
  w28 = w69[0];
  w82 = w69[1];
  w75 = w69[2];
  w81 = w69[3];
  /* #999: @27 = (@6*@28) */
  w27  = (w6*w28);
  /* #1000: @26 = (@7*@82) */
  w26  = (w7*w82);
  /* #1001: @27 = (@27-@26) */
  w27 -= w26;
  /* #1002: @26 = (@8*@75) */
  w26  = (w8*w75);
  /* #1003: @27 = (@27-@26) */
  w27 -= w26;
  /* #1004: @26 = (@9*@81) */
  w26  = (w9*w81);
  /* #1005: @27 = (@27-@26) */
  w27 -= w26;
  /* #1006: @26 = (@7*@28) */
  w26  = (w7*w28);
  /* #1007: @80 = (@6*@82) */
  w80  = (w6*w82);
  /* #1008: @26 = (@26+@80) */
  w26 += w80;
  /* #1009: @80 = (@9*@75) */
  w80  = (w9*w75);
  /* #1010: @26 = (@26+@80) */
  w26 += w80;
  /* #1011: @80 = (@8*@81) */
  w80  = (w8*w81);
  /* #1012: @26 = (@26-@80) */
  w26 -= w80;
  /* #1013: @80 = (@8*@28) */
  w80  = (w8*w28);
  /* #1014: @83 = (@9*@82) */
  w83  = (w9*w82);
  /* #1015: @80 = (@80-@83) */
  w80 -= w83;
  /* #1016: @83 = (@6*@75) */
  w83  = (w6*w75);
  /* #1017: @80 = (@80+@83) */
  w80 += w83;
  /* #1018: @83 = (@7*@81) */
  w83  = (w7*w81);
  /* #1019: @80 = (@80+@83) */
  w80 += w83;
  /* #1020: @28 = (@9*@28) */
  w28  = (w9*w28);
  /* #1021: @82 = (@8*@82) */
  w82  = (w8*w82);
  /* #1022: @28 = (@28+@82) */
  w28 += w82;
  /* #1023: @75 = (@7*@75) */
  w75  = (w7*w75);
  /* #1024: @28 = (@28-@75) */
  w28 -= w75;
  /* #1025: @81 = (@6*@81) */
  w81  = (w6*w81);
  /* #1026: @28 = (@28+@81) */
  w28 += w81;
  /* #1027: @37 = vertcat(@27, @26, @80, @28) */
  rr=w37;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w80;
  *rr++ = w28;
  /* #1028: @70 = (@14*@37) */
  for (i=0, rr=w70, cs=w37; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #1029: @37 = (@15*@37) */
  for (i=0, rr=w37, cs=w37; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #1030: @70 = (@70-@37) */
  for (i=0, rr=w70, cs=w37; i<4; ++i) (*rr++) -= (*cs++);
  /* #1031: @30 = @70[1:4] */
  for (rr=w30, ss=w70+1; ss!=w70+4; ss+=1) *rr++ = *ss;
  /* #1032: @15 = dot(@41, @30) */
  w15 = casadi_dot(3, w41, w30);
  /* #1033: @15 = (@15/@16) */
  w15 /= w16;
  /* #1034: @14 = (@15/@5) */
  w14  = (w15/w5);
  /* #1035: @20 = (@20*@15) */
  w20 *= w15;
  /* #1036: @27 = @70[0] */
  for (rr=(&w27), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  /* #1037: @22 = (@22*@27) */
  w22 *= w27;
  /* #1038: @20 = (@20+@22) */
  w20 += w22;
  /* #1039: @71 = (@71*@20) */
  w71 *= w20;
  /* #1040: @14 = (@14-@71) */
  w14 -= w71;
  /* #1041: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #1042: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #1043: @2 = (2.*@30) */
  for (i=0, rr=w2, cs=w30; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1044: @52 = (@11*@2) */
  for (i=0, rr=w52, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #1045: @17 = (@17*@15) */
  w17 *= w15;
  /* #1046: @72 = (@72*@27) */
  w72 *= w27;
  /* #1047: @17 = (@17-@72) */
  w17 -= w72;
  /* #1048: @1 = (@42*@17) */
  for (i=0, rr=w1, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #1049: @52 = (@52+@1) */
  for (i=0, rr=w52, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #1050: @52 = (@52/@16) */
  for (i=0, rr=w52; i<3; ++i) (*rr++) /= w16;
  /* #1051: @43 = (@43*@15) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) *= w15;
  /* #1052: @52 = (@52-@43) */
  for (i=0, rr=w52, cs=w43; i<3; ++i) (*rr++) -= (*cs++);
  /* #1053: @43 = @52' */
  casadi_copy(w52, 3, w43);
  /* #1054: @34 = mac(@43,@45,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1055: @34 = @34' */
  /* #1056: @43 = zeros(1x3) */
  casadi_clear(w43, 3);
  /* #1057: @1 = @52' */
  casadi_copy(w52, 3, w1);
  /* #1058: @43 = mac(@1,@50,@43) */
  for (i=0, rr=w43; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1059: @43 = @43' */
  /* #1060: @34 = (@34+@43) */
  for (i=0, rr=w34, cs=w43; i<3; ++i) (*rr++) += (*cs++);
  /* #1061: @43 = (@34/@16) */
  for (i=0, rr=w43, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #1062: @53 = (@53*@15) */
  for (i=0, rr=w53; i<3; ++i) (*rr++) *= w15;
  /* #1063: @43 = (@43-@53) */
  for (i=0, rr=w43, cs=w53; i<3; ++i) (*rr++) -= (*cs++);
  /* #1064: @72 = dot(@42, @43) */
  w72 = casadi_dot(3, w42, w43);
  /* #1065: @71 = dot(@2, @44) */
  w71 = casadi_dot(3, w2, w44);
  /* #1066: @72 = (@72+@71) */
  w72 += w71;
  /* #1067: @4 = (@4*@72) */
  w4 *= w72;
  /* #1068: @14 = (@14+@4) */
  w14 += w4;
  /* #1069: @14 = (-@14) */
  w14 = (- w14 );
  /* #1070: (@64[0] += @14) */
  for (rr=w64+0, ss=(&w14); rr!=w64+1; rr+=1) *rr += *ss++;
  /* #1071: @14 = dot(@51, @34) */
  w14 = casadi_dot(3, w51, w34);
  /* #1072: @52 = (@52/@16) */
  for (i=0, rr=w52; i<3; ++i) (*rr++) /= w16;
  /* #1073: @49 = (@49*@15) */
  for (i=0, rr=w49; i<3; ++i) (*rr++) *= w15;
  /* #1074: @52 = (@52-@49) */
  for (i=0, rr=w52, cs=w49; i<3; ++i) (*rr++) -= (*cs++);
  /* #1075: @52 = (-@52) */
  for (i=0, rr=w52, cs=w52; i<3; ++i) *rr++ = (- *cs++ );
  /* #1076: @4 = dot(@52, @35) */
  w4 = casadi_dot(3, w52, w35);
  /* #1077: @14 = (@14+@4) */
  w14 += w4;
  /* #1078: @27 = (@27/@5) */
  w27 /= w5;
  /* #1079: @77 = (@77*@20) */
  w77 *= w20;
  /* #1080: @27 = (@27-@77) */
  w27 -= w77;
  /* #1081: @0 = (@0*@27) */
  w0 *= w27;
  /* #1082: @18 = (@18*@72) */
  w18 *= w72;
  /* #1083: @0 = (@0+@18) */
  w0 += w18;
  /* #1084: @14 = (@14+@0) */
  w14 += w0;
  /* #1085: @14 = (@14/@16) */
  w14 /= w16;
  /* #1086: @21 = (@21*@15) */
  w21 *= w15;
  /* #1087: @14 = (@14-@21) */
  w14 -= w21;
  /* #1088: @41 = (@41*@14) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) *= w14;
  /* #1089: @30 = (@12*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #1090: @41 = (@41+@30) */
  for (i=0, rr=w41, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #1091: @44 = (@44*@17) */
  for (i=0, rr=w44; i<3; ++i) (*rr++) *= w17;
  /* #1092: @43 = (@11*@43) */
  for (i=0, rr=w43, cs=w43; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #1093: @44 = (@44+@43) */
  for (i=0, rr=w44, cs=w43; i<3; ++i) (*rr++) += (*cs++);
  /* #1094: @44 = (2.*@44) */
  for (i=0, rr=w44, cs=w44; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1095: @41 = (@41+@44) */
  for (i=0, rr=w41, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #1096: (@64[1:4] += @41) */
  for (rr=w64+1, ss=w41; rr!=w64+4; rr+=1) *rr += *ss++;
  /* #1097: @70 = (@13*@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #1098: @64 = (@19*@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #1099: @70 = (@70-@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #1100: {@19, @13, @11, @17} = vertsplit(@70) */
  w19 = w70[0];
  w13 = w70[1];
  w11 = w70[2];
  w17 = w70[3];
  /* #1101: @12 = (@9*@17) */
  w12  = (w9*w17);
  /* #1102: @14 = (@8*@11) */
  w14  = (w8*w11);
  /* #1103: @12 = (@12+@14) */
  w12 += w14;
  /* #1104: @14 = (@7*@13) */
  w14  = (w7*w13);
  /* #1105: @12 = (@12+@14) */
  w12 += w14;
  /* #1106: @14 = (@6*@19) */
  w14  = (w6*w19);
  /* #1107: @12 = (@12+@14) */
  w12 += w14;
  /* #1108: @14 = (@8*@17) */
  w14  = (w8*w17);
  /* #1109: @21 = (@9*@11) */
  w21  = (w9*w11);
  /* #1110: @14 = (@14-@21) */
  w14 -= w21;
  /* #1111: @21 = (@6*@13) */
  w21  = (w6*w13);
  /* #1112: @14 = (@14+@21) */
  w14 += w21;
  /* #1113: @21 = (@7*@19) */
  w21  = (w7*w19);
  /* #1114: @14 = (@14-@21) */
  w14 -= w21;
  /* #1115: @21 = (@6*@11) */
  w21  = (w6*w11);
  /* #1116: @15 = (@7*@17) */
  w15  = (w7*w17);
  /* #1117: @21 = (@21-@15) */
  w21 -= w15;
  /* #1118: @15 = (@9*@13) */
  w15  = (w9*w13);
  /* #1119: @21 = (@21+@15) */
  w21 += w15;
  /* #1120: @15 = (@8*@19) */
  w15  = (w8*w19);
  /* #1121: @21 = (@21-@15) */
  w21 -= w15;
  /* #1122: @6 = (@6*@17) */
  w6 *= w17;
  /* #1123: @7 = (@7*@11) */
  w7 *= w11;
  /* #1124: @6 = (@6+@7) */
  w6 += w7;
  /* #1125: @8 = (@8*@13) */
  w8 *= w13;
  /* #1126: @6 = (@6-@8) */
  w6 -= w8;
  /* #1127: @9 = (@9*@19) */
  w9 *= w19;
  /* #1128: @6 = (@6-@9) */
  w6 -= w9;
  /* #1129: @70 = vertcat(@12, @14, @21, @6) */
  rr=w70;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w21;
  *rr++ = w6;
  /* #1130: @12 = dot(@46, @70) */
  w12 = casadi_dot(4, w46, w70);
  /* #1131: @69 = (@69/@10) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w10;
  /* #1132: @40 = (@40*@58) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) *= w58;
  /* #1133: @69 = (@69-@40) */
  for (i=0, rr=w69, cs=w40; i<4; ++i) (*rr++) -= (*cs++);
  /* #1134: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #1135: @14 = dot(@69, @54) */
  w14 = casadi_dot(4, w69, w54);
  /* #1136: @12 = (@12+@14) */
  w12 += w14;
  /* #1137: @12 = (@12/@10) */
  w12 /= w10;
  /* #1138: @78 = (@78*@58) */
  w78 *= w58;
  /* #1139: @12 = (@12-@78) */
  w12 -= w78;
  /* #1140: @38 = (@38*@12) */
  for (i=0, rr=w38; i<4; ++i) (*rr++) *= w12;
  /* #1141: @24 = (@24*@59) */
  w24 *= w59;
  /* #1142: @69 = dense(@24) */
  casadi_densify((&w24), casadi_s22, w69, 0);
  /* #1143: @38 = (@38+@69) */
  for (i=0, rr=w38, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #1144: (@33[6:10] += @38) */
  for (rr=w33+6, ss=w38; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #1145: {@24, @59, @12, @78, @14, @21, @6, @9, @19, @8, @13, @7, @11} = vertsplit(@33) */
  w24 = w33[0];
  w59 = w33[1];
  w12 = w33[2];
  w78 = w33[3];
  w14 = w33[4];
  w21 = w33[5];
  w6 = w33[6];
  w9 = w33[7];
  w19 = w33[8];
  w8 = w33[9];
  w13 = w33[10];
  w7 = w33[11];
  w11 = w33[12];
  /* #1146: @70 = (@70/@10) */
  for (i=0, rr=w70; i<4; ++i) (*rr++) /= w10;
  /* #1147: @39 = (@39*@58) */
  for (i=0, rr=w39; i<4; ++i) (*rr++) *= w58;
  /* #1148: @70 = (@70-@39) */
  for (i=0, rr=w70, cs=w39; i<4; ++i) (*rr++) -= (*cs++);
  /* #1149: {@58, @10, @17, @15} = vertsplit(@70) */
  w58 = w70[0];
  w10 = w70[1];
  w17 = w70[2];
  w15 = w70[3];
  /* #1150: @58 = (@58+@6) */
  w58 += w6;
  /* #1151: @9 = (@9-@10) */
  w9 -= w10;
  /* #1152: @19 = (@19-@17) */
  w19 -= w17;
  /* #1153: @8 = (@8-@15) */
  w8 -= w15;
  /* #1154: @88 = vertcat(@74, @61, @62, @79, @24, @59, @12, @78, @14, @21, @58, @9, @19, @8, @13, @7, @11) */
  rr=w88;
  *rr++ = w74;
  *rr++ = w61;
  *rr++ = w62;
  *rr++ = w79;
  *rr++ = w24;
  *rr++ = w59;
  *rr++ = w12;
  *rr++ = w78;
  *rr++ = w14;
  *rr++ = w21;
  *rr++ = w58;
  *rr++ = w9;
  *rr++ = w19;
  *rr++ = w8;
  *rr++ = w13;
  *rr++ = w7;
  *rr++ = w11;
  /* #1155: @91 = @88[:20:10;:4] */
  for (rr=w91, ss=w88+0; ss!=w88+20; ss+=10) for (tt=ss+0; tt!=ss+4; tt+=1) *rr++ = *tt;
  /* #1156: (@63[:50:25;12:16] = @91) */
  for (rr=w63+0, ss=w91; rr!=w63+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *ss++;
  /* #1157: @91 = @88[:20:10;:4] */
  for (rr=w91, ss=w88+0; ss!=w88+20; ss+=10) for (tt=ss+0; tt!=ss+4; tt+=1) *rr++ = *tt;
  /* #1158: (@63[:50:25;3:19:4] = @91) */
  for (rr=w63+0, ss=w91; rr!=w63+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *ss++;
  /* #1159: @92 = @63' */
  casadi_trans(w63,casadi_s23, w92, casadi_s23, iw);
  /* #1160: output[2][0] = @92 */
  casadi_copy(w92, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s24;
    case 1: return casadi_s25;
    case 2: return casadi_s26;
    case 3: return casadi_s27;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s28;
    case 1: return casadi_s29;
    case 2: return casadi_s23;
    case 3: return casadi_s26;
    case 4: return casadi_s30;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 28;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 404;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
