/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s2[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s6[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[9] = {3., 0., 0., 0., 3., 0., 0., 0., 3.};
static const casadi_real casadi_c2[16] = {2.0000000000000000e-03, 0., 0., 0., 0., 200., 0., 0., 0., 0., 200., 0., 0., 0., 0., 200.};

/* Drone_ode_complete_cost_ext_cost_0_fun_jac:(i0[13],i1[4],i2[],i3[24])->(o0,o1[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+4, *w2=w+7, *w3=w+10, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, *w29=w+44, *w30=w+68, *w31=w+71, *w32=w+74, *w33=w+83, *w34=w+96, *w35=w+99, *w36=w+102, *w37=w+111, *w38=w+115, *w39=w+119, *w40=w+123, *w41=w+127, *w42=w+130, *w43=w+133, *w44=w+136, *w45=w+139, *w46=w+148, *w47=w+152, *w48=w+168, *w49=w+184, *w50=w+187;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #6: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #7: @7 = input[3][2] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #8: @8 = input[3][3] */
  w8 = arg[3] ? arg[3][3] : 0;
  /* #9: @9 = input[3][4] */
  w9 = arg[3] ? arg[3][4] : 0;
  /* #10: @10 = input[3][5] */
  w10 = arg[3] ? arg[3][5] : 0;
  /* #11: @11 = input[3][6] */
  w11 = arg[3] ? arg[3][6] : 0;
  /* #12: @12 = input[3][7] */
  w12 = arg[3] ? arg[3][7] : 0;
  /* #13: @13 = input[3][8] */
  w13 = arg[3] ? arg[3][8] : 0;
  /* #14: @14 = input[3][9] */
  w14 = arg[3] ? arg[3][9] : 0;
  /* #15: @15 = input[3][10] */
  w15 = arg[3] ? arg[3][10] : 0;
  /* #16: @16 = input[3][11] */
  w16 = arg[3] ? arg[3][11] : 0;
  /* #17: @17 = input[3][12] */
  w17 = arg[3] ? arg[3][12] : 0;
  /* #18: @18 = input[3][13] */
  w18 = arg[3] ? arg[3][13] : 0;
  /* #19: @19 = input[3][14] */
  w19 = arg[3] ? arg[3][14] : 0;
  /* #20: @20 = input[3][15] */
  w20 = arg[3] ? arg[3][15] : 0;
  /* #21: @21 = input[3][16] */
  w21 = arg[3] ? arg[3][16] : 0;
  /* #22: @22 = input[3][17] */
  w22 = arg[3] ? arg[3][17] : 0;
  /* #23: @23 = input[3][18] */
  w23 = arg[3] ? arg[3][18] : 0;
  /* #24: @24 = input[3][19] */
  w24 = arg[3] ? arg[3][19] : 0;
  /* #25: @25 = input[3][20] */
  w25 = arg[3] ? arg[3][20] : 0;
  /* #26: @26 = input[3][21] */
  w26 = arg[3] ? arg[3][21] : 0;
  /* #27: @27 = input[3][22] */
  w27 = arg[3] ? arg[3][22] : 0;
  /* #28: @28 = input[3][23] */
  w28 = arg[3] ? arg[3][23] : 0;
  /* #29: @29 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28) */
  rr=w29;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  /* #30: @30 = @29[3:6] */
  for (rr=w30, ss=w29+3; ss!=w29+6; ss+=1) *rr++ = *ss;
  /* #31: @31 = @30' */
  casadi_copy(w30, 3, w31);
  /* #32: @4 = mac(@31,@30,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #33: @32 = @4[0, 0, 0, 0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w32, ss=(&w4); cii!=casadi_s0+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #34: @3 = (@3-@32) */
  for (i=0, rr=w3, cs=w32; i<9; ++i) (*rr++) -= (*cs++);
  /* #35: @31 = @29[:3] */
  for (rr=w31, ss=w29+0; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #36: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #37: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #38: @6 = input[0][2] */
  w6 = arg[0] ? arg[0][2] : 0;
  /* #39: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #40: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #41: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #42: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #43: @11 = input[0][7] */
  w11 = arg[0] ? arg[0][7] : 0;
  /* #44: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #45: @13 = input[0][9] */
  w13 = arg[0] ? arg[0][9] : 0;
  /* #46: @14 = input[0][10] */
  w14 = arg[0] ? arg[0][10] : 0;
  /* #47: @15 = input[0][11] */
  w15 = arg[0] ? arg[0][11] : 0;
  /* #48: @16 = input[0][12] */
  w16 = arg[0] ? arg[0][12] : 0;
  /* #49: @33 = vertcat(@4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w33;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #50: @34 = @33[:3] */
  for (rr=w34, ss=w33+0; ss!=w33+3; ss+=1) *rr++ = *ss;
  /* #51: @31 = (@31-@34) */
  for (i=0, rr=w31, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #52: @2 = mac(@3,@31,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #53: @34 = @2' */
  casadi_copy(w2, 3, w34);
  /* #54: @32 = 
  [[3, 0, 0], 
   [0, 3, 0], 
   [0, 0, 3]] */
  casadi_copy(casadi_c1, 9, w32);
  /* #55: @1 = mac(@34,@32,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #56: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #57: @4 = 0 */
  w4 = 0.;
  /* #58: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #59: @5 = dot(@30, @31) */
  w5 = casadi_dot(3, w30, w31);
  /* #60: @31 = (@5*@30) */
  for (i=0, rr=w31, cs=w30; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #61: @35 = @31' */
  casadi_copy(w31, 3, w35);
  /* #62: @36 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w36);
  /* #63: @34 = mac(@35,@36,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #64: @4 = mac(@34,@31,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #65: @0 = (@0+@4) */
  w0 += w4;
  /* #66: @4 = 0 */
  w4 = 0.;
  /* #67: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #68: @11 = (-@11) */
  w11 = (- w11 );
  /* #69: @12 = (-@12) */
  w12 = (- w12 );
  /* #70: @13 = (-@13) */
  w13 = (- w13 );
  /* #71: @37 = vertcat(@10, @11, @12, @13) */
  rr=w37;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #72: @38 = @33[6:10] */
  for (rr=w38, ss=w33+6; ss!=w33+10; ss+=1) *rr++ = *ss;
  /* #73: @10 = ||@38||_F */
  w10 = sqrt(casadi_dot(4, w38, w38));
  /* #74: @37 = (@37/@10) */
  for (i=0, rr=w37; i<4; ++i) (*rr++) /= w10;
  /* #75: {@11, @12, @13, @5} = vertsplit(@37) */
  w11 = w37[0];
  w12 = w37[1];
  w13 = w37[2];
  w5 = w37[3];
  /* #76: @39 = @29[6:10] */
  for (rr=w39, ss=w29+6; ss!=w29+10; ss+=1) *rr++ = *ss;
  /* #77: {@6, @7, @8, @9} = vertsplit(@39) */
  w6 = w39[0];
  w7 = w39[1];
  w8 = w39[2];
  w9 = w39[3];
  /* #78: @14 = (@11*@6) */
  w14  = (w11*w6);
  /* #79: @15 = (@12*@7) */
  w15  = (w12*w7);
  /* #80: @14 = (@14-@15) */
  w14 -= w15;
  /* #81: @15 = (@13*@8) */
  w15  = (w13*w8);
  /* #82: @14 = (@14-@15) */
  w14 -= w15;
  /* #83: @15 = (@5*@9) */
  w15  = (w5*w9);
  /* #84: @14 = (@14-@15) */
  w14 -= w15;
  /* #85: @15 = 0 */
  w15 = 0.;
  /* #86: @15 = (@14<@15) */
  w15  = (w14<w15);
  /* #87: @16 = (@11*@7) */
  w16  = (w11*w7);
  /* #88: @17 = (@12*@6) */
  w17  = (w12*w6);
  /* #89: @16 = (@16+@17) */
  w16 += w17;
  /* #90: @17 = (@13*@9) */
  w17  = (w13*w9);
  /* #91: @16 = (@16+@17) */
  w16 += w17;
  /* #92: @17 = (@5*@8) */
  w17  = (w5*w8);
  /* #93: @16 = (@16-@17) */
  w16 -= w17;
  /* #94: @17 = (@11*@8) */
  w17  = (w11*w8);
  /* #95: @18 = (@12*@9) */
  w18  = (w12*w9);
  /* #96: @17 = (@17-@18) */
  w17 -= w18;
  /* #97: @18 = (@13*@6) */
  w18  = (w13*w6);
  /* #98: @17 = (@17+@18) */
  w17 += w18;
  /* #99: @18 = (@5*@7) */
  w18  = (w5*w7);
  /* #100: @17 = (@17+@18) */
  w17 += w18;
  /* #101: @11 = (@11*@9) */
  w11 *= w9;
  /* #102: @12 = (@12*@8) */
  w12 *= w8;
  /* #103: @11 = (@11+@12) */
  w11 += w12;
  /* #104: @13 = (@13*@7) */
  w13 *= w7;
  /* #105: @11 = (@11-@13) */
  w11 -= w13;
  /* #106: @5 = (@5*@6) */
  w5 *= w6;
  /* #107: @11 = (@11+@5) */
  w11 += w5;
  /* #108: @39 = vertcat(@14, @16, @17, @11) */
  rr=w39;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w11;
  /* #109: @40 = (-@39) */
  for (i=0, rr=w40, cs=w39; i<4; ++i) *rr++ = (- *cs++ );
  /* #110: @40 = (@15?@40:0) */
  for (i=0, rr=w40, cs=w40; i<4; ++i) (*rr++)  = (w15?(*cs++):0);
  /* #111: @14 = (!@15) */
  w14 = (! w15 );
  /* #112: @39 = (@14?@39:0) */
  for (i=0, rr=w39, cs=w39; i<4; ++i) (*rr++)  = (w14?(*cs++):0);
  /* #113: @40 = (@40+@39) */
  for (i=0, rr=w40, cs=w39; i<4; ++i) (*rr++) += (*cs++);
  /* #114: @41 = @40[1:4] */
  for (rr=w41, ss=w40+1; ss!=w40+4; ss+=1) *rr++ = *ss;
  /* #115: @42 = (2.*@41) */
  for (i=0, rr=w42, cs=w41; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #116: @16 = ||@41||_F */
  w16 = sqrt(casadi_dot(3, w41, w41));
  /* #117: @17 = @40[0] */
  for (rr=(&w17), ss=w40+0; ss!=w40+1; ss+=1) *rr++ = *ss;
  /* #118: @11 = atan2(@16,@17) */
  w11  = atan2(w16,w17);
  /* #119: @43 = (@42*@11) */
  for (i=0, rr=w43, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w11);
  /* #120: @43 = (@43/@16) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) /= w16;
  /* #121: @44 = @43' */
  casadi_copy(w43, 3, w44);
  /* #122: @45 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w45);
  /* #123: @35 = mac(@44,@45,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w44+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #124: @4 = mac(@35,@43,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w43+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #125: @0 = (@0+@4) */
  w0 += w4;
  /* #126: @4 = 0 */
  w4 = 0.;
  /* #127: @40 = zeros(1x4) */
  casadi_clear(w40, 4);
  /* #128: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #129: @13 = input[1][1] */
  w13 = arg[1] ? arg[1][1] : 0;
  /* #130: @12 = input[1][2] */
  w12 = arg[1] ? arg[1][2] : 0;
  /* #131: @18 = input[1][3] */
  w18 = arg[1] ? arg[1][3] : 0;
  /* #132: @39 = vertcat(@5, @13, @12, @18) */
  rr=w39;
  *rr++ = w5;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w18;
  /* #133: @46 = @39' */
  casadi_copy(w39, 4, w46);
  /* #134: @47 = 
  [[0.002, 0, 0, 0], 
   [0, 200, 0, 0], 
   [0, 0, 200, 0], 
   [0, 0, 0, 200]] */
  casadi_copy(casadi_c2, 16, w47);
  /* #135: @40 = mac(@46,@47,@40) */
  for (i=0, rr=w40; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w46+j, tt=w47+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #136: @4 = mac(@40,@39,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w40+j, tt=w39+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #137: @0 = (@0+@4) */
  w0 += w4;
  /* #138: @4 = 0.05 */
  w4 = 5.0000000000000003e-02;
  /* #139: @44 = @33[3:6] */
  for (rr=w44, ss=w33+3; ss!=w33+6; ss+=1) *rr++ = *ss;
  /* #140: @5 = dot(@30, @44) */
  w5 = casadi_dot(3, w30, w44);
  /* #141: @4 = (@4*@5) */
  w4 *= w5;
  /* #142: @0 = (@0-@4) */
  w0 -= w4;
  /* #143: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #144: @40 = @40' */
  /* #145: @46 = zeros(1x4) */
  casadi_clear(w46, 4);
  /* #146: @39 = @39' */
  /* #147: @48 = @47' */
  for (i=0, rr=w48, cs=w47; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #148: @46 = mac(@39,@48,@46) */
  for (i=0, rr=w46; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w39+j, tt=w48+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #149: @46 = @46' */
  /* #150: @40 = (@40+@46) */
  for (i=0, rr=w40, cs=w46; i<4; ++i) (*rr++) += (*cs++);
  /* #151: {@0, @4, @5, @13} = vertsplit(@40) */
  w0 = w40[0];
  w4 = w40[1];
  w5 = w40[2];
  w13 = w40[3];
  /* #152: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #153: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #154: output[1][2] = @5 */
  if (res[1]) res[1][2] = w5;
  /* #155: output[1][3] = @13 */
  if (res[1]) res[1][3] = w13;
  /* #156: @33 = zeros(13x1) */
  casadi_clear(w33, 13);
  /* #157: @13 = -0.05 */
  w13 = -5.0000000000000003e-02;
  /* #158: @44 = (@13*@30) */
  for (i=0, rr=w44, cs=w30; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #159: (@33[3:6] += @44) */
  for (rr=w33+3, ss=w44; rr!=w33+6; rr+=1) *rr += *ss++;
  /* #160: @37 = (@37/@10) */
  for (i=0, rr=w37; i<4; ++i) (*rr++) /= w10;
  /* #161: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<4; ++i) *rr++ = (- *cs++ );
  /* #162: @13 = 1 */
  w13 = 1.;
  /* #163: @14 = (@14?@13:0) */
  w14  = (w14?w13:0);
  /* #164: @40 = zeros(4x1) */
  casadi_clear(w40, 4);
  /* #165: @13 = sq(@16) */
  w13 = casadi_sq( w16 );
  /* #166: @5 = sq(@17) */
  w5 = casadi_sq( w17 );
  /* #167: @13 = (@13+@5) */
  w13 += w5;
  /* #168: @5 = (@16/@13) */
  w5  = (w16/w13);
  /* #169: @35 = @35' */
  /* #170: @44 = zeros(1x3) */
  casadi_clear(w44, 3);
  /* #171: @49 = @43' */
  casadi_copy(w43, 3, w49);
  /* #172: @50 = @45' */
  for (i=0, rr=w50, cs=w45; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #173: @44 = mac(@49,@50,@44) */
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w49+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #174: @44 = @44' */
  /* #175: @35 = (@35+@44) */
  for (i=0, rr=w35, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #176: @44 = (@35/@16) */
  for (i=0, rr=w44, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #177: @4 = dot(@42, @44) */
  w4 = casadi_dot(3, w42, w44);
  /* #178: @5 = (@5*@4) */
  w5 *= w4;
  /* #179: @5 = (-@5) */
  w5 = (- w5 );
  /* #180: (@40[0] += @5) */
  for (rr=w40+0, ss=(&w5); rr!=w40+1; rr+=1) *rr += *ss++;
  /* #181: @43 = (@43/@16) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) /= w16;
  /* #182: @43 = (-@43) */
  for (i=0, rr=w43, cs=w43; i<3; ++i) *rr++ = (- *cs++ );
  /* #183: @5 = dot(@43, @35) */
  w5 = casadi_dot(3, w43, w35);
  /* #184: @17 = (@17/@13) */
  w17 /= w13;
  /* #185: @17 = (@17*@4) */
  w17 *= w4;
  /* #186: @5 = (@5+@17) */
  w5 += w17;
  /* #187: @5 = (@5/@16) */
  w5 /= w16;
  /* #188: @41 = (@5*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #189: @44 = (@11*@44) */
  for (i=0, rr=w44, cs=w44; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #190: @44 = (2.*@44) */
  for (i=0, rr=w44, cs=w44; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #191: @41 = (@41+@44) */
  for (i=0, rr=w41, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #192: (@40[1:4] += @41) */
  for (rr=w40+1, ss=w41; rr!=w40+4; rr+=1) *rr += *ss++;
  /* #193: @46 = (@14*@40) */
  for (i=0, rr=w46, cs=w40; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #194: @14 = 1 */
  w14 = 1.;
  /* #195: @15 = (@15?@14:0) */
  w15  = (w15?w14:0);
  /* #196: @40 = (@15*@40) */
  for (i=0, rr=w40, cs=w40; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #197: @46 = (@46-@40) */
  for (i=0, rr=w46, cs=w40; i<4; ++i) (*rr++) -= (*cs++);
  /* #198: {@15, @14, @11, @5} = vertsplit(@46) */
  w15 = w46[0];
  w14 = w46[1];
  w11 = w46[2];
  w5 = w46[3];
  /* #199: @16 = (@9*@5) */
  w16  = (w9*w5);
  /* #200: @17 = (@8*@11) */
  w17  = (w8*w11);
  /* #201: @16 = (@16+@17) */
  w16 += w17;
  /* #202: @17 = (@7*@14) */
  w17  = (w7*w14);
  /* #203: @16 = (@16+@17) */
  w16 += w17;
  /* #204: @17 = (@6*@15) */
  w17  = (w6*w15);
  /* #205: @16 = (@16+@17) */
  w16 += w17;
  /* #206: @17 = (@8*@5) */
  w17  = (w8*w5);
  /* #207: @4 = (@9*@11) */
  w4  = (w9*w11);
  /* #208: @17 = (@17-@4) */
  w17 -= w4;
  /* #209: @4 = (@6*@14) */
  w4  = (w6*w14);
  /* #210: @17 = (@17+@4) */
  w17 += w4;
  /* #211: @4 = (@7*@15) */
  w4  = (w7*w15);
  /* #212: @17 = (@17-@4) */
  w17 -= w4;
  /* #213: @4 = (@6*@11) */
  w4  = (w6*w11);
  /* #214: @13 = (@7*@5) */
  w13  = (w7*w5);
  /* #215: @4 = (@4-@13) */
  w4 -= w13;
  /* #216: @13 = (@9*@14) */
  w13  = (w9*w14);
  /* #217: @4 = (@4+@13) */
  w4 += w13;
  /* #218: @13 = (@8*@15) */
  w13  = (w8*w15);
  /* #219: @4 = (@4-@13) */
  w4 -= w13;
  /* #220: @6 = (@6*@5) */
  w6 *= w5;
  /* #221: @7 = (@7*@11) */
  w7 *= w11;
  /* #222: @6 = (@6+@7) */
  w6 += w7;
  /* #223: @8 = (@8*@14) */
  w8 *= w14;
  /* #224: @6 = (@6-@8) */
  w6 -= w8;
  /* #225: @9 = (@9*@15) */
  w9 *= w15;
  /* #226: @6 = (@6-@9) */
  w6 -= w9;
  /* #227: @46 = vertcat(@16, @17, @4, @6) */
  rr=w46;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w4;
  *rr++ = w6;
  /* #228: @16 = dot(@37, @46) */
  w16 = casadi_dot(4, w37, w46);
  /* #229: @16 = (@16/@10) */
  w16 /= w10;
  /* #230: @38 = (@16*@38) */
  for (i=0, rr=w38, cs=w38; i<4; ++i) (*rr++)  = (w16*(*cs++));
  /* #231: (@33[6:10] += @38) */
  for (rr=w33+6, ss=w38; rr!=w33+10; rr+=1) *rr += *ss++;
  /* #232: @34 = @34' */
  /* #233: @41 = zeros(1x3) */
  casadi_clear(w41, 3);
  /* #234: @31 = @31' */
  /* #235: @50 = @36' */
  for (i=0, rr=w50, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #236: @41 = mac(@31,@50,@41) */
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #237: @41 = @41' */
  /* #238: @34 = (@34+@41) */
  for (i=0, rr=w34, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #239: @16 = dot(@30, @34) */
  w16 = casadi_dot(3, w30, w34);
  /* #240: @30 = (@16*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w16*(*cs++));
  /* #241: @34 = zeros(3x1) */
  casadi_clear(w34, 3);
  /* #242: @50 = @3' */
  for (i=0, rr=w50, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #243: @1 = @1' */
  /* #244: @41 = zeros(1x3) */
  casadi_clear(w41, 3);
  /* #245: @2 = @2' */
  /* #246: @3 = @32' */
  for (i=0, rr=w3, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #247: @41 = mac(@2,@3,@41) */
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #248: @41 = @41' */
  /* #249: @1 = (@1+@41) */
  for (i=0, rr=w1, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #250: @34 = mac(@50,@1,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w50+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #251: @30 = (@30+@34) */
  for (i=0, rr=w30, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #252: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #253: (@33[:3] += @30) */
  for (rr=w33+0, ss=w30; rr!=w33+3; rr+=1) *rr += *ss++;
  /* #254: {@16, @17, @4, @6, @9, @15, @8, @14, @7, @11, @5, @13, @0} = vertsplit(@33) */
  w16 = w33[0];
  w17 = w33[1];
  w4 = w33[2];
  w6 = w33[3];
  w9 = w33[4];
  w15 = w33[5];
  w8 = w33[6];
  w14 = w33[7];
  w7 = w33[8];
  w11 = w33[9];
  w5 = w33[10];
  w13 = w33[11];
  w0 = w33[12];
  /* #255: output[1][4] = @16 */
  if (res[1]) res[1][4] = w16;
  /* #256: output[1][5] = @17 */
  if (res[1]) res[1][5] = w17;
  /* #257: output[1][6] = @4 */
  if (res[1]) res[1][6] = w4;
  /* #258: output[1][7] = @6 */
  if (res[1]) res[1][7] = w6;
  /* #259: output[1][8] = @9 */
  if (res[1]) res[1][8] = w9;
  /* #260: output[1][9] = @15 */
  if (res[1]) res[1][9] = w15;
  /* #261: @46 = (@46/@10) */
  for (i=0, rr=w46; i<4; ++i) (*rr++) /= w10;
  /* #262: {@10, @15, @9, @6} = vertsplit(@46) */
  w10 = w46[0];
  w15 = w46[1];
  w9 = w46[2];
  w6 = w46[3];
  /* #263: @10 = (@10+@8) */
  w10 += w8;
  /* #264: output[1][10] = @10 */
  if (res[1]) res[1][10] = w10;
  /* #265: @14 = (@14-@15) */
  w14 -= w15;
  /* #266: output[1][11] = @14 */
  if (res[1]) res[1][11] = w14;
  /* #267: @7 = (@7-@9) */
  w7 -= w9;
  /* #268: output[1][12] = @7 */
  if (res[1]) res[1][12] = w7;
  /* #269: @11 = (@11-@6) */
  w11 -= w6;
  /* #270: output[1][13] = @11 */
  if (res[1]) res[1][13] = w11;
  /* #271: output[1][14] = @5 */
  if (res[1]) res[1][14] = w5;
  /* #272: output[1][15] = @13 */
  if (res[1]) res[1][15] = w13;
  /* #273: output[1][16] = @0 */
  if (res[1]) res[1][16] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_0_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_0_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_0_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 28;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 196;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
