/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s2[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s3[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[3] = {0, 0, 0};
static const casadi_int casadi_s5[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 0., 1.};
static const casadi_real casadi_c2[3] = {3.2723905139943781e+02, 6.2619368170575160e+02, 6.2622505275946071e+02};
static const casadi_real casadi_c3[9] = {3.0558700000000000e-03, 0., 0., 0., 1.5969500000000000e-03, 0., 0., 0., 1.5968700000000000e-03};

/* Drone_ode_complete_impl_dae_fun:(i0[13],i1[13],i2[4],i3[],i4[24])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+16, *w14=w+29, *w15=w+32, *w16=w+41, *w17=w+50, *w18=w+59, *w19=w+63, *w20=w+72, w21, w22, *w23=w+77, *w24=w+80, *w25=w+83, *w26=w+86, *w27=w+89;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w6 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w7 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = input[1][8] */
  w8 = arg[1] ? arg[1][8] : 0;
  /* #9: @9 = input[1][9] */
  w9 = arg[1] ? arg[1][9] : 0;
  /* #10: @10 = input[1][10] */
  w10 = arg[1] ? arg[1][10] : 0;
  /* #11: @11 = input[1][11] */
  w11 = arg[1] ? arg[1][11] : 0;
  /* #12: @12 = input[1][12] */
  w12 = arg[1] ? arg[1][12] : 0;
  /* #13: @13 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w13;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #15: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #16: @2 = input[0][5] */
  w2 = arg[0] ? arg[0][5] : 0;
  /* #17: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #18: @15 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w15);
  /* #19: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #20: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #21: @3 = input[0][6] */
  w3 = arg[0] ? arg[0][6] : 0;
  /* #22: @4 = input[0][7] */
  w4 = arg[0] ? arg[0][7] : 0;
  /* #23: @5 = input[0][8] */
  w5 = arg[0] ? arg[0][8] : 0;
  /* #24: @6 = input[0][9] */
  w6 = arg[0] ? arg[0][9] : 0;
  /* #25: @18 = vertcat(@3, @4, @5, @6) */
  rr=w18;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #26: @7 = ||@18||_F */
  w7 = sqrt(casadi_dot(4, w18, w18));
  /* #27: @18 = (@18/@7) */
  for (i=0, rr=w18; i<4; ++i) (*rr++) /= w7;
  /* #28: @7 = @18[3] */
  for (rr=(&w7), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #29: @7 = (-@7) */
  w7 = (- w7 );
  /* #30: (@17[3] = @7) */
  for (rr=w17+3, ss=(&w7); rr!=w17+4; rr+=1) *rr = *ss++;
  /* #31: @7 = @18[2] */
  for (rr=(&w7), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #32: (@17[6] = @7) */
  for (rr=w17+6, ss=(&w7); rr!=w17+7; rr+=1) *rr = *ss++;
  /* #33: @7 = @18[1] */
  for (rr=(&w7), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #34: @7 = (-@7) */
  w7 = (- w7 );
  /* #35: (@17[7] = @7) */
  for (rr=w17+7, ss=(&w7); rr!=w17+8; rr+=1) *rr = *ss++;
  /* #36: @7 = @18[3] */
  for (rr=(&w7), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #37: (@17[1] = @7) */
  for (rr=w17+1, ss=(&w7); rr!=w17+2; rr+=1) *rr = *ss++;
  /* #38: @7 = @18[2] */
  for (rr=(&w7), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #39: @7 = (-@7) */
  w7 = (- w7 );
  /* #40: (@17[2] = @7) */
  for (rr=w17+2, ss=(&w7); rr!=w17+3; rr+=1) *rr = *ss++;
  /* #41: @7 = @18[1] */
  for (rr=(&w7), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #42: (@17[5] = @7) */
  for (rr=w17+5, ss=(&w7); rr!=w17+6; rr+=1) *rr = *ss++;
  /* #43: @19 = (2.*@17) */
  for (i=0, rr=w19, cs=w17; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #44: @16 = mac(@19,@17,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #45: @15 = (@15+@16) */
  for (i=0, rr=w15, cs=w16; i<9; ++i) (*rr++) += (*cs++);
  /* #46: @7 = @18[0] */
  for (rr=(&w7), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #47: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #48: @17 = (@7*@17) */
  for (i=0, rr=w17, cs=w17; i<9; ++i) (*rr++)  = (w7*(*cs++));
  /* #49: @15 = (@15+@17) */
  for (i=0, rr=w15, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #50: @7 = 0 */
  w7 = 0.;
  /* #51: @8 = 0 */
  w8 = 0.;
  /* #52: @9 = input[2][0] */
  w9 = arg[2] ? arg[2][0] : 0;
  /* #53: @20 = vertcat(@7, @8, @9) */
  rr=w20;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #54: @14 = mac(@15,@20,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #55: @7 = 0.85 */
  w7 = 8.4999999999999998e-01;
  /* #56: @14 = (@14/@7) */
  for (i=0, rr=w14; i<3; ++i) (*rr++) /= w7;
  /* #57: @20 = [0, 0, 1] */
  casadi_copy(casadi_c1, 3, w20);
  /* #58: @7 = 9.81 */
  w7 = 9.8100000000000005e+00;
  /* #59: @20 = (@20*@7) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w7;
  /* #60: @14 = (@14-@20) */
  for (i=0, rr=w14, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #61: @7 = 0.5 */
  w7 = 5.0000000000000000e-01;
  /* #62: @8 = input[0][10] */
  w8 = arg[0] ? arg[0][10] : 0;
  /* #63: @9 = (@4*@8) */
  w9  = (w4*w8);
  /* #64: @9 = (-@9) */
  w9 = (- w9 );
  /* #65: @10 = input[0][11] */
  w10 = arg[0] ? arg[0][11] : 0;
  /* #66: @11 = (@5*@10) */
  w11  = (w5*w10);
  /* #67: @9 = (@9-@11) */
  w9 -= w11;
  /* #68: @11 = input[0][12] */
  w11 = arg[0] ? arg[0][12] : 0;
  /* #69: @12 = (@6*@11) */
  w12  = (w6*w11);
  /* #70: @9 = (@9-@12) */
  w9 -= w12;
  /* #71: @12 = (@3*@8) */
  w12  = (w3*w8);
  /* #72: @21 = (@5*@11) */
  w21  = (w5*w11);
  /* #73: @12 = (@12+@21) */
  w12 += w21;
  /* #74: @21 = (@6*@10) */
  w21  = (w6*w10);
  /* #75: @12 = (@12-@21) */
  w12 -= w21;
  /* #76: @21 = (@3*@10) */
  w21  = (w3*w10);
  /* #77: @22 = (@4*@11) */
  w22  = (w4*w11);
  /* #78: @21 = (@21-@22) */
  w21 -= w22;
  /* #79: @6 = (@6*@8) */
  w6 *= w8;
  /* #80: @21 = (@21+@6) */
  w21 += w6;
  /* #81: @3 = (@3*@11) */
  w3 *= w11;
  /* #82: @4 = (@4*@10) */
  w4 *= w10;
  /* #83: @3 = (@3+@4) */
  w3 += w4;
  /* #84: @5 = (@5*@8) */
  w5 *= w8;
  /* #85: @3 = (@3-@5) */
  w3 -= w5;
  /* #86: @18 = vertcat(@9, @12, @21, @3) */
  rr=w18;
  *rr++ = w9;
  *rr++ = w12;
  *rr++ = w21;
  *rr++ = w3;
  /* #87: @18 = (@7*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w7*(*cs++));
  /* #88: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #89: @23 = 
  [[327.239, 00, 00], 
   [00, 626.194, 00], 
   [00, 00, 626.225]] */
  casadi_copy(casadi_c2, 3, w23);
  /* #90: @7 = input[2][1] */
  w7 = arg[2] ? arg[2][1] : 0;
  /* #91: @9 = input[2][2] */
  w9 = arg[2] ? arg[2][2] : 0;
  /* #92: @12 = input[2][3] */
  w12 = arg[2] ? arg[2][3] : 0;
  /* #93: @24 = vertcat(@7, @9, @12) */
  rr=w24;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w12;
  /* #94: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #95: @15 = 
  [[0.00305587, 0, 0], 
   [0, 0.00159695, 0], 
   [0, 0, 0.00159687]] */
  casadi_copy(casadi_c3, 9, w15);
  /* #96: @26 = vertcat(@8, @10, @11) */
  rr=w26;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w11;
  /* #97: @25 = mac(@15,@26,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #98: @7 = @25[2] */
  for (rr=(&w7), ss=w25+2; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #99: @9 = (@10*@7) */
  w9  = (w10*w7);
  /* #100: @12 = @25[1] */
  for (rr=(&w12), ss=w25+1; ss!=w25+2; ss+=1) *rr++ = *ss;
  /* #101: @21 = (@11*@12) */
  w21  = (w11*w12);
  /* #102: @9 = (@9-@21) */
  w9 -= w21;
  /* #103: @21 = @25[0] */
  for (rr=(&w21), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  /* #104: @11 = (@11*@21) */
  w11 *= w21;
  /* #105: @7 = (@8*@7) */
  w7  = (w8*w7);
  /* #106: @11 = (@11-@7) */
  w11 -= w7;
  /* #107: @8 = (@8*@12) */
  w8 *= w12;
  /* #108: @10 = (@10*@21) */
  w10 *= w21;
  /* #109: @8 = (@8-@10) */
  w8 -= w10;
  /* #110: @25 = vertcat(@9, @11, @8) */
  rr=w25;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w8;
  /* #111: @24 = (@24-@25) */
  for (i=0, rr=w24, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #112: @20 = mac(@23,@24,@20) */
  casadi_mtimes(w23, casadi_s1, w24, casadi_s0, w20, casadi_s0, w, 0);
  /* #113: @27 = vertcat(@0, @1, @2, @14, @18, @20) */
  rr=w27;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #114: @13 = (@13-@27) */
  for (i=0, rr=w13, cs=w27; i<13; ++i) (*rr++) -= (*cs++);
  /* #115: output[0][0] = @13 */
  casadi_copy(w13, 13, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_impl_dae_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_impl_dae_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_impl_dae_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_impl_dae_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 102;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
