/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s2[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s3[9] = {0, 1, 2, 3, 7, 11, 21, 27, 33};
static const casadi_int casadi_s4[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s5[6] = {4, 8, 12, 15, 28, 34};
static const casadi_int casadi_s6[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s7[6] = {5, 9, 13, 16, 22, 35};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s9[6] = {6, 10, 14, 17, 23, 29};
static const casadi_int casadi_s10[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s11[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s12[7] = {18, 24, 30, 36, 39, 42, 45};
static const casadi_int casadi_s13[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s14[7] = {19, 25, 31, 37, 40, 43, 46};
static const casadi_int casadi_s15[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s16[7] = {20, 26, 32, 38, 41, 44, 47};
static const casadi_int casadi_s17[64] = {13, 13, 0, 0, 0, 0, 1, 2, 3, 9, 15, 21, 27, 34, 41, 48, 0, 1, 2, 3, 4, 5, 7, 8, 9, 3, 4, 5, 6, 8, 9, 3, 4, 5, 6, 7, 9, 3, 4, 5, 6, 7, 8, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s18[64] = {13, 13, 0, 1, 2, 3, 7, 11, 15, 21, 27, 33, 39, 42, 45, 48, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 7, 8, 9, 10, 11, 12, 6, 8, 9, 10, 11, 12, 6, 7, 9, 10, 11, 12, 6, 7, 8, 10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11, 12};
static const casadi_int casadi_s19[29] = {13, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s20[13] = {13, 4, 0, 3, 4, 5, 6, 3, 4, 5, 10, 11, 12};
static const casadi_int casadi_s21[22] = {4, 13, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 4, 5, 6, 0, 0, 0, 1, 2, 3};
static const casadi_int casadi_s22[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s23[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s24[3] = {0, 0, 0};
static const casadi_int casadi_s25[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s26[3] = {13, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 0., 1.};
static const casadi_real casadi_c2[3] = {3.2723905139943781e+02, 6.2619368170575160e+02, 6.2622505275946071e+02};
static const casadi_real casadi_c3[9] = {3.0558700000000000e-03, 0., 0., 0., 1.5969500000000000e-03, 0., 0., 0., 1.5968700000000000e-03};

/* Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z:(i0[13],i1[13],i2[4],i3[],i4[24])->(o0[13],o1[13x13,48nz],o2[13x13,13nz],o3[13x4,6nz],o4[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+16, *w14=w+29, *w15=w+32, *w16=w+41, *w17=w+50, *w18=w+59, *w19=w+63, *w20=w+67, *w21=w+76, *w22=w+79, w23, w24, w25, w26, w27, *w28=w+87, *w29=w+91, *w30=w+94, *w31=w+97, *w32=w+100, w33, w34, *w35=w+105, *w36=w+118, *w37=w+166, *w38=w+173, *w39=w+182, w43, *w44=w+192, *w45=w+196, *w46=w+205, *w50=w+214, *w51=w+220, *w52=w+226, *w53=w+233, *w54=w+281;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w6 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w7 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = input[1][8] */
  w8 = arg[1] ? arg[1][8] : 0;
  /* #9: @9 = input[1][9] */
  w9 = arg[1] ? arg[1][9] : 0;
  /* #10: @10 = input[1][10] */
  w10 = arg[1] ? arg[1][10] : 0;
  /* #11: @11 = input[1][11] */
  w11 = arg[1] ? arg[1][11] : 0;
  /* #12: @12 = input[1][12] */
  w12 = arg[1] ? arg[1][12] : 0;
  /* #13: @13 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w13;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #15: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #16: @2 = input[0][5] */
  w2 = arg[0] ? arg[0][5] : 0;
  /* #17: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #18: @15 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w15);
  /* #19: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #20: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #21: @3 = input[0][6] */
  w3 = arg[0] ? arg[0][6] : 0;
  /* #22: @4 = input[0][7] */
  w4 = arg[0] ? arg[0][7] : 0;
  /* #23: @5 = input[0][8] */
  w5 = arg[0] ? arg[0][8] : 0;
  /* #24: @6 = input[0][9] */
  w6 = arg[0] ? arg[0][9] : 0;
  /* #25: @18 = vertcat(@3, @4, @5, @6) */
  rr=w18;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #26: @7 = ||@18||_F */
  w7 = sqrt(casadi_dot(4, w18, w18));
  /* #27: @19 = (@18/@7) */
  for (i=0, rr=w19, cr=w18; i<4; ++i) (*rr++)  = ((*cr++)/w7);
  /* #28: @8 = @19[3] */
  for (rr=(&w8), ss=w19+3; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #29: @8 = (-@8) */
  w8 = (- w8 );
  /* #30: (@17[3] = @8) */
  for (rr=w17+3, ss=(&w8); rr!=w17+4; rr+=1) *rr = *ss++;
  /* #31: @8 = @19[2] */
  for (rr=(&w8), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #32: (@17[6] = @8) */
  for (rr=w17+6, ss=(&w8); rr!=w17+7; rr+=1) *rr = *ss++;
  /* #33: @8 = @19[1] */
  for (rr=(&w8), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #34: @8 = (-@8) */
  w8 = (- w8 );
  /* #35: (@17[7] = @8) */
  for (rr=w17+7, ss=(&w8); rr!=w17+8; rr+=1) *rr = *ss++;
  /* #36: @8 = @19[3] */
  for (rr=(&w8), ss=w19+3; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #37: (@17[1] = @8) */
  for (rr=w17+1, ss=(&w8); rr!=w17+2; rr+=1) *rr = *ss++;
  /* #38: @8 = @19[2] */
  for (rr=(&w8), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #39: @8 = (-@8) */
  w8 = (- w8 );
  /* #40: (@17[2] = @8) */
  for (rr=w17+2, ss=(&w8); rr!=w17+3; rr+=1) *rr = *ss++;
  /* #41: @8 = @19[1] */
  for (rr=(&w8), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #42: (@17[5] = @8) */
  for (rr=w17+5, ss=(&w8); rr!=w17+6; rr+=1) *rr = *ss++;
  /* #43: @20 = (2.*@17) */
  for (i=0, rr=w20, cs=w17; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #44: @16 = mac(@20,@17,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #45: @15 = (@15+@16) */
  for (i=0, rr=w15, cs=w16; i<9; ++i) (*rr++) += (*cs++);
  /* #46: @8 = @19[0] */
  for (rr=(&w8), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #47: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #48: @16 = (@8*@17) */
  for (i=0, rr=w16, cs=w17; i<9; ++i) (*rr++)  = (w8*(*cs++));
  /* #49: @15 = (@15+@16) */
  for (i=0, rr=w15, cs=w16; i<9; ++i) (*rr++) += (*cs++);
  /* #50: @9 = 0 */
  w9 = 0.;
  /* #51: @10 = 0 */
  w10 = 0.;
  /* #52: @11 = input[2][0] */
  w11 = arg[2] ? arg[2][0] : 0;
  /* #53: @21 = vertcat(@9, @10, @11) */
  rr=w21;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #54: @14 = mac(@15,@21,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #55: @9 = 0.85 */
  w9 = 8.4999999999999998e-01;
  /* #56: @14 = (@14/@9) */
  for (i=0, rr=w14; i<3; ++i) (*rr++) /= w9;
  /* #57: @22 = [0, 0, 1] */
  casadi_copy(casadi_c1, 3, w22);
  /* #58: @9 = 9.81 */
  w9 = 9.8100000000000005e+00;
  /* #59: @22 = (@22*@9) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) *= w9;
  /* #60: @14 = (@14-@22) */
  for (i=0, rr=w14, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #61: @9 = 0.5 */
  w9 = 5.0000000000000000e-01;
  /* #62: @10 = input[0][10] */
  w10 = arg[0] ? arg[0][10] : 0;
  /* #63: @11 = (@4*@10) */
  w11  = (w4*w10);
  /* #64: @11 = (-@11) */
  w11 = (- w11 );
  /* #65: @12 = input[0][11] */
  w12 = arg[0] ? arg[0][11] : 0;
  /* #66: @23 = (@5*@12) */
  w23  = (w5*w12);
  /* #67: @11 = (@11-@23) */
  w11 -= w23;
  /* #68: @23 = input[0][12] */
  w23 = arg[0] ? arg[0][12] : 0;
  /* #69: @24 = (@6*@23) */
  w24  = (w6*w23);
  /* #70: @11 = (@11-@24) */
  w11 -= w24;
  /* #71: @24 = (@3*@10) */
  w24  = (w3*w10);
  /* #72: @25 = (@5*@23) */
  w25  = (w5*w23);
  /* #73: @24 = (@24+@25) */
  w24 += w25;
  /* #74: @25 = (@6*@12) */
  w25  = (w6*w12);
  /* #75: @24 = (@24-@25) */
  w24 -= w25;
  /* #76: @25 = (@3*@12) */
  w25  = (w3*w12);
  /* #77: @26 = (@4*@23) */
  w26  = (w4*w23);
  /* #78: @25 = (@25-@26) */
  w25 -= w26;
  /* #79: @26 = (@6*@10) */
  w26  = (w6*w10);
  /* #80: @25 = (@25+@26) */
  w25 += w26;
  /* #81: @26 = (@3*@23) */
  w26  = (w3*w23);
  /* #82: @27 = (@4*@12) */
  w27  = (w4*w12);
  /* #83: @26 = (@26+@27) */
  w26 += w27;
  /* #84: @27 = (@5*@10) */
  w27  = (w5*w10);
  /* #85: @26 = (@26-@27) */
  w26 -= w27;
  /* #86: @28 = vertcat(@11, @24, @25, @26) */
  rr=w28;
  *rr++ = w11;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  /* #87: @28 = (@9*@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #88: @22 = zeros(3x1) */
  casadi_clear(w22, 3);
  /* #89: @29 = 
  [[327.239, 00, 00], 
   [00, 626.194, 00], 
   [00, 00, 626.225]] */
  casadi_copy(casadi_c2, 3, w29);
  /* #90: @11 = input[2][1] */
  w11 = arg[2] ? arg[2][1] : 0;
  /* #91: @24 = input[2][2] */
  w24 = arg[2] ? arg[2][2] : 0;
  /* #92: @25 = input[2][3] */
  w25 = arg[2] ? arg[2][3] : 0;
  /* #93: @30 = vertcat(@11, @24, @25) */
  rr=w30;
  *rr++ = w11;
  *rr++ = w24;
  *rr++ = w25;
  /* #94: @31 = zeros(3x1) */
  casadi_clear(w31, 3);
  /* #95: @16 = 
  [[0.00305587, 0, 0], 
   [0, 0.00159695, 0], 
   [0, 0, 0.00159687]] */
  casadi_copy(casadi_c3, 9, w16);
  /* #96: @32 = vertcat(@10, @12, @23) */
  rr=w32;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w23;
  /* #97: @31 = mac(@16,@32,@31) */
  for (i=0, rr=w31; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #98: @11 = @31[2] */
  for (rr=(&w11), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #99: @24 = (@12*@11) */
  w24  = (w12*w11);
  /* #100: @25 = @31[1] */
  for (rr=(&w25), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #101: @26 = (@23*@25) */
  w26  = (w23*w25);
  /* #102: @24 = (@24-@26) */
  w24 -= w26;
  /* #103: @26 = @31[0] */
  for (rr=(&w26), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #104: @27 = (@23*@26) */
  w27  = (w23*w26);
  /* #105: @33 = (@10*@11) */
  w33  = (w10*w11);
  /* #106: @27 = (@27-@33) */
  w27 -= w33;
  /* #107: @33 = (@10*@25) */
  w33  = (w10*w25);
  /* #108: @34 = (@12*@26) */
  w34  = (w12*w26);
  /* #109: @33 = (@33-@34) */
  w33 -= w34;
  /* #110: @31 = vertcat(@24, @27, @33) */
  rr=w31;
  *rr++ = w24;
  *rr++ = w27;
  *rr++ = w33;
  /* #111: @30 = (@30-@31) */
  for (i=0, rr=w30, cs=w31; i<3; ++i) (*rr++) -= (*cs++);
  /* #112: @22 = mac(@29,@30,@22) */
  casadi_mtimes(w29, casadi_s1, w30, casadi_s0, w22, casadi_s0, w, 0);
  /* #113: @35 = vertcat(@0, @1, @2, @14, @28, @22) */
  rr=w35;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #114: @13 = (@13-@35) */
  for (i=0, rr=w13, cs=w35; i<13; ++i) (*rr++) -= (*cs++);
  /* #115: output[0][0] = @13 */
  casadi_copy(w13, 13, res[0]);
  /* #116: @36 = zeros(13x13,48nz) */
  casadi_clear(w36, 48);
  /* #117: @37 = ones(13x1,7nz) */
  casadi_fill(w37, 7, 1.);
  /* #118: {NULL, NULL, NULL, @0, @1, @2, @24, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@37) */
  w0 = w37[3];
  w1 = w37[4];
  w2 = w37[5];
  w24 = w37[6];
  /* #119: @27 = 1.17647 */
  w27 = 1.1764705882352942e+00;
  /* #120: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #121: @38 = zeros(3x3) */
  casadi_clear(w38, 9);
  /* #122: @39 = zeros(3x3) */
  casadi_clear(w39, 9);
  /* #123: @40 = 00 */
  /* #124: @41 = 00 */
  /* #125: @42 = 00 */
  /* #126: @33 = vertcat(@24, @40, @41, @42) */
  rr=(&w33);
  *rr++ = w24;
  /* #127: @34 = (@33/@7) */
  w34  = (w33/w7);
  /* #128: @28 = dense(@34) */
  casadi_densify((&w34), casadi_s2, w28, 0);
  /* #129: @19 = (@19/@7) */
  for (i=0, rr=w19; i<4; ++i) (*rr++) /= w7;
  /* #130: @34 = project(@18) */
  casadi_sparsify(w18, (&w34), casadi_s2, 0);
  /* #131: @43 = dot(@34, @33) */
  w43 = casadi_dot(1, (&w34), (&w33));
  /* #132: @43 = (@43/@7) */
  w43 /= w7;
  /* #133: @44 = (@19*@43) */
  for (i=0, rr=w44, cr=w19; i<4; ++i) (*rr++)  = ((*cr++)*w43);
  /* #134: @28 = (@28-@44) */
  for (i=0, rr=w28, cs=w44; i<4; ++i) (*rr++) -= (*cs++);
  /* #135: @43 = @28[3] */
  for (rr=(&w43), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #136: @43 = (-@43) */
  w43 = (- w43 );
  /* #137: (@39[3] += @43) */
  for (rr=w39+3, ss=(&w43); rr!=w39+4; rr+=1) *rr += *ss++;
  /* #138: @43 = 0 */
  w43 = 0.;
  /* #139: (@39[6] = @43) */
  for (rr=w39+6, ss=(&w43); rr!=w39+7; rr+=1) *rr = *ss++;
  /* #140: @43 = @28[2] */
  for (rr=(&w43), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #141: (@39[6] += @43) */
  for (rr=w39+6, ss=(&w43); rr!=w39+7; rr+=1) *rr += *ss++;
  /* #142: @43 = 0 */
  w43 = 0.;
  /* #143: (@39[7] = @43) */
  for (rr=w39+7, ss=(&w43); rr!=w39+8; rr+=1) *rr = *ss++;
  /* #144: @43 = @28[1] */
  for (rr=(&w43), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #145: @43 = (-@43) */
  w43 = (- w43 );
  /* #146: (@39[7] += @43) */
  for (rr=w39+7, ss=(&w43); rr!=w39+8; rr+=1) *rr += *ss++;
  /* #147: @43 = 0 */
  w43 = 0.;
  /* #148: (@39[1] = @43) */
  for (rr=w39+1, ss=(&w43); rr!=w39+2; rr+=1) *rr = *ss++;
  /* #149: @43 = @28[3] */
  for (rr=(&w43), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #150: (@39[1] += @43) */
  for (rr=w39+1, ss=(&w43); rr!=w39+2; rr+=1) *rr += *ss++;
  /* #151: @43 = 0 */
  w43 = 0.;
  /* #152: (@39[2] = @43) */
  for (rr=w39+2, ss=(&w43); rr!=w39+3; rr+=1) *rr = *ss++;
  /* #153: @43 = @28[2] */
  for (rr=(&w43), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #154: @43 = (-@43) */
  w43 = (- w43 );
  /* #155: (@39[2] += @43) */
  for (rr=w39+2, ss=(&w43); rr!=w39+3; rr+=1) *rr += *ss++;
  /* #156: @43 = 0 */
  w43 = 0.;
  /* #157: (@39[5] = @43) */
  for (rr=w39+5, ss=(&w43); rr!=w39+6; rr+=1) *rr = *ss++;
  /* #158: @43 = @28[1] */
  for (rr=(&w43), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #159: (@39[5] += @43) */
  for (rr=w39+5, ss=(&w43); rr!=w39+6; rr+=1) *rr += *ss++;
  /* #160: @38 = mac(@20,@39,@38) */
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #161: @45 = zeros(3x3) */
  casadi_clear(w45, 9);
  /* #162: @46 = (2.*@39) */
  for (i=0, rr=w46, cs=w39; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #163: @45 = mac(@46,@17,@45) */
  for (i=0, rr=w45; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w46+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #164: @38 = (@38+@45) */
  for (i=0, rr=w38, cs=w45; i<9; ++i) (*rr++) += (*cs++);
  /* #165: @43 = @28[0] */
  for (rr=(&w43), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #166: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #167: @45 = (@17*@43) */
  for (i=0, rr=w45, cr=w17; i<9; ++i) (*rr++)  = ((*cr++)*w43);
  /* #168: @39 = (@8*@39) */
  for (i=0, rr=w39, cs=w39; i<9; ++i) (*rr++)  = (w8*(*cs++));
  /* #169: @45 = (@45+@39) */
  for (i=0, rr=w45, cs=w39; i<9; ++i) (*rr++) += (*cs++);
  /* #170: @38 = (@38+@45) */
  for (i=0, rr=w38, cs=w45; i<9; ++i) (*rr++) += (*cs++);
  /* #171: @14 = mac(@38,@21,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w38+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #172: @14 = (@27*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w27*(*cs++));
  /* #173: @40 = 00 */
  /* #174: @43 = (@10*@24) */
  w43  = (w10*w24);
  /* #175: @34 = (@12*@24) */
  w34  = (w12*w24);
  /* #176: @24 = (@23*@24) */
  w24  = (w23*w24);
  /* #177: @22 = vertcat(@40, @43, @34, @24) */
  rr=w22;
  *rr++ = w43;
  *rr++ = w34;
  *rr++ = w24;
  /* #178: @22 = (@9*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #179: @40 = zeros(3x1,0nz) */
  /* #180: @38 = vertcat(@0, @1, @2, @14, @22, @40) */
  rr=w38;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #181: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<9; ++i) *rr++ = (- *cs++ );
  /* #182: @45 = @38[:9] */
  for (rr=w45, ss=w38+0; ss!=w38+9; ss+=1) *rr++ = *ss;
  /* #183: (@36[0, 1, 2, 3, 7, 11, 21, 27, 33] = @45) */
  for (cii=casadi_s3, rr=w36, ss=w45; cii!=casadi_s3+9; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #184: @40 = 00 */
  /* #185: @41 = 00 */
  /* #186: @42 = 00 */
  /* #187: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #188: @45 = zeros(3x3) */
  casadi_clear(w45, 9);
  /* #189: @38 = zeros(3x3) */
  casadi_clear(w38, 9);
  /* #190: @47 = 00 */
  /* #191: @0 = ones(13x1,1nz) */
  w0 = 1.;
  /* #192: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @1, NULL, NULL, NULL, NULL, NULL} = vertsplit(@0) */
  w1 = w0;
  /* #193: @48 = 00 */
  /* #194: @49 = 00 */
  /* #195: @0 = vertcat(@47, @1, @48, @49) */
  rr=(&w0);
  *rr++ = w1;
  /* #196: @2 = (@0/@7) */
  w2  = (w0/w7);
  /* #197: @28 = dense(@2) */
  casadi_densify((&w2), casadi_s4, w28, 0);
  /* #198: @2 = project(@18) */
  casadi_sparsify(w18, (&w2), casadi_s4, 0);
  /* #199: @43 = dot(@2, @0) */
  w43 = casadi_dot(1, (&w2), (&w0));
  /* #200: @43 = (@43/@7) */
  w43 /= w7;
  /* #201: @44 = (@19*@43) */
  for (i=0, rr=w44, cr=w19; i<4; ++i) (*rr++)  = ((*cr++)*w43);
  /* #202: @28 = (@28-@44) */
  for (i=0, rr=w28, cs=w44; i<4; ++i) (*rr++) -= (*cs++);
  /* #203: @43 = @28[3] */
  for (rr=(&w43), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #204: @43 = (-@43) */
  w43 = (- w43 );
  /* #205: (@38[3] += @43) */
  for (rr=w38+3, ss=(&w43); rr!=w38+4; rr+=1) *rr += *ss++;
  /* #206: @43 = 0 */
  w43 = 0.;
  /* #207: (@38[6] = @43) */
  for (rr=w38+6, ss=(&w43); rr!=w38+7; rr+=1) *rr = *ss++;
  /* #208: @43 = @28[2] */
  for (rr=(&w43), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #209: (@38[6] += @43) */
  for (rr=w38+6, ss=(&w43); rr!=w38+7; rr+=1) *rr += *ss++;
  /* #210: @43 = 0 */
  w43 = 0.;
  /* #211: (@38[7] = @43) */
  for (rr=w38+7, ss=(&w43); rr!=w38+8; rr+=1) *rr = *ss++;
  /* #212: @43 = @28[1] */
  for (rr=(&w43), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #213: @43 = (-@43) */
  w43 = (- w43 );
  /* #214: (@38[7] += @43) */
  for (rr=w38+7, ss=(&w43); rr!=w38+8; rr+=1) *rr += *ss++;
  /* #215: @43 = 0 */
  w43 = 0.;
  /* #216: (@38[1] = @43) */
  for (rr=w38+1, ss=(&w43); rr!=w38+2; rr+=1) *rr = *ss++;
  /* #217: @43 = @28[3] */
  for (rr=(&w43), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #218: (@38[1] += @43) */
  for (rr=w38+1, ss=(&w43); rr!=w38+2; rr+=1) *rr += *ss++;
  /* #219: @43 = 0 */
  w43 = 0.;
  /* #220: (@38[2] = @43) */
  for (rr=w38+2, ss=(&w43); rr!=w38+3; rr+=1) *rr = *ss++;
  /* #221: @43 = @28[2] */
  for (rr=(&w43), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #222: @43 = (-@43) */
  w43 = (- w43 );
  /* #223: (@38[2] += @43) */
  for (rr=w38+2, ss=(&w43); rr!=w38+3; rr+=1) *rr += *ss++;
  /* #224: @43 = 0 */
  w43 = 0.;
  /* #225: (@38[5] = @43) */
  for (rr=w38+5, ss=(&w43); rr!=w38+6; rr+=1) *rr = *ss++;
  /* #226: @43 = @28[1] */
  for (rr=(&w43), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #227: (@38[5] += @43) */
  for (rr=w38+5, ss=(&w43); rr!=w38+6; rr+=1) *rr += *ss++;
  /* #228: @45 = mac(@20,@38,@45) */
  for (i=0, rr=w45; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #229: @39 = zeros(3x3) */
  casadi_clear(w39, 9);
  /* #230: @46 = (2.*@38) */
  for (i=0, rr=w46, cs=w38; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #231: @39 = mac(@46,@17,@39) */
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w46+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #232: @45 = (@45+@39) */
  for (i=0, rr=w45, cs=w39; i<9; ++i) (*rr++) += (*cs++);
  /* #233: @43 = @28[0] */
  for (rr=(&w43), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #234: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #235: @39 = (@17*@43) */
  for (i=0, rr=w39, cr=w17; i<9; ++i) (*rr++)  = ((*cr++)*w43);
  /* #236: @38 = (@8*@38) */
  for (i=0, rr=w38, cs=w38; i<9; ++i) (*rr++)  = (w8*(*cs++));
  /* #237: @39 = (@39+@38) */
  for (i=0, rr=w39, cs=w38; i<9; ++i) (*rr++) += (*cs++);
  /* #238: @45 = (@45+@39) */
  for (i=0, rr=w45, cs=w39; i<9; ++i) (*rr++) += (*cs++);
  /* #239: @14 = mac(@45,@21,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w45+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #240: @14 = (@27*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w27*(*cs++));
  /* #241: @43 = (@10*@1) */
  w43  = (w10*w1);
  /* #242: @43 = (-@43) */
  w43 = (- w43 );
  /* #243: @47 = 00 */
  /* #244: @2 = (@23*@1) */
  w2  = (w23*w1);
  /* #245: @2 = (-@2) */
  w2 = (- w2 );
  /* #246: @1 = (@12*@1) */
  w1  = (w12*w1);
  /* #247: @22 = vertcat(@43, @47, @2, @1) */
  rr=w22;
  *rr++ = w43;
  *rr++ = w2;
  *rr++ = w1;
  /* #248: @22 = (@9*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #249: @47 = zeros(3x1,0nz) */
  /* #250: @50 = vertcat(@40, @41, @42, @14, @22, @47) */
  rr=w50;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #251: @50 = (-@50) */
  for (i=0, rr=w50, cs=w50; i<6; ++i) *rr++ = (- *cs++ );
  /* #252: @51 = @50[:6] */
  for (rr=w51, ss=w50+0; ss!=w50+6; ss+=1) *rr++ = *ss;
  /* #253: (@36[4, 8, 12, 15, 28, 34] = @51) */
  for (cii=casadi_s5, rr=w36, ss=w51; cii!=casadi_s5+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #254: @40 = 00 */
  /* #255: @41 = 00 */
  /* #256: @42 = 00 */
  /* #257: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #258: @45 = zeros(3x3) */
  casadi_clear(w45, 9);
  /* #259: @39 = zeros(3x3) */
  casadi_clear(w39, 9);
  /* #260: @47 = 00 */
  /* #261: @48 = 00 */
  /* #262: @43 = ones(13x1,1nz) */
  w43 = 1.;
  /* #263: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @2, NULL, NULL, NULL, NULL} = vertsplit(@43) */
  w2 = w43;
  /* #264: @49 = 00 */
  /* #265: @43 = vertcat(@47, @48, @2, @49) */
  rr=(&w43);
  *rr++ = w2;
  /* #266: @1 = (@43/@7) */
  w1  = (w43/w7);
  /* #267: @28 = dense(@1) */
  casadi_densify((&w1), casadi_s6, w28, 0);
  /* #268: @1 = project(@18) */
  casadi_sparsify(w18, (&w1), casadi_s6, 0);
  /* #269: @0 = dot(@1, @43) */
  w0 = casadi_dot(1, (&w1), (&w43));
  /* #270: @0 = (@0/@7) */
  w0 /= w7;
  /* #271: @44 = (@19*@0) */
  for (i=0, rr=w44, cr=w19; i<4; ++i) (*rr++)  = ((*cr++)*w0);
  /* #272: @28 = (@28-@44) */
  for (i=0, rr=w28, cs=w44; i<4; ++i) (*rr++) -= (*cs++);
  /* #273: @0 = @28[3] */
  for (rr=(&w0), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #274: @0 = (-@0) */
  w0 = (- w0 );
  /* #275: (@39[3] += @0) */
  for (rr=w39+3, ss=(&w0); rr!=w39+4; rr+=1) *rr += *ss++;
  /* #276: @0 = 0 */
  w0 = 0.;
  /* #277: (@39[6] = @0) */
  for (rr=w39+6, ss=(&w0); rr!=w39+7; rr+=1) *rr = *ss++;
  /* #278: @0 = @28[2] */
  for (rr=(&w0), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #279: (@39[6] += @0) */
  for (rr=w39+6, ss=(&w0); rr!=w39+7; rr+=1) *rr += *ss++;
  /* #280: @0 = 0 */
  w0 = 0.;
  /* #281: (@39[7] = @0) */
  for (rr=w39+7, ss=(&w0); rr!=w39+8; rr+=1) *rr = *ss++;
  /* #282: @0 = @28[1] */
  for (rr=(&w0), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #283: @0 = (-@0) */
  w0 = (- w0 );
  /* #284: (@39[7] += @0) */
  for (rr=w39+7, ss=(&w0); rr!=w39+8; rr+=1) *rr += *ss++;
  /* #285: @0 = 0 */
  w0 = 0.;
  /* #286: (@39[1] = @0) */
  for (rr=w39+1, ss=(&w0); rr!=w39+2; rr+=1) *rr = *ss++;
  /* #287: @0 = @28[3] */
  for (rr=(&w0), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #288: (@39[1] += @0) */
  for (rr=w39+1, ss=(&w0); rr!=w39+2; rr+=1) *rr += *ss++;
  /* #289: @0 = 0 */
  w0 = 0.;
  /* #290: (@39[2] = @0) */
  for (rr=w39+2, ss=(&w0); rr!=w39+3; rr+=1) *rr = *ss++;
  /* #291: @0 = @28[2] */
  for (rr=(&w0), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #292: @0 = (-@0) */
  w0 = (- w0 );
  /* #293: (@39[2] += @0) */
  for (rr=w39+2, ss=(&w0); rr!=w39+3; rr+=1) *rr += *ss++;
  /* #294: @0 = 0 */
  w0 = 0.;
  /* #295: (@39[5] = @0) */
  for (rr=w39+5, ss=(&w0); rr!=w39+6; rr+=1) *rr = *ss++;
  /* #296: @0 = @28[1] */
  for (rr=(&w0), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #297: (@39[5] += @0) */
  for (rr=w39+5, ss=(&w0); rr!=w39+6; rr+=1) *rr += *ss++;
  /* #298: @45 = mac(@20,@39,@45) */
  for (i=0, rr=w45; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #299: @38 = zeros(3x3) */
  casadi_clear(w38, 9);
  /* #300: @46 = (2.*@39) */
  for (i=0, rr=w46, cs=w39; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #301: @38 = mac(@46,@17,@38) */
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w46+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #302: @45 = (@45+@38) */
  for (i=0, rr=w45, cs=w38; i<9; ++i) (*rr++) += (*cs++);
  /* #303: @0 = @28[0] */
  for (rr=(&w0), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #304: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #305: @38 = (@17*@0) */
  for (i=0, rr=w38, cr=w17; i<9; ++i) (*rr++)  = ((*cr++)*w0);
  /* #306: @39 = (@8*@39) */
  for (i=0, rr=w39, cs=w39; i<9; ++i) (*rr++)  = (w8*(*cs++));
  /* #307: @38 = (@38+@39) */
  for (i=0, rr=w38, cs=w39; i<9; ++i) (*rr++) += (*cs++);
  /* #308: @45 = (@45+@38) */
  for (i=0, rr=w45, cs=w38; i<9; ++i) (*rr++) += (*cs++);
  /* #309: @14 = mac(@45,@21,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w45+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #310: @14 = (@27*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w27*(*cs++));
  /* #311: @0 = (@12*@2) */
  w0  = (w12*w2);
  /* #312: @0 = (-@0) */
  w0 = (- w0 );
  /* #313: @1 = (@23*@2) */
  w1  = (w23*w2);
  /* #314: @47 = 00 */
  /* #315: @2 = (@10*@2) */
  w2  = (w10*w2);
  /* #316: @2 = (-@2) */
  w2 = (- w2 );
  /* #317: @22 = vertcat(@0, @1, @47, @2) */
  rr=w22;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  /* #318: @22 = (@9*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #319: @47 = zeros(3x1,0nz) */
  /* #320: @51 = vertcat(@40, @41, @42, @14, @22, @47) */
  rr=w51;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #321: @51 = (-@51) */
  for (i=0, rr=w51, cs=w51; i<6; ++i) *rr++ = (- *cs++ );
  /* #322: @50 = @51[:6] */
  for (rr=w50, ss=w51+0; ss!=w51+6; ss+=1) *rr++ = *ss;
  /* #323: (@36[5, 9, 13, 16, 22, 35] = @50) */
  for (cii=casadi_s7, rr=w36, ss=w50; cii!=casadi_s7+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #324: @40 = 00 */
  /* #325: @41 = 00 */
  /* #326: @42 = 00 */
  /* #327: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #328: @45 = zeros(3x3) */
  casadi_clear(w45, 9);
  /* #329: @38 = zeros(3x3) */
  casadi_clear(w38, 9);
  /* #330: @47 = 00 */
  /* #331: @48 = 00 */
  /* #332: @49 = 00 */
  /* #333: @0 = ones(13x1,1nz) */
  w0 = 1.;
  /* #334: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @1, NULL, NULL, NULL} = vertsplit(@0) */
  w1 = w0;
  /* #335: @0 = vertcat(@47, @48, @49, @1) */
  rr=(&w0);
  *rr++ = w1;
  /* #336: @2 = (@0/@7) */
  w2  = (w0/w7);
  /* #337: @28 = dense(@2) */
  casadi_densify((&w2), casadi_s8, w28, 0);
  /* #338: @2 = project(@18) */
  casadi_sparsify(w18, (&w2), casadi_s8, 0);
  /* #339: @43 = dot(@2, @0) */
  w43 = casadi_dot(1, (&w2), (&w0));
  /* #340: @43 = (@43/@7) */
  w43 /= w7;
  /* #341: @19 = (@19*@43) */
  for (i=0, rr=w19; i<4; ++i) (*rr++) *= w43;
  /* #342: @28 = (@28-@19) */
  for (i=0, rr=w28, cs=w19; i<4; ++i) (*rr++) -= (*cs++);
  /* #343: @43 = @28[3] */
  for (rr=(&w43), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #344: @43 = (-@43) */
  w43 = (- w43 );
  /* #345: (@38[3] += @43) */
  for (rr=w38+3, ss=(&w43); rr!=w38+4; rr+=1) *rr += *ss++;
  /* #346: @43 = 0 */
  w43 = 0.;
  /* #347: (@38[6] = @43) */
  for (rr=w38+6, ss=(&w43); rr!=w38+7; rr+=1) *rr = *ss++;
  /* #348: @43 = @28[2] */
  for (rr=(&w43), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #349: (@38[6] += @43) */
  for (rr=w38+6, ss=(&w43); rr!=w38+7; rr+=1) *rr += *ss++;
  /* #350: @43 = 0 */
  w43 = 0.;
  /* #351: (@38[7] = @43) */
  for (rr=w38+7, ss=(&w43); rr!=w38+8; rr+=1) *rr = *ss++;
  /* #352: @43 = @28[1] */
  for (rr=(&w43), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #353: @43 = (-@43) */
  w43 = (- w43 );
  /* #354: (@38[7] += @43) */
  for (rr=w38+7, ss=(&w43); rr!=w38+8; rr+=1) *rr += *ss++;
  /* #355: @43 = 0 */
  w43 = 0.;
  /* #356: (@38[1] = @43) */
  for (rr=w38+1, ss=(&w43); rr!=w38+2; rr+=1) *rr = *ss++;
  /* #357: @43 = @28[3] */
  for (rr=(&w43), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #358: (@38[1] += @43) */
  for (rr=w38+1, ss=(&w43); rr!=w38+2; rr+=1) *rr += *ss++;
  /* #359: @43 = 0 */
  w43 = 0.;
  /* #360: (@38[2] = @43) */
  for (rr=w38+2, ss=(&w43); rr!=w38+3; rr+=1) *rr = *ss++;
  /* #361: @43 = @28[2] */
  for (rr=(&w43), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #362: @43 = (-@43) */
  w43 = (- w43 );
  /* #363: (@38[2] += @43) */
  for (rr=w38+2, ss=(&w43); rr!=w38+3; rr+=1) *rr += *ss++;
  /* #364: @43 = 0 */
  w43 = 0.;
  /* #365: (@38[5] = @43) */
  for (rr=w38+5, ss=(&w43); rr!=w38+6; rr+=1) *rr = *ss++;
  /* #366: @43 = @28[1] */
  for (rr=(&w43), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #367: (@38[5] += @43) */
  for (rr=w38+5, ss=(&w43); rr!=w38+6; rr+=1) *rr += *ss++;
  /* #368: @45 = mac(@20,@38,@45) */
  for (i=0, rr=w45; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #369: @20 = zeros(3x3) */
  casadi_clear(w20, 9);
  /* #370: @39 = (2.*@38) */
  for (i=0, rr=w39, cs=w38; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #371: @20 = mac(@39,@17,@20) */
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w39+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #372: @45 = (@45+@20) */
  for (i=0, rr=w45, cs=w20; i<9; ++i) (*rr++) += (*cs++);
  /* #373: @43 = @28[0] */
  for (rr=(&w43), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #374: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #375: @17 = (@17*@43) */
  for (i=0, rr=w17; i<9; ++i) (*rr++) *= w43;
  /* #376: @38 = (@8*@38) */
  for (i=0, rr=w38, cs=w38; i<9; ++i) (*rr++)  = (w8*(*cs++));
  /* #377: @17 = (@17+@38) */
  for (i=0, rr=w17, cs=w38; i<9; ++i) (*rr++) += (*cs++);
  /* #378: @45 = (@45+@17) */
  for (i=0, rr=w45, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #379: @14 = mac(@45,@21,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w45+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #380: @14 = (@27*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w27*(*cs++));
  /* #381: @27 = (@23*@1) */
  w27  = (w23*w1);
  /* #382: @27 = (-@27) */
  w27 = (- w27 );
  /* #383: @8 = (@12*@1) */
  w8  = (w12*w1);
  /* #384: @8 = (-@8) */
  w8 = (- w8 );
  /* #385: @1 = (@10*@1) */
  w1  = (w10*w1);
  /* #386: @47 = 00 */
  /* #387: @21 = vertcat(@27, @8, @1, @47) */
  rr=w21;
  *rr++ = w27;
  *rr++ = w8;
  *rr++ = w1;
  /* #388: @21 = (@9*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #389: @47 = zeros(3x1,0nz) */
  /* #390: @50 = vertcat(@40, @41, @42, @14, @21, @47) */
  rr=w50;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #391: @50 = (-@50) */
  for (i=0, rr=w50, cs=w50; i<6; ++i) *rr++ = (- *cs++ );
  /* #392: @51 = @50[:6] */
  for (rr=w51, ss=w50+0; ss!=w50+6; ss+=1) *rr++ = *ss;
  /* #393: (@36[6, 10, 14, 17, 23, 29] = @51) */
  for (cii=casadi_s9, rr=w36, ss=w51; cii!=casadi_s9+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #394: @40 = 00 */
  /* #395: @41 = 00 */
  /* #396: @42 = 00 */
  /* #397: @47 = zeros(3x1,0nz) */
  /* #398: @27 = ones(13x1,1nz) */
  w27 = 1.;
  /* #399: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @8, NULL, NULL} = vertsplit(@27) */
  w8 = w27;
  /* #400: @27 = (@4*@8) */
  w27  = (w4*w8);
  /* #401: @27 = (-@27) */
  w27 = (- w27 );
  /* #402: @1 = (@3*@8) */
  w1  = (w3*w8);
  /* #403: @43 = (@6*@8) */
  w43  = (w6*w8);
  /* #404: @7 = (@5*@8) */
  w7  = (w5*w8);
  /* #405: @7 = (-@7) */
  w7 = (- w7 );
  /* #406: @28 = vertcat(@27, @1, @43, @7) */
  rr=w28;
  *rr++ = w27;
  *rr++ = w1;
  *rr++ = w43;
  *rr++ = w7;
  /* #407: @28 = (@9*@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #408: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #409: @21 = zeros(3x1) */
  casadi_clear(w21, 3);
  /* #410: @48 = 00 */
  /* #411: @49 = 00 */
  /* #412: @27 = vertcat(@8, @48, @49) */
  rr=(&w27);
  *rr++ = w8;
  /* #413: @21 = mac(@16,@27,@21) */
  casadi_mtimes(w16, casadi_s11, (&w27), casadi_s10, w21, casadi_s0, w, 0);
  /* #414: @27 = @21[2] */
  for (rr=(&w27), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #415: @1 = (@12*@27) */
  w1  = (w12*w27);
  /* #416: @43 = @21[1] */
  for (rr=(&w43), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #417: @7 = (@23*@43) */
  w7  = (w23*w43);
  /* #418: @1 = (@1-@7) */
  w1 -= w7;
  /* #419: @7 = @21[0] */
  for (rr=(&w7), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #420: @2 = (@23*@7) */
  w2  = (w23*w7);
  /* #421: @0 = (@11*@8) */
  w0  = (w11*w8);
  /* #422: @27 = (@10*@27) */
  w27  = (w10*w27);
  /* #423: @0 = (@0+@27) */
  w0 += w27;
  /* #424: @2 = (@2-@0) */
  w2 -= w0;
  /* #425: @8 = (@25*@8) */
  w8  = (w25*w8);
  /* #426: @43 = (@10*@43) */
  w43  = (w10*w43);
  /* #427: @8 = (@8+@43) */
  w8 += w43;
  /* #428: @7 = (@12*@7) */
  w7  = (w12*w7);
  /* #429: @8 = (@8-@7) */
  w8 -= w7;
  /* #430: @21 = vertcat(@1, @2, @8) */
  rr=w21;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w8;
  /* #431: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) *rr++ = (- *cs++ );
  /* #432: @14 = mac(@29,@21,@14) */
  casadi_mtimes(w29, casadi_s1, w21, casadi_s0, w14, casadi_s0, w, 0);
  /* #433: @37 = vertcat(@40, @41, @42, @47, @28, @14) */
  rr=w37;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #434: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<7; ++i) *rr++ = (- *cs++ );
  /* #435: @52 = @37[:7] */
  for (rr=w52, ss=w37+0; ss!=w37+7; ss+=1) *rr++ = *ss;
  /* #436: (@36[18, 24, 30, 36, 39, 42, 45] = @52) */
  for (cii=casadi_s12, rr=w36, ss=w52; cii!=casadi_s12+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #437: @40 = 00 */
  /* #438: @41 = 00 */
  /* #439: @42 = 00 */
  /* #440: @47 = zeros(3x1,0nz) */
  /* #441: @1 = ones(13x1,1nz) */
  w1 = 1.;
  /* #442: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @2, NULL} = vertsplit(@1) */
  w2 = w1;
  /* #443: @1 = (@5*@2) */
  w1  = (w5*w2);
  /* #444: @1 = (-@1) */
  w1 = (- w1 );
  /* #445: @8 = (@6*@2) */
  w8  = (w6*w2);
  /* #446: @8 = (-@8) */
  w8 = (- w8 );
  /* #447: @7 = (@3*@2) */
  w7  = (w3*w2);
  /* #448: @43 = (@4*@2) */
  w43  = (w4*w2);
  /* #449: @28 = vertcat(@1, @8, @7, @43) */
  rr=w28;
  *rr++ = w1;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w43;
  /* #450: @28 = (@9*@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #451: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #452: @11 = (@11*@2) */
  w11 *= w2;
  /* #453: @21 = zeros(3x1) */
  casadi_clear(w21, 3);
  /* #454: @48 = 00 */
  /* #455: @49 = 00 */
  /* #456: @1 = vertcat(@48, @2, @49) */
  rr=(&w1);
  *rr++ = w2;
  /* #457: @21 = mac(@16,@1,@21) */
  casadi_mtimes(w16, casadi_s11, (&w1), casadi_s13, w21, casadi_s0, w, 0);
  /* #458: @1 = @21[2] */
  for (rr=(&w1), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #459: @8 = (@12*@1) */
  w8  = (w12*w1);
  /* #460: @11 = (@11+@8) */
  w11 += w8;
  /* #461: @8 = @21[1] */
  for (rr=(&w8), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #462: @7 = (@23*@8) */
  w7  = (w23*w8);
  /* #463: @11 = (@11-@7) */
  w11 -= w7;
  /* #464: @7 = @21[0] */
  for (rr=(&w7), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #465: @43 = (@23*@7) */
  w43  = (w23*w7);
  /* #466: @1 = (@10*@1) */
  w1  = (w10*w1);
  /* #467: @43 = (@43-@1) */
  w43 -= w1;
  /* #468: @8 = (@10*@8) */
  w8  = (w10*w8);
  /* #469: @2 = (@26*@2) */
  w2  = (w26*w2);
  /* #470: @7 = (@12*@7) */
  w7  = (w12*w7);
  /* #471: @2 = (@2+@7) */
  w2 += w7;
  /* #472: @8 = (@8-@2) */
  w8 -= w2;
  /* #473: @21 = vertcat(@11, @43, @8) */
  rr=w21;
  *rr++ = w11;
  *rr++ = w43;
  *rr++ = w8;
  /* #474: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) *rr++ = (- *cs++ );
  /* #475: @14 = mac(@29,@21,@14) */
  casadi_mtimes(w29, casadi_s1, w21, casadi_s0, w14, casadi_s0, w, 0);
  /* #476: @52 = vertcat(@40, @41, @42, @47, @28, @14) */
  rr=w52;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #477: @52 = (-@52) */
  for (i=0, rr=w52, cs=w52; i<7; ++i) *rr++ = (- *cs++ );
  /* #478: @37 = @52[:7] */
  for (rr=w37, ss=w52+0; ss!=w52+7; ss+=1) *rr++ = *ss;
  /* #479: (@36[19, 25, 31, 37, 40, 43, 46] = @37) */
  for (cii=casadi_s14, rr=w36, ss=w37; cii!=casadi_s14+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #480: @40 = 00 */
  /* #481: @41 = 00 */
  /* #482: @42 = 00 */
  /* #483: @47 = zeros(3x1,0nz) */
  /* #484: @11 = ones(13x1,1nz) */
  w11 = 1.;
  /* #485: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @43} = vertsplit(@11) */
  w43 = w11;
  /* #486: @6 = (@6*@43) */
  w6 *= w43;
  /* #487: @6 = (-@6) */
  w6 = (- w6 );
  /* #488: @5 = (@5*@43) */
  w5 *= w43;
  /* #489: @4 = (@4*@43) */
  w4 *= w43;
  /* #490: @4 = (-@4) */
  w4 = (- w4 );
  /* #491: @3 = (@3*@43) */
  w3 *= w43;
  /* #492: @28 = vertcat(@6, @5, @4, @3) */
  rr=w28;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w4;
  *rr++ = w3;
  /* #493: @28 = (@9*@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #494: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #495: @21 = zeros(3x1) */
  casadi_clear(w21, 3);
  /* #496: @48 = 00 */
  /* #497: @49 = 00 */
  /* #498: @9 = vertcat(@48, @49, @43) */
  rr=(&w9);
  *rr++ = w43;
  /* #499: @21 = mac(@16,@9,@21) */
  casadi_mtimes(w16, casadi_s11, (&w9), casadi_s15, w21, casadi_s0, w, 0);
  /* #500: @9 = @21[2] */
  for (rr=(&w9), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #501: @6 = (@12*@9) */
  w6  = (w12*w9);
  /* #502: @25 = (@25*@43) */
  w25 *= w43;
  /* #503: @5 = @21[1] */
  for (rr=(&w5), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #504: @4 = (@23*@5) */
  w4  = (w23*w5);
  /* #505: @25 = (@25+@4) */
  w25 += w4;
  /* #506: @6 = (@6-@25) */
  w6 -= w25;
  /* #507: @26 = (@26*@43) */
  w26 *= w43;
  /* #508: @43 = @21[0] */
  for (rr=(&w43), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #509: @23 = (@23*@43) */
  w23 *= w43;
  /* #510: @26 = (@26+@23) */
  w26 += w23;
  /* #511: @9 = (@10*@9) */
  w9  = (w10*w9);
  /* #512: @26 = (@26-@9) */
  w26 -= w9;
  /* #513: @10 = (@10*@5) */
  w10 *= w5;
  /* #514: @12 = (@12*@43) */
  w12 *= w43;
  /* #515: @10 = (@10-@12) */
  w10 -= w12;
  /* #516: @21 = vertcat(@6, @26, @10) */
  rr=w21;
  *rr++ = w6;
  *rr++ = w26;
  *rr++ = w10;
  /* #517: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) *rr++ = (- *cs++ );
  /* #518: @14 = mac(@29,@21,@14) */
  casadi_mtimes(w29, casadi_s1, w21, casadi_s0, w14, casadi_s0, w, 0);
  /* #519: @37 = vertcat(@40, @41, @42, @47, @28, @14) */
  rr=w37;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #520: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<7; ++i) *rr++ = (- *cs++ );
  /* #521: @52 = @37[:7] */
  for (rr=w52, ss=w37+0; ss!=w37+7; ss+=1) *rr++ = *ss;
  /* #522: (@36[20, 26, 32, 38, 41, 44, 47] = @52) */
  for (cii=casadi_s16, rr=w36, ss=w52; cii!=casadi_s16+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #523: @53 = @36' */
  casadi_trans(w36,casadi_s18, w53, casadi_s17, iw);
  /* #524: output[1][0] = @53 */
  casadi_copy(w53, 48, res[1]);
  /* #525: @13 = zeros(13x13,13nz) */
  casadi_clear(w13, 13);
  /* #526: @35 = ones(13x1) */
  casadi_fill(w35, 13, 1.);
  /* #527: (@13[:13] = @35) */
  for (rr=w13+0, ss=w35; rr!=w13+13; rr+=1) *rr = *ss++;
  /* #528: @35 = @13' */
  casadi_trans(w13,casadi_s19, w35, casadi_s19, iw);
  /* #529: output[2][0] = @35 */
  casadi_copy(w35, 13, res[2]);
  /* #530: @51 = zeros(4x13,6nz) */
  casadi_clear(w51, 6);
  /* #531: @40 = 00 */
  /* #532: @41 = 00 */
  /* #533: @42 = 00 */
  /* #534: @6 = 1.17647 */
  w6 = 1.1764705882352942e+00;
  /* #535: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #536: @47 = 00 */
  /* #537: @48 = 00 */
  /* #538: @28 = ones(4x1) */
  casadi_fill(w28, 4, 1.);
  /* #539: {@26, @10, @12, @43} = vertsplit(@28) */
  w26 = w28[0];
  w10 = w28[1];
  w12 = w28[2];
  w43 = w28[3];
  /* #540: @5 = vertcat(@47, @48, @26) */
  rr=(&w5);
  *rr++ = w26;
  /* #541: @14 = mac(@15,@5,@14) */
  casadi_mtimes(w15, casadi_s11, (&w5), casadi_s15, w14, casadi_s0, w, 0);
  /* #542: @14 = (@6*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #543: @47 = zeros(4x1,0nz) */
  /* #544: @21 = zeros(3x1) */
  casadi_clear(w21, 3);
  /* #545: @22 = vertcat(@10, @12, @43) */
  rr=w22;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w43;
  /* #546: @21 = mac(@29,@22,@21) */
  casadi_mtimes(w29, casadi_s1, w22, casadi_s0, w21, casadi_s0, w, 0);
  /* #547: @50 = vertcat(@40, @41, @42, @14, @47, @21) */
  rr=w50;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #548: @50 = (-@50) */
  for (i=0, rr=w50, cs=w50; i<6; ++i) *rr++ = (- *cs++ );
  /* #549: @54 = @50[:6] */
  for (rr=w54, ss=w50+0; ss!=w50+6; ss+=1) *rr++ = *ss;
  /* #550: (@51[:6] = @54) */
  for (rr=w51+0, ss=w54; rr!=w51+6; rr+=1) *rr = *ss++;
  /* #551: @54 = @51' */
  casadi_trans(w51,casadi_s21, w54, casadi_s20, iw);
  /* #552: output[3][0] = @54 */
  casadi_copy(w54, 6, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s22;
    case 1: return casadi_s22;
    case 2: return casadi_s23;
    case 3: return casadi_s24;
    case 4: return casadi_s25;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s22;
    case 1: return casadi_s17;
    case 2: return casadi_s19;
    case 3: return casadi_s20;
    case 4: return casadi_s26;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_impl_dae_fun_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 287;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
