/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s4[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s5[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s6[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s7[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s8[14] = {0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 34, 35, 36, 37};
static const casadi_int casadi_s9[14] = {0, 4, 8, 12, 16, 19, 22, 25, 28, 31, 34, 38, 42, 46};
static const casadi_int casadi_s10[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s12[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s13[14] = {4, 5, 6, 7, 19, 20, 21, 28, 29, 30, 38, 39, 40, 41};
static const casadi_int casadi_s14[14] = {1, 5, 9, 13, 17, 20, 23, 26, 29, 32, 35, 39, 43, 47};
static const casadi_int casadi_s15[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s16[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s17[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s18[14] = {8, 9, 10, 11, 22, 23, 24, 31, 32, 33, 42, 43, 44, 45};
static const casadi_int casadi_s19[14] = {2, 6, 10, 14, 18, 21, 24, 27, 30, 33, 36, 40, 44, 48};
static const casadi_int casadi_s20[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s21[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s22[70] = {17, 17, 0, 4, 8, 12, 16, 19, 22, 25, 28, 31, 34, 38, 42, 46, 50, 50, 50, 50, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 7, 8, 9, 7, 8, 9, 7, 8, 9, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13};
static const casadi_int casadi_s23[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s24[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s25[3] = {0, 0, 0};
static const casadi_int casadi_s26[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s27[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s28[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s29[20] = {0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[16] = {2.0000000000000000e-03, 0., 0., 0., 0., 200., 0., 0., 0., 0., 200., 0., 0., 0., 0., 200.};
static const casadi_real casadi_c2[3] = {0., 0., 1.};

/* Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess:(i0[13],i1[4],i2[],i3[20])->(o0,o1[17],o2[17x17,50nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+4, *w2=w+7, *w3=w+10, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, *w25=w+40, *w26=w+60, *w27=w+63, *w28=w+66, *w29=w+75, *w30=w+88, *w31=w+91, *w32=w+94, *w33=w+103, *w34=w+107, *w35=w+111, *w36=w+115, *w37=w+119, *w38=w+122, *w39=w+125, *w40=w+128, *w41=w+131, *w42=w+140, *w43=w+144, *w44=w+160, *w45=w+163, *w46=w+179, *w47=w+188, *w48=w+191, *w49=w+194, *w50=w+197, w51, w52, w53, *w54=w+204, *w55=w+213, *w56=w+222, w57, w58, w59, w60, w61, w62, *w63=w+237, *w64=w+287, *w65=w+291, *w69=w+298, *w70=w+302, w71, w72, *w73=w+308, w74, w75, *w76=w+314, w77, w78, w79, w80, w81, w82, w83, w84, w85, w86, w87, *w88=w+328, *w89=w+345, *w90=w+359, *w91=w+361, *w92=w+369;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #6: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #7: @7 = input[3][2] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #8: @8 = input[3][3] */
  w8 = arg[3] ? arg[3][3] : 0;
  /* #9: @9 = input[3][4] */
  w9 = arg[3] ? arg[3][4] : 0;
  /* #10: @10 = input[3][5] */
  w10 = arg[3] ? arg[3][5] : 0;
  /* #11: @11 = input[3][6] */
  w11 = arg[3] ? arg[3][6] : 0;
  /* #12: @12 = input[3][7] */
  w12 = arg[3] ? arg[3][7] : 0;
  /* #13: @13 = input[3][8] */
  w13 = arg[3] ? arg[3][8] : 0;
  /* #14: @14 = input[3][9] */
  w14 = arg[3] ? arg[3][9] : 0;
  /* #15: @15 = input[3][10] */
  w15 = arg[3] ? arg[3][10] : 0;
  /* #16: @16 = input[3][11] */
  w16 = arg[3] ? arg[3][11] : 0;
  /* #17: @17 = input[3][12] */
  w17 = arg[3] ? arg[3][12] : 0;
  /* #18: @18 = input[3][13] */
  w18 = arg[3] ? arg[3][13] : 0;
  /* #19: @19 = input[3][14] */
  w19 = arg[3] ? arg[3][14] : 0;
  /* #20: @20 = input[3][15] */
  w20 = arg[3] ? arg[3][15] : 0;
  /* #21: @21 = input[3][16] */
  w21 = arg[3] ? arg[3][16] : 0;
  /* #22: @22 = input[3][17] */
  w22 = arg[3] ? arg[3][17] : 0;
  /* #23: @23 = input[3][18] */
  w23 = arg[3] ? arg[3][18] : 0;
  /* #24: @24 = input[3][19] */
  w24 = arg[3] ? arg[3][19] : 0;
  /* #25: @25 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24) */
  rr=w25;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  /* #26: @26 = @25[3:6] */
  for (rr=w26, ss=w25+3; ss!=w25+6; ss+=1) *rr++ = *ss;
  /* #27: @27 = @26' */
  casadi_copy(w26, 3, w27);
  /* #28: @4 = mac(@27,@26,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #29: @28 = @4[0, 0, 0, 0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w28, ss=(&w4); cii!=casadi_s0+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #30: @3 = (@3-@28) */
  for (i=0, rr=w3, cs=w28; i<9; ++i) (*rr++) -= (*cs++);
  /* #31: @27 = @25[:3] */
  for (rr=w27, ss=w25+0; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #32: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #33: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #34: @6 = input[0][2] */
  w6 = arg[0] ? arg[0][2] : 0;
  /* #35: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #36: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #37: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #38: @13 = input[0][6] */
  w13 = arg[0] ? arg[0][6] : 0;
  /* #39: @14 = input[0][7] */
  w14 = arg[0] ? arg[0][7] : 0;
  /* #40: @15 = input[0][8] */
  w15 = arg[0] ? arg[0][8] : 0;
  /* #41: @16 = input[0][9] */
  w16 = arg[0] ? arg[0][9] : 0;
  /* #42: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #43: @18 = input[0][11] */
  w18 = arg[0] ? arg[0][11] : 0;
  /* #44: @19 = input[0][12] */
  w19 = arg[0] ? arg[0][12] : 0;
  /* #45: @29 = vertcat(@4, @5, @6, @7, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w29;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #46: @30 = @29[:3] */
  for (rr=w30, ss=w29+0; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #47: @27 = (@27-@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) -= (*cs++);
  /* #48: @2 = mac(@3,@27,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #49: @30 = @2' */
  casadi_copy(w2, 3, w30);
  /* #50: @28 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w28);
  /* #51: @1 = mac(@30,@28,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #52: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #53: @4 = 0 */
  w4 = 0.;
  /* #54: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #55: @5 = dot(@26, @27) */
  w5 = casadi_dot(3, w26, w27);
  /* #56: @27 = (@5*@26) */
  for (i=0, rr=w27, cs=w26; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #57: @31 = @27' */
  casadi_copy(w27, 3, w31);
  /* #58: @32 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w32);
  /* #59: @30 = mac(@31,@32,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #60: @4 = mac(@30,@27,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #61: @0 = (@0+@4) */
  w0 += w4;
  /* #62: @4 = 0 */
  w4 = 0.;
  /* #63: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #64: @14 = (-@14) */
  w14 = (- w14 );
  /* #65: @15 = (-@15) */
  w15 = (- w15 );
  /* #66: @16 = (-@16) */
  w16 = (- w16 );
  /* #67: @33 = vertcat(@13, @14, @15, @16) */
  rr=w33;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #68: @34 = @29[6:10] */
  for (rr=w34, ss=w29+6; ss!=w29+10; ss+=1) *rr++ = *ss;
  /* #69: @13 = ||@34||_F */
  w13 = sqrt(casadi_dot(4, w34, w34));
  /* #70: @33 = (@33/@13) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) /= w13;
  /* #71: {@14, @15, @16, @5} = vertsplit(@33) */
  w14 = w33[0];
  w15 = w33[1];
  w16 = w33[2];
  w5 = w33[3];
  /* #72: @35 = @25[6:10] */
  for (rr=w35, ss=w25+6; ss!=w25+10; ss+=1) *rr++ = *ss;
  /* #73: {@6, @7, @11, @12} = vertsplit(@35) */
  w6 = w35[0];
  w7 = w35[1];
  w11 = w35[2];
  w12 = w35[3];
  /* #74: @17 = (@14*@6) */
  w17  = (w14*w6);
  /* #75: @18 = (@15*@7) */
  w18  = (w15*w7);
  /* #76: @17 = (@17-@18) */
  w17 -= w18;
  /* #77: @18 = (@16*@11) */
  w18  = (w16*w11);
  /* #78: @17 = (@17-@18) */
  w17 -= w18;
  /* #79: @18 = (@5*@12) */
  w18  = (w5*w12);
  /* #80: @17 = (@17-@18) */
  w17 -= w18;
  /* #81: @18 = 0 */
  w18 = 0.;
  /* #82: @18 = (@17<@18) */
  w18  = (w17<w18);
  /* #83: @19 = (@14*@7) */
  w19  = (w14*w7);
  /* #84: @20 = (@15*@6) */
  w20  = (w15*w6);
  /* #85: @19 = (@19+@20) */
  w19 += w20;
  /* #86: @20 = (@16*@12) */
  w20  = (w16*w12);
  /* #87: @19 = (@19+@20) */
  w19 += w20;
  /* #88: @20 = (@5*@11) */
  w20  = (w5*w11);
  /* #89: @19 = (@19-@20) */
  w19 -= w20;
  /* #90: @20 = (@14*@11) */
  w20  = (w14*w11);
  /* #91: @21 = (@15*@12) */
  w21  = (w15*w12);
  /* #92: @20 = (@20-@21) */
  w20 -= w21;
  /* #93: @21 = (@16*@6) */
  w21  = (w16*w6);
  /* #94: @20 = (@20+@21) */
  w20 += w21;
  /* #95: @21 = (@5*@7) */
  w21  = (w5*w7);
  /* #96: @20 = (@20+@21) */
  w20 += w21;
  /* #97: @14 = (@14*@12) */
  w14 *= w12;
  /* #98: @15 = (@15*@11) */
  w15 *= w11;
  /* #99: @14 = (@14+@15) */
  w14 += w15;
  /* #100: @16 = (@16*@7) */
  w16 *= w7;
  /* #101: @14 = (@14-@16) */
  w14 -= w16;
  /* #102: @5 = (@5*@6) */
  w5 *= w6;
  /* #103: @14 = (@14+@5) */
  w14 += w5;
  /* #104: @35 = vertcat(@17, @19, @20, @14) */
  rr=w35;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w14;
  /* #105: @36 = (-@35) */
  for (i=0, rr=w36, cs=w35; i<4; ++i) *rr++ = (- *cs++ );
  /* #106: @36 = (@18?@36:0) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) (*rr++)  = (w18?(*cs++):0);
  /* #107: @17 = (!@18) */
  w17 = (! w18 );
  /* #108: @35 = (@17?@35:0) */
  for (i=0, rr=w35, cs=w35; i<4; ++i) (*rr++)  = (w17?(*cs++):0);
  /* #109: @36 = (@36+@35) */
  for (i=0, rr=w36, cs=w35; i<4; ++i) (*rr++) += (*cs++);
  /* #110: @37 = @36[1:4] */
  for (rr=w37, ss=w36+1; ss!=w36+4; ss+=1) *rr++ = *ss;
  /* #111: @38 = (2.*@37) */
  for (i=0, rr=w38, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #112: @19 = ||@37||_F */
  w19 = sqrt(casadi_dot(3, w37, w37));
  /* #113: @20 = @36[0] */
  for (rr=(&w20), ss=w36+0; ss!=w36+1; ss+=1) *rr++ = *ss;
  /* #114: @14 = atan2(@19,@20) */
  w14  = atan2(w19,w20);
  /* #115: @39 = (@38*@14) */
  for (i=0, rr=w39, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w14);
  /* #116: @39 = (@39/@19) */
  for (i=0, rr=w39; i<3; ++i) (*rr++) /= w19;
  /* #117: @40 = @39' */
  casadi_copy(w39, 3, w40);
  /* #118: @41 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w41);
  /* #119: @31 = mac(@40,@41,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w40+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #120: @4 = mac(@31,@39,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #121: @0 = (@0+@4) */
  w0 += w4;
  /* #122: @4 = 0 */
  w4 = 0.;
  /* #123: @36 = zeros(1x4) */
  casadi_clear(w36, 4);
  /* #124: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #125: @16 = input[1][1] */
  w16 = arg[1] ? arg[1][1] : 0;
  /* #126: @15 = input[1][2] */
  w15 = arg[1] ? arg[1][2] : 0;
  /* #127: @21 = input[1][3] */
  w21 = arg[1] ? arg[1][3] : 0;
  /* #128: @35 = vertcat(@5, @16, @15, @21) */
  rr=w35;
  *rr++ = w5;
  *rr++ = w16;
  *rr++ = w15;
  *rr++ = w21;
  /* #129: @42 = @35' */
  casadi_copy(w35, 4, w42);
  /* #130: @43 = 
  [[0.002, 0, 0, 0], 
   [0, 200, 0, 0], 
   [0, 0, 200, 0], 
   [0, 0, 0, 200]] */
  casadi_copy(casadi_c1, 16, w43);
  /* #131: @36 = mac(@42,@43,@36) */
  for (i=0, rr=w36; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w42+j, tt=w43+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #132: @4 = mac(@36,@35,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w36+j, tt=w35+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #133: @0 = (@0+@4) */
  w0 += w4;
  /* #134: @4 = 0.05 */
  w4 = 5.0000000000000003e-02;
  /* #135: @40 = @29[3:6] */
  for (rr=w40, ss=w29+3; ss!=w29+6; ss+=1) *rr++ = *ss;
  /* #136: @5 = dot(@26, @40) */
  w5 = casadi_dot(3, w26, w40);
  /* #137: @4 = (@4*@5) */
  w4 *= w5;
  /* #138: @0 = (@0-@4) */
  w0 -= w4;
  /* #139: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #140: @40 = @29[3:6] */
  for (rr=w40, ss=w29+3; ss!=w29+6; ss+=1) *rr++ = *ss;
  /* #141: @44 = [0, 0, 1] */
  casadi_copy(casadi_c2, 3, w44);
  /* #142: @5 = @44[2] */
  for (rr=(&w5), ss=w44+2; ss!=w44+3; ss+=1) *rr++ = *ss;
  /* #143: @16 = (@9*@5) */
  w16  = (w9*w5);
  /* #144: @15 = @44[1] */
  for (rr=(&w15), ss=w44+1; ss!=w44+2; ss+=1) *rr++ = *ss;
  /* #145: @21 = (@10*@15) */
  w21  = (w10*w15);
  /* #146: @16 = (@16-@21) */
  w16 -= w21;
  /* #147: @21 = @44[0] */
  for (rr=(&w21), ss=w44+0; ss!=w44+1; ss+=1) *rr++ = *ss;
  /* #148: @10 = (@10*@21) */
  w10 *= w21;
  /* #149: @5 = (@8*@5) */
  w5  = (w8*w5);
  /* #150: @10 = (@10-@5) */
  w10 -= w5;
  /* #151: @8 = (@8*@15) */
  w8 *= w15;
  /* #152: @9 = (@9*@21) */
  w9 *= w21;
  /* #153: @8 = (@8-@9) */
  w8 -= w9;
  /* #154: @44 = vertcat(@16, @10, @8) */
  rr=w44;
  *rr++ = w16;
  *rr++ = w10;
  *rr++ = w8;
  /* #155: @16 = dot(@40, @44) */
  w16 = casadi_dot(3, w40, w44);
  /* #156: @10 = 0 */
  w10 = 0.;
  /* #157: @10 = (@16<@10) */
  w10  = (w16<w10);
  /* #158: @16 = (-@16) */
  w16 = (- w16 );
  /* #159: @16 = (@10?@16:0) */
  w16  = (w10?w16:0);
  /* #160: @4 = (@4*@16) */
  w4 *= w16;
  /* #161: @0 = (@0+@4) */
  w0 += w4;
  /* #162: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #163: @36 = @36' */
  /* #164: @42 = zeros(1x4) */
  casadi_clear(w42, 4);
  /* #165: @35 = @35' */
  /* #166: @45 = @43' */
  for (i=0, rr=w45, cs=w43; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #167: @42 = mac(@35,@45,@42) */
  for (i=0, rr=w42; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w45+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #168: @42 = @42' */
  /* #169: @36 = (@36+@42) */
  for (i=0, rr=w36, cs=w42; i<4; ++i) (*rr++) += (*cs++);
  /* #170: {@0, @4, @16, @8} = vertsplit(@36) */
  w0 = w36[0];
  w4 = w36[1];
  w16 = w36[2];
  w8 = w36[3];
  /* #171: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #172: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #173: output[1][2] = @16 */
  if (res[1]) res[1][2] = w16;
  /* #174: output[1][3] = @8 */
  if (res[1]) res[1][3] = w8;
  /* #175: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #176: @8 = 0.5 */
  w8 = 5.0000000000000000e-01;
  /* #177: @16 = 1 */
  w16 = 1.;
  /* #178: @10 = (@10?@16:0) */
  w10  = (w10?w16:0);
  /* #179: @8 = (@8*@10) */
  w8 *= w10;
  /* #180: @44 = (@8*@44) */
  for (i=0, rr=w44, cs=w44; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #181: @44 = (-@44) */
  for (i=0, rr=w44, cs=w44; i<3; ++i) *rr++ = (- *cs++ );
  /* #182: (@29[3:6] += @44) */
  for (rr=w29+3, ss=w44; rr!=w29+6; rr+=1) *rr += *ss++;
  /* #183: @8 = -0.05 */
  w8 = -5.0000000000000003e-02;
  /* #184: @44 = (@8*@26) */
  for (i=0, rr=w44, cs=w26; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #185: (@29[3:6] += @44) */
  for (rr=w29+3, ss=w44; rr!=w29+6; rr+=1) *rr += *ss++;
  /* #186: @36 = (@33/@13) */
  for (i=0, rr=w36, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)/w13);
  /* #187: @42 = (-@36) */
  for (i=0, rr=w42, cs=w36; i<4; ++i) *rr++ = (- *cs++ );
  /* #188: @8 = 1 */
  w8 = 1.;
  /* #189: @8 = (@17?@8:0) */
  w8  = (w17?w8:0);
  /* #190: @35 = zeros(4x1) */
  casadi_clear(w35, 4);
  /* #191: @10 = sq(@19) */
  w10 = casadi_sq( w19 );
  /* #192: @16 = sq(@20) */
  w16 = casadi_sq( w20 );
  /* #193: @10 = (@10+@16) */
  w10 += w16;
  /* #194: @16 = (@19/@10) */
  w16  = (w19/w10);
  /* #195: @31 = @31' */
  /* #196: @44 = zeros(1x3) */
  casadi_clear(w44, 3);
  /* #197: @40 = @39' */
  casadi_copy(w39, 3, w40);
  /* #198: @46 = @41' */
  for (i=0, rr=w46, cs=w41; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #199: @44 = mac(@40,@46,@44) */
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w40+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #200: @44 = @44' */
  /* #201: @31 = (@31+@44) */
  for (i=0, rr=w31, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #202: @44 = (@31/@19) */
  for (i=0, rr=w44, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)/w19);
  /* #203: @4 = dot(@38, @44) */
  w4 = casadi_dot(3, w38, w44);
  /* #204: @0 = (@16*@4) */
  w0  = (w16*w4);
  /* #205: @0 = (-@0) */
  w0 = (- w0 );
  /* #206: (@35[0] += @0) */
  for (rr=w35+0, ss=(&w0); rr!=w35+1; rr+=1) *rr += *ss++;
  /* #207: @40 = (@39/@19) */
  for (i=0, rr=w40, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)/w19);
  /* #208: @47 = (-@40) */
  for (i=0, rr=w47, cs=w40; i<3; ++i) *rr++ = (- *cs++ );
  /* #209: @0 = dot(@47, @31) */
  w0 = casadi_dot(3, w47, w31);
  /* #210: @9 = (@20/@10) */
  w9  = (w20/w10);
  /* #211: @21 = (@9*@4) */
  w21  = (w9*w4);
  /* #212: @0 = (@0+@21) */
  w0 += w21;
  /* #213: @0 = (@0/@19) */
  w0 /= w19;
  /* #214: @48 = (@0*@37) */
  for (i=0, rr=w48, cs=w37; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #215: @49 = (@14*@44) */
  for (i=0, rr=w49, cs=w44; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #216: @49 = (2.*@49) */
  for (i=0, rr=w49, cs=w49; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #217: @48 = (@48+@49) */
  for (i=0, rr=w48, cs=w49; i<3; ++i) (*rr++) += (*cs++);
  /* #218: (@35[1:4] += @48) */
  for (rr=w35+1, ss=w48; rr!=w35+4; rr+=1) *rr += *ss++;
  /* #219: @50 = (@8*@35) */
  for (i=0, rr=w50, cs=w35; i<4; ++i) (*rr++)  = (w8*(*cs++));
  /* #220: @21 = 1 */
  w21 = 1.;
  /* #221: @21 = (@18?@21:0) */
  w21  = (w18?w21:0);
  /* #222: @35 = (@21*@35) */
  for (i=0, rr=w35, cs=w35; i<4; ++i) (*rr++)  = (w21*(*cs++));
  /* #223: @50 = (@50-@35) */
  for (i=0, rr=w50, cs=w35; i<4; ++i) (*rr++) -= (*cs++);
  /* #224: {@15, @5, @22, @23} = vertsplit(@50) */
  w15 = w50[0];
  w5 = w50[1];
  w22 = w50[2];
  w23 = w50[3];
  /* #225: @24 = (@12*@23) */
  w24  = (w12*w23);
  /* #226: @51 = (@11*@22) */
  w51  = (w11*w22);
  /* #227: @24 = (@24+@51) */
  w24 += w51;
  /* #228: @51 = (@7*@5) */
  w51  = (w7*w5);
  /* #229: @24 = (@24+@51) */
  w24 += w51;
  /* #230: @51 = (@6*@15) */
  w51  = (w6*w15);
  /* #231: @24 = (@24+@51) */
  w24 += w51;
  /* #232: @51 = (@11*@23) */
  w51  = (w11*w23);
  /* #233: @52 = (@12*@22) */
  w52  = (w12*w22);
  /* #234: @51 = (@51-@52) */
  w51 -= w52;
  /* #235: @52 = (@6*@5) */
  w52  = (w6*w5);
  /* #236: @51 = (@51+@52) */
  w51 += w52;
  /* #237: @52 = (@7*@15) */
  w52  = (w7*w15);
  /* #238: @51 = (@51-@52) */
  w51 -= w52;
  /* #239: @52 = (@6*@22) */
  w52  = (w6*w22);
  /* #240: @53 = (@7*@23) */
  w53  = (w7*w23);
  /* #241: @52 = (@52-@53) */
  w52 -= w53;
  /* #242: @53 = (@12*@5) */
  w53  = (w12*w5);
  /* #243: @52 = (@52+@53) */
  w52 += w53;
  /* #244: @53 = (@11*@15) */
  w53  = (w11*w15);
  /* #245: @52 = (@52-@53) */
  w52 -= w53;
  /* #246: @23 = (@6*@23) */
  w23  = (w6*w23);
  /* #247: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #248: @23 = (@23+@22) */
  w23 += w22;
  /* #249: @5 = (@11*@5) */
  w5  = (w11*w5);
  /* #250: @23 = (@23-@5) */
  w23 -= w5;
  /* #251: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #252: @23 = (@23-@15) */
  w23 -= w15;
  /* #253: @50 = vertcat(@24, @51, @52, @23) */
  rr=w50;
  *rr++ = w24;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w23;
  /* #254: @24 = dot(@42, @50) */
  w24 = casadi_dot(4, w42, w50);
  /* #255: @24 = (@24/@13) */
  w24 /= w13;
  /* #256: @35 = (@24*@34) */
  for (i=0, rr=w35, cs=w34; i<4; ++i) (*rr++)  = (w24*(*cs++));
  /* #257: (@29[6:10] += @35) */
  for (rr=w29+6, ss=w35; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #258: @30 = @30' */
  /* #259: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #260: @27 = @27' */
  /* #261: @54 = @32' */
  for (i=0, rr=w54, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #262: @48 = mac(@27,@54,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #263: @48 = @48' */
  /* #264: @30 = (@30+@48) */
  for (i=0, rr=w30, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #265: @51 = dot(@26, @30) */
  w51 = casadi_dot(3, w26, w30);
  /* #266: @30 = (@51*@26) */
  for (i=0, rr=w30, cs=w26; i<3; ++i) (*rr++)  = (w51*(*cs++));
  /* #267: @48 = zeros(3x1) */
  casadi_clear(w48, 3);
  /* #268: @55 = @3' */
  for (i=0, rr=w55, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #269: @1 = @1' */
  /* #270: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #271: @2 = @2' */
  /* #272: @56 = @28' */
  for (i=0, rr=w56, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #273: @27 = mac(@2,@56,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w56+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #274: @27 = @27' */
  /* #275: @1 = (@1+@27) */
  for (i=0, rr=w1, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #276: @48 = mac(@55,@1,@48) */
  for (i=0, rr=w48; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w55+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #277: @30 = (@30+@48) */
  for (i=0, rr=w30, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #278: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #279: (@29[:3] += @30) */
  for (rr=w29+0, ss=w30; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #280: {@51, @52, @23, @15, @5, @22, @53, @57, @58, @59, @60, @61, @62} = vertsplit(@29) */
  w51 = w29[0];
  w52 = w29[1];
  w23 = w29[2];
  w15 = w29[3];
  w5 = w29[4];
  w22 = w29[5];
  w53 = w29[6];
  w57 = w29[7];
  w58 = w29[8];
  w59 = w29[9];
  w60 = w29[10];
  w61 = w29[11];
  w62 = w29[12];
  /* #281: output[1][4] = @51 */
  if (res[1]) res[1][4] = w51;
  /* #282: output[1][5] = @52 */
  if (res[1]) res[1][5] = w52;
  /* #283: output[1][6] = @23 */
  if (res[1]) res[1][6] = w23;
  /* #284: output[1][7] = @15 */
  if (res[1]) res[1][7] = w15;
  /* #285: output[1][8] = @5 */
  if (res[1]) res[1][8] = w5;
  /* #286: output[1][9] = @22 */
  if (res[1]) res[1][9] = w22;
  /* #287: @35 = (@50/@13) */
  for (i=0, rr=w35, cr=w50; i<4; ++i) (*rr++)  = ((*cr++)/w13);
  /* #288: {@22, @5, @15, @23} = vertsplit(@35) */
  w22 = w35[0];
  w5 = w35[1];
  w15 = w35[2];
  w23 = w35[3];
  /* #289: @22 = (@22+@53) */
  w22 += w53;
  /* #290: output[1][10] = @22 */
  if (res[1]) res[1][10] = w22;
  /* #291: @57 = (@57-@5) */
  w57 -= w5;
  /* #292: output[1][11] = @57 */
  if (res[1]) res[1][11] = w57;
  /* #293: @58 = (@58-@15) */
  w58 -= w15;
  /* #294: output[1][12] = @58 */
  if (res[1]) res[1][12] = w58;
  /* #295: @59 = (@59-@23) */
  w59 -= w23;
  /* #296: output[1][13] = @59 */
  if (res[1]) res[1][13] = w59;
  /* #297: output[1][14] = @60 */
  if (res[1]) res[1][14] = w60;
  /* #298: output[1][15] = @61 */
  if (res[1]) res[1][15] = w61;
  /* #299: output[1][16] = @62 */
  if (res[1]) res[1][16] = w62;
  /* #300: @63 = zeros(17x17,50nz) */
  casadi_clear(w63, 50);
  /* #301: @64 = zeros(1x4) */
  casadi_clear(w64, 4);
  /* #302: @65 = ones(17x1,7nz) */
  casadi_fill(w65, 7, 1.);
  /* #303: {@62, NULL, NULL, NULL, @61, NULL, NULL, NULL, NULL, NULL, @60, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@65) */
  w62 = w65[0];
  w61 = w65[1];
  w60 = w65[3];
  /* #304: @66 = 00 */
  /* #305: @67 = 00 */
  /* #306: @68 = 00 */
  /* #307: @59 = vertcat(@62, @66, @67, @68) */
  rr=(&w59);
  *rr++ = w62;
  /* #308: @62 = @59' */
  casadi_copy((&w59), 1, (&w62));
  /* #309: @64 = mac(@62,@43,@64) */
  casadi_mtimes((&w62), casadi_s3, w43, casadi_s2, w64, casadi_s1, w, 0);
  /* #310: @64 = @64' */
  /* #311: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #312: @59 = @59' */
  /* #313: @69 = mac(@59,@45,@69) */
  casadi_mtimes((&w59), casadi_s3, w45, casadi_s2, w69, casadi_s1, w, 0);
  /* #314: @69 = @69' */
  /* #315: @64 = (@64+@69) */
  for (i=0, rr=w64, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #316: {@59, @62, @23, @58} = vertsplit(@64) */
  w59 = w64[0];
  w62 = w64[1];
  w23 = w64[2];
  w58 = w64[3];
  /* #317: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #318: @64 = zeros(4x1) */
  casadi_clear(w64, 4);
  /* #319: @15 = 1 */
  w15 = 1.;
  /* #320: @17 = (@17?@15:0) */
  w17  = (w17?w15:0);
  /* #321: @66 = 00 */
  /* #322: @67 = 00 */
  /* #323: @68 = 00 */
  /* #324: @15 = vertcat(@60, @66, @67, @68) */
  rr=(&w15);
  *rr++ = w60;
  /* #325: @15 = (@15/@13) */
  w15 /= w13;
  /* #326: @69 = dense(@15) */
  casadi_densify((&w15), casadi_s4, w69, 0);
  /* #327: @33 = (@33/@13) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) /= w13;
  /* #328: @15 = project(@34) */
  casadi_sparsify(w34, (&w15), casadi_s4, 0);
  /* #329: @57 = @60[0] */
  for (rr=(&w57), ss=(&w60)+0; ss!=(&w60)+1; ss+=1) *rr++ = *ss;
  /* #330: @60 = dot(@15, @57) */
  w60 = casadi_dot(1, (&w15), (&w57));
  /* #331: @60 = (@60/@13) */
  w60 /= w13;
  /* #332: @70 = (@33*@60) */
  for (i=0, rr=w70, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #333: @69 = (@69-@70) */
  for (i=0, rr=w69, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #334: {@15, @5, @22, @53} = vertsplit(@69) */
  w15 = w69[0];
  w5 = w69[1];
  w22 = w69[2];
  w53 = w69[3];
  /* #335: @52 = (@6*@15) */
  w52  = (w6*w15);
  /* #336: @51 = (@7*@5) */
  w51  = (w7*w5);
  /* #337: @52 = (@52-@51) */
  w52 -= w51;
  /* #338: @51 = (@11*@22) */
  w51  = (w11*w22);
  /* #339: @52 = (@52-@51) */
  w52 -= w51;
  /* #340: @51 = (@12*@53) */
  w51  = (w12*w53);
  /* #341: @52 = (@52-@51) */
  w52 -= w51;
  /* #342: @51 = (@7*@15) */
  w51  = (w7*w15);
  /* #343: @71 = (@6*@5) */
  w71  = (w6*w5);
  /* #344: @51 = (@51+@71) */
  w51 += w71;
  /* #345: @71 = (@12*@22) */
  w71  = (w12*w22);
  /* #346: @51 = (@51+@71) */
  w51 += w71;
  /* #347: @71 = (@11*@53) */
  w71  = (w11*w53);
  /* #348: @51 = (@51-@71) */
  w51 -= w71;
  /* #349: @71 = (@11*@15) */
  w71  = (w11*w15);
  /* #350: @72 = (@12*@5) */
  w72  = (w12*w5);
  /* #351: @71 = (@71-@72) */
  w71 -= w72;
  /* #352: @72 = (@6*@22) */
  w72  = (w6*w22);
  /* #353: @71 = (@71+@72) */
  w71 += w72;
  /* #354: @72 = (@7*@53) */
  w72  = (w7*w53);
  /* #355: @71 = (@71+@72) */
  w71 += w72;
  /* #356: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #357: @5 = (@11*@5) */
  w5  = (w11*w5);
  /* #358: @15 = (@15+@5) */
  w15 += w5;
  /* #359: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #360: @15 = (@15-@22) */
  w15 -= w22;
  /* #361: @53 = (@6*@53) */
  w53  = (w6*w53);
  /* #362: @15 = (@15+@53) */
  w15 += w53;
  /* #363: @70 = vertcat(@52, @51, @71, @15) */
  rr=w70;
  *rr++ = w52;
  *rr++ = w51;
  *rr++ = w71;
  *rr++ = w15;
  /* #364: @73 = (@17*@70) */
  for (i=0, rr=w73, cs=w70; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #365: @52 = 1 */
  w52 = 1.;
  /* #366: @18 = (@18?@52:0) */
  w18  = (w18?w52:0);
  /* #367: @70 = (@18*@70) */
  for (i=0, rr=w70, cs=w70; i<4; ++i) (*rr++)  = (w18*(*cs++));
  /* #368: @73 = (@73-@70) */
  for (i=0, rr=w73, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #369: @30 = @73[1:4] */
  for (rr=w30, ss=w73+1; ss!=w73+4; ss+=1) *rr++ = *ss;
  /* #370: @52 = dot(@37, @30) */
  w52 = casadi_dot(3, w37, w30);
  /* #371: @52 = (@52/@19) */
  w52 /= w19;
  /* #372: @51 = (@52/@10) */
  w51  = (w52/w10);
  /* #373: @71 = (@16/@10) */
  w71  = (w16/w10);
  /* #374: @15 = (2.*@19) */
  w15 = (2.* w19 );
  /* #375: @53 = (@15*@52) */
  w53  = (w15*w52);
  /* #376: @22 = (2.*@20) */
  w22 = (2.* w20 );
  /* #377: @5 = @73[0] */
  for (rr=(&w5), ss=w73+0; ss!=w73+1; ss+=1) *rr++ = *ss;
  /* #378: @72 = (@22*@5) */
  w72  = (w22*w5);
  /* #379: @53 = (@53+@72) */
  w53 += w72;
  /* #380: @72 = (@71*@53) */
  w72  = (w71*w53);
  /* #381: @51 = (@51-@72) */
  w51 -= w72;
  /* #382: @51 = (@4*@51) */
  w51  = (w4*w51);
  /* #383: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #384: @1 = (2.*@30) */
  for (i=0, rr=w1, cs=w30; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #385: @27 = (@14*@1) */
  for (i=0, rr=w27, cs=w1; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #386: @72 = sq(@19) */
  w72 = casadi_sq( w19 );
  /* #387: @74 = sq(@20) */
  w74 = casadi_sq( w20 );
  /* #388: @72 = (@72+@74) */
  w72 += w74;
  /* #389: @20 = (@20/@72) */
  w20 /= w72;
  /* #390: @74 = (@20*@52) */
  w74  = (w20*w52);
  /* #391: @72 = (@19/@72) */
  w72  = (w19/w72);
  /* #392: @75 = (@72*@5) */
  w75  = (w72*w5);
  /* #393: @74 = (@74-@75) */
  w74 -= w75;
  /* #394: @2 = (@38*@74) */
  for (i=0, rr=w2, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #395: @27 = (@27+@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #396: @27 = (@27/@19) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w19;
  /* #397: @39 = (@39/@19) */
  for (i=0, rr=w39; i<3; ++i) (*rr++) /= w19;
  /* #398: @2 = (@39*@52) */
  for (i=0, rr=w2, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #399: @27 = (@27-@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #400: @2 = @27' */
  casadi_copy(w27, 3, w2);
  /* #401: @48 = mac(@2,@41,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #402: @48 = @48' */
  /* #403: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #404: @49 = @27' */
  casadi_copy(w27, 3, w49);
  /* #405: @2 = mac(@49,@46,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w49+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #406: @2 = @2' */
  /* #407: @48 = (@48+@2) */
  for (i=0, rr=w48, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #408: @2 = (@48/@19) */
  for (i=0, rr=w2, cr=w48; i<3; ++i) (*rr++)  = ((*cr++)/w19);
  /* #409: @49 = (@44/@19) */
  for (i=0, rr=w49, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)/w19);
  /* #410: @76 = (@49*@52) */
  for (i=0, rr=w76, cr=w49; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #411: @2 = (@2-@76) */
  for (i=0, rr=w2, cs=w76; i<3; ++i) (*rr++) -= (*cs++);
  /* #412: @75 = dot(@38, @2) */
  w75 = casadi_dot(3, w38, w2);
  /* #413: @77 = dot(@1, @44) */
  w77 = casadi_dot(3, w1, w44);
  /* #414: @75 = (@75+@77) */
  w75 += w77;
  /* #415: @77 = (@16*@75) */
  w77  = (w16*w75);
  /* #416: @51 = (@51+@77) */
  w51 += w77;
  /* #417: @51 = (-@51) */
  w51 = (- w51 );
  /* #418: (@64[0] += @51) */
  for (rr=w64+0, ss=(&w51); rr!=w64+1; rr+=1) *rr += *ss++;
  /* #419: @51 = dot(@47, @48) */
  w51 = casadi_dot(3, w47, w48);
  /* #420: @27 = (@27/@19) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w19;
  /* #421: @40 = (@40/@19) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) /= w19;
  /* #422: @48 = (@40*@52) */
  for (i=0, rr=w48, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #423: @27 = (@27-@48) */
  for (i=0, rr=w27, cs=w48; i<3; ++i) (*rr++) -= (*cs++);
  /* #424: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #425: @77 = dot(@27, @31) */
  w77 = casadi_dot(3, w27, w31);
  /* #426: @51 = (@51+@77) */
  w51 += w77;
  /* #427: @5 = (@5/@10) */
  w5 /= w10;
  /* #428: @77 = (@9/@10) */
  w77  = (w9/w10);
  /* #429: @53 = (@77*@53) */
  w53  = (w77*w53);
  /* #430: @5 = (@5-@53) */
  w5 -= w53;
  /* #431: @5 = (@4*@5) */
  w5  = (w4*w5);
  /* #432: @75 = (@9*@75) */
  w75  = (w9*w75);
  /* #433: @5 = (@5+@75) */
  w5 += w75;
  /* #434: @51 = (@51+@5) */
  w51 += w5;
  /* #435: @51 = (@51/@19) */
  w51 /= w19;
  /* #436: @5 = (@0/@19) */
  w5  = (w0/w19);
  /* #437: @52 = (@5*@52) */
  w52  = (w5*w52);
  /* #438: @51 = (@51-@52) */
  w51 -= w52;
  /* #439: @27 = (@37*@51) */
  for (i=0, rr=w27, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w51);
  /* #440: @30 = (@0*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #441: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #442: @30 = (@44*@74) */
  for (i=0, rr=w30, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #443: @2 = (@14*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #444: @30 = (@30+@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #445: @30 = (2.*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #446: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #447: (@64[1:4] += @27) */
  for (rr=w64+1, ss=w27; rr!=w64+4; rr+=1) *rr += *ss++;
  /* #448: @73 = (@8*@64) */
  for (i=0, rr=w73, cs=w64; i<4; ++i) (*rr++)  = (w8*(*cs++));
  /* #449: @64 = (@21*@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w21*(*cs++));
  /* #450: @73 = (@73-@64) */
  for (i=0, rr=w73, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #451: {@74, @51, @52, @75} = vertsplit(@73) */
  w74 = w73[0];
  w51 = w73[1];
  w52 = w73[2];
  w75 = w73[3];
  /* #452: @53 = (@12*@75) */
  w53  = (w12*w75);
  /* #453: @78 = (@11*@52) */
  w78  = (w11*w52);
  /* #454: @53 = (@53+@78) */
  w53 += w78;
  /* #455: @78 = (@7*@51) */
  w78  = (w7*w51);
  /* #456: @53 = (@53+@78) */
  w53 += w78;
  /* #457: @78 = (@6*@74) */
  w78  = (w6*w74);
  /* #458: @53 = (@53+@78) */
  w53 += w78;
  /* #459: @78 = (@11*@75) */
  w78  = (w11*w75);
  /* #460: @79 = (@12*@52) */
  w79  = (w12*w52);
  /* #461: @78 = (@78-@79) */
  w78 -= w79;
  /* #462: @79 = (@6*@51) */
  w79  = (w6*w51);
  /* #463: @78 = (@78+@79) */
  w78 += w79;
  /* #464: @79 = (@7*@74) */
  w79  = (w7*w74);
  /* #465: @78 = (@78-@79) */
  w78 -= w79;
  /* #466: @79 = (@6*@52) */
  w79  = (w6*w52);
  /* #467: @80 = (@7*@75) */
  w80  = (w7*w75);
  /* #468: @79 = (@79-@80) */
  w79 -= w80;
  /* #469: @80 = (@12*@51) */
  w80  = (w12*w51);
  /* #470: @79 = (@79+@80) */
  w79 += w80;
  /* #471: @80 = (@11*@74) */
  w80  = (w11*w74);
  /* #472: @79 = (@79-@80) */
  w79 -= w80;
  /* #473: @75 = (@6*@75) */
  w75  = (w6*w75);
  /* #474: @52 = (@7*@52) */
  w52  = (w7*w52);
  /* #475: @75 = (@75+@52) */
  w75 += w52;
  /* #476: @51 = (@11*@51) */
  w51  = (w11*w51);
  /* #477: @75 = (@75-@51) */
  w75 -= w51;
  /* #478: @74 = (@12*@74) */
  w74  = (w12*w74);
  /* #479: @75 = (@75-@74) */
  w75 -= w74;
  /* #480: @73 = vertcat(@53, @78, @79, @75) */
  rr=w73;
  *rr++ = w53;
  *rr++ = w78;
  *rr++ = w79;
  *rr++ = w75;
  /* #481: @53 = dot(@42, @73) */
  w53 = casadi_dot(4, w42, w73);
  /* #482: @69 = (@69/@13) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w13;
  /* #483: @36 = (@36/@13) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) /= w13;
  /* #484: @64 = (@36*@60) */
  for (i=0, rr=w64, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #485: @69 = (@69-@64) */
  for (i=0, rr=w69, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #486: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #487: @78 = dot(@69, @50) */
  w78 = casadi_dot(4, w69, w50);
  /* #488: @53 = (@53+@78) */
  w53 += w78;
  /* #489: @53 = (@53/@13) */
  w53 /= w13;
  /* #490: @78 = (@24/@13) */
  w78  = (w24/w13);
  /* #491: @79 = (@78*@60) */
  w79  = (w78*w60);
  /* #492: @53 = (@53-@79) */
  w53 -= w79;
  /* #493: @69 = (@34*@53) */
  for (i=0, rr=w69, cr=w34; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #494: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #495: @64 = dense(@57) */
  casadi_densify((&w57), casadi_s4, w64, 0);
  /* #496: @69 = (@69+@64) */
  for (i=0, rr=w69, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #497: (@29[6:10] += @69) */
  for (rr=w29+6, ss=w69; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #498: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #499: @57 = project(@26) */
  casadi_sparsify(w26, (&w57), casadi_s5, 0);
  /* #500: @53 = @61[0] */
  for (rr=(&w53), ss=(&w61)+0; ss!=(&w61)+1; ss+=1) *rr++ = *ss;
  /* #501: @53 = (-@53) */
  w53 = (- w53 );
  /* #502: @61 = dot(@57, @53) */
  w61 = casadi_dot(1, (&w57), (&w53));
  /* #503: @30 = (@26*@61) */
  for (i=0, rr=w30, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w61);
  /* #504: @2 = @30' */
  casadi_copy(w30, 3, w2);
  /* #505: @27 = mac(@2,@32,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #506: @27 = @27' */
  /* #507: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #508: @30 = @30' */
  /* #509: @2 = mac(@30,@54,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #510: @2 = @2' */
  /* #511: @27 = (@27+@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #512: @61 = dot(@26, @27) */
  w61 = casadi_dot(3, w26, w27);
  /* #513: @27 = (@26*@61) */
  for (i=0, rr=w27, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w61);
  /* #514: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #515: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #516: @48 = zeros(3x1) */
  casadi_clear(w48, 3);
  /* #517: @48 = mac(@3,@53,@48) */
  casadi_mtimes(w3, casadi_s7, (&w53), casadi_s5, w48, casadi_s6, w, 0);
  /* #518: @1 = @48' */
  casadi_copy(w48, 3, w1);
  /* #519: @30 = mac(@1,@28,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #520: @30 = @30' */
  /* #521: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #522: @48 = @48' */
  /* #523: @1 = mac(@48,@56,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w48+j, tt=w56+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #524: @1 = @1' */
  /* #525: @30 = (@30+@1) */
  for (i=0, rr=w30, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #526: @2 = mac(@55,@30,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w55+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #527: @27 = (@27+@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #528: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #529: (@29[:3] += @27) */
  for (rr=w29+0, ss=w27; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #530: {@53, @61, @57, @79, @75, @74, @51, @52, @80, @81, @82, @83, @84} = vertsplit(@29) */
  w53 = w29[0];
  w61 = w29[1];
  w57 = w29[2];
  w79 = w29[3];
  w75 = w29[4];
  w74 = w29[5];
  w51 = w29[6];
  w52 = w29[7];
  w80 = w29[8];
  w81 = w29[9];
  w82 = w29[10];
  w83 = w29[11];
  w84 = w29[12];
  /* #531: @73 = (@73/@13) */
  for (i=0, rr=w73; i<4; ++i) (*rr++) /= w13;
  /* #532: @35 = (@35/@13) */
  for (i=0, rr=w35; i<4; ++i) (*rr++) /= w13;
  /* #533: @69 = (@35*@60) */
  for (i=0, rr=w69, cr=w35; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #534: @73 = (@73-@69) */
  for (i=0, rr=w73, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #535: {@60, @85, @86, @87} = vertsplit(@73) */
  w60 = w73[0];
  w85 = w73[1];
  w86 = w73[2];
  w87 = w73[3];
  /* #536: @60 = (@60+@51) */
  w60 += w51;
  /* #537: @52 = (@52-@85) */
  w52 -= w85;
  /* #538: @80 = (@80-@86) */
  w80 -= w86;
  /* #539: @81 = (@81-@87) */
  w81 -= w87;
  /* #540: @88 = vertcat(@59, @62, @23, @58, @53, @61, @57, @79, @75, @74, @60, @52, @80, @81, @82, @83, @84) */
  rr=w88;
  *rr++ = w59;
  *rr++ = w62;
  *rr++ = w23;
  *rr++ = w58;
  *rr++ = w53;
  *rr++ = w61;
  *rr++ = w57;
  *rr++ = w79;
  *rr++ = w75;
  *rr++ = w74;
  *rr++ = w60;
  *rr++ = w52;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w84;
  /* #541: @89 = @88[:14] */
  for (rr=w89, ss=w88+0; ss!=w88+14; ss+=1) *rr++ = *ss;
  /* #542: (@63[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 34, 35, 36, 37] = @89) */
  for (cii=casadi_s8, rr=w63, ss=w89; cii!=casadi_s8+14; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #543: @89 = @88[:14] */
  for (rr=w89, ss=w88+0; ss!=w88+14; ss+=1) *rr++ = *ss;
  /* #544: (@63[0, 4, 8, 12, 16, 19, 22, 25, 28, 31, 34, 38, 42, 46] = @89) */
  for (cii=casadi_s9, rr=w63, ss=w89; cii!=casadi_s9+14; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #545: @73 = zeros(1x4) */
  casadi_clear(w73, 4);
  /* #546: @66 = 00 */
  /* #547: @69 = ones(17x1,4nz) */
  casadi_fill(w69, 4, 1.);
  /* #548: {NULL, @59, NULL, NULL, NULL, @62, NULL, NULL, NULL, NULL, NULL, @23, NULL, NULL, NULL, NULL, NULL} = vertsplit(@69) */
  w59 = w69[0];
  w62 = w69[1];
  w23 = w69[3];
  /* #549: @67 = 00 */
  /* #550: @68 = 00 */
  /* #551: @58 = vertcat(@66, @59, @67, @68) */
  rr=(&w58);
  *rr++ = w59;
  /* #552: @59 = @58' */
  casadi_copy((&w58), 1, (&w59));
  /* #553: @73 = mac(@59,@43,@73) */
  casadi_mtimes((&w59), casadi_s10, w43, casadi_s2, w73, casadi_s1, w, 0);
  /* #554: @73 = @73' */
  /* #555: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #556: @58 = @58' */
  /* #557: @69 = mac(@58,@45,@69) */
  casadi_mtimes((&w58), casadi_s10, w45, casadi_s2, w69, casadi_s1, w, 0);
  /* #558: @69 = @69' */
  /* #559: @73 = (@73+@69) */
  for (i=0, rr=w73, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #560: {@58, @59, @53, @61} = vertsplit(@73) */
  w58 = w73[0];
  w59 = w73[1];
  w53 = w73[2];
  w61 = w73[3];
  /* #561: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #562: @73 = zeros(4x1) */
  casadi_clear(w73, 4);
  /* #563: @66 = 00 */
  /* #564: @57 = (-@23) */
  w57 = (- w23 );
  /* #565: @67 = 00 */
  /* #566: @68 = 00 */
  /* #567: @79 = vertcat(@66, @57, @67, @68) */
  rr=(&w79);
  *rr++ = w57;
  /* #568: @79 = (@79/@13) */
  w79 /= w13;
  /* #569: @69 = dense(@79) */
  casadi_densify((&w79), casadi_s11, w69, 0);
  /* #570: @79 = project(@34) */
  casadi_sparsify(w34, (&w79), casadi_s11, 0);
  /* #571: @57 = @23[0] */
  for (rr=(&w57), ss=(&w23)+0; ss!=(&w23)+1; ss+=1) *rr++ = *ss;
  /* #572: @23 = dot(@79, @57) */
  w23 = casadi_dot(1, (&w79), (&w57));
  /* #573: @23 = (@23/@13) */
  w23 /= w13;
  /* #574: @64 = (@33*@23) */
  for (i=0, rr=w64, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #575: @69 = (@69-@64) */
  for (i=0, rr=w69, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #576: {@79, @75, @74, @60} = vertsplit(@69) */
  w79 = w69[0];
  w75 = w69[1];
  w74 = w69[2];
  w60 = w69[3];
  /* #577: @52 = (@6*@79) */
  w52  = (w6*w79);
  /* #578: @80 = (@7*@75) */
  w80  = (w7*w75);
  /* #579: @52 = (@52-@80) */
  w52 -= w80;
  /* #580: @80 = (@11*@74) */
  w80  = (w11*w74);
  /* #581: @52 = (@52-@80) */
  w52 -= w80;
  /* #582: @80 = (@12*@60) */
  w80  = (w12*w60);
  /* #583: @52 = (@52-@80) */
  w52 -= w80;
  /* #584: @80 = (@7*@79) */
  w80  = (w7*w79);
  /* #585: @81 = (@6*@75) */
  w81  = (w6*w75);
  /* #586: @80 = (@80+@81) */
  w80 += w81;
  /* #587: @81 = (@12*@74) */
  w81  = (w12*w74);
  /* #588: @80 = (@80+@81) */
  w80 += w81;
  /* #589: @81 = (@11*@60) */
  w81  = (w11*w60);
  /* #590: @80 = (@80-@81) */
  w80 -= w81;
  /* #591: @81 = (@11*@79) */
  w81  = (w11*w79);
  /* #592: @82 = (@12*@75) */
  w82  = (w12*w75);
  /* #593: @81 = (@81-@82) */
  w81 -= w82;
  /* #594: @82 = (@6*@74) */
  w82  = (w6*w74);
  /* #595: @81 = (@81+@82) */
  w81 += w82;
  /* #596: @82 = (@7*@60) */
  w82  = (w7*w60);
  /* #597: @81 = (@81+@82) */
  w81 += w82;
  /* #598: @79 = (@12*@79) */
  w79  = (w12*w79);
  /* #599: @75 = (@11*@75) */
  w75  = (w11*w75);
  /* #600: @79 = (@79+@75) */
  w79 += w75;
  /* #601: @74 = (@7*@74) */
  w74  = (w7*w74);
  /* #602: @79 = (@79-@74) */
  w79 -= w74;
  /* #603: @60 = (@6*@60) */
  w60  = (w6*w60);
  /* #604: @79 = (@79+@60) */
  w79 += w60;
  /* #605: @64 = vertcat(@52, @80, @81, @79) */
  rr=w64;
  *rr++ = w52;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w79;
  /* #606: @70 = (@17*@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #607: @64 = (@18*@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w18*(*cs++));
  /* #608: @70 = (@70-@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #609: @27 = @70[1:4] */
  for (rr=w27, ss=w70+1; ss!=w70+4; ss+=1) *rr++ = *ss;
  /* #610: @52 = dot(@37, @27) */
  w52 = casadi_dot(3, w37, w27);
  /* #611: @52 = (@52/@19) */
  w52 /= w19;
  /* #612: @80 = (@52/@10) */
  w80  = (w52/w10);
  /* #613: @81 = (@15*@52) */
  w81  = (w15*w52);
  /* #614: @79 = @70[0] */
  for (rr=(&w79), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  /* #615: @60 = (@22*@79) */
  w60  = (w22*w79);
  /* #616: @81 = (@81+@60) */
  w81 += w60;
  /* #617: @60 = (@71*@81) */
  w60  = (w71*w81);
  /* #618: @80 = (@80-@60) */
  w80 -= w60;
  /* #619: @80 = (@4*@80) */
  w80  = (w4*w80);
  /* #620: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #621: @30 = (2.*@27) */
  for (i=0, rr=w30, cs=w27; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #622: @1 = (@14*@30) */
  for (i=0, rr=w1, cs=w30; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #623: @60 = (@20*@52) */
  w60  = (w20*w52);
  /* #624: @74 = (@72*@79) */
  w74  = (w72*w79);
  /* #625: @60 = (@60-@74) */
  w60 -= w74;
  /* #626: @48 = (@38*@60) */
  for (i=0, rr=w48, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #627: @1 = (@1+@48) */
  for (i=0, rr=w1, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #628: @1 = (@1/@19) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w19;
  /* #629: @48 = (@39*@52) */
  for (i=0, rr=w48, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #630: @1 = (@1-@48) */
  for (i=0, rr=w1, cs=w48; i<3; ++i) (*rr++) -= (*cs++);
  /* #631: @48 = @1' */
  casadi_copy(w1, 3, w48);
  /* #632: @2 = mac(@48,@41,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w48+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #633: @2 = @2' */
  /* #634: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #635: @76 = @1' */
  casadi_copy(w1, 3, w76);
  /* #636: @48 = mac(@76,@46,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w76+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #637: @48 = @48' */
  /* #638: @2 = (@2+@48) */
  for (i=0, rr=w2, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #639: @48 = (@2/@19) */
  for (i=0, rr=w48, cr=w2; i<3; ++i) (*rr++)  = ((*cr++)/w19);
  /* #640: @76 = (@49*@52) */
  for (i=0, rr=w76, cr=w49; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #641: @48 = (@48-@76) */
  for (i=0, rr=w48, cs=w76; i<3; ++i) (*rr++) -= (*cs++);
  /* #642: @74 = dot(@38, @48) */
  w74 = casadi_dot(3, w38, w48);
  /* #643: @75 = dot(@30, @44) */
  w75 = casadi_dot(3, w30, w44);
  /* #644: @74 = (@74+@75) */
  w74 += w75;
  /* #645: @75 = (@16*@74) */
  w75  = (w16*w74);
  /* #646: @80 = (@80+@75) */
  w80 += w75;
  /* #647: @80 = (-@80) */
  w80 = (- w80 );
  /* #648: (@73[0] += @80) */
  for (rr=w73+0, ss=(&w80); rr!=w73+1; rr+=1) *rr += *ss++;
  /* #649: @80 = dot(@47, @2) */
  w80 = casadi_dot(3, w47, w2);
  /* #650: @1 = (@1/@19) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w19;
  /* #651: @2 = (@40*@52) */
  for (i=0, rr=w2, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #652: @1 = (@1-@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #653: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #654: @75 = dot(@1, @31) */
  w75 = casadi_dot(3, w1, w31);
  /* #655: @80 = (@80+@75) */
  w80 += w75;
  /* #656: @79 = (@79/@10) */
  w79 /= w10;
  /* #657: @81 = (@77*@81) */
  w81  = (w77*w81);
  /* #658: @79 = (@79-@81) */
  w79 -= w81;
  /* #659: @79 = (@4*@79) */
  w79  = (w4*w79);
  /* #660: @74 = (@9*@74) */
  w74  = (w9*w74);
  /* #661: @79 = (@79+@74) */
  w79 += w74;
  /* #662: @80 = (@80+@79) */
  w80 += w79;
  /* #663: @80 = (@80/@19) */
  w80 /= w19;
  /* #664: @52 = (@5*@52) */
  w52  = (w5*w52);
  /* #665: @80 = (@80-@52) */
  w80 -= w52;
  /* #666: @1 = (@37*@80) */
  for (i=0, rr=w1, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #667: @27 = (@0*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #668: @1 = (@1+@27) */
  for (i=0, rr=w1, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #669: @27 = (@44*@60) */
  for (i=0, rr=w27, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #670: @48 = (@14*@48) */
  for (i=0, rr=w48, cs=w48; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #671: @27 = (@27+@48) */
  for (i=0, rr=w27, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #672: @27 = (2.*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #673: @1 = (@1+@27) */
  for (i=0, rr=w1, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #674: (@73[1:4] += @1) */
  for (rr=w73+1, ss=w1; rr!=w73+4; rr+=1) *rr += *ss++;
  /* #675: @70 = (@8*@73) */
  for (i=0, rr=w70, cs=w73; i<4; ++i) (*rr++)  = (w8*(*cs++));
  /* #676: @73 = (@21*@73) */
  for (i=0, rr=w73, cs=w73; i<4; ++i) (*rr++)  = (w21*(*cs++));
  /* #677: @70 = (@70-@73) */
  for (i=0, rr=w70, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #678: {@60, @80, @52, @79} = vertsplit(@70) */
  w60 = w70[0];
  w80 = w70[1];
  w52 = w70[2];
  w79 = w70[3];
  /* #679: @74 = (@12*@79) */
  w74  = (w12*w79);
  /* #680: @81 = (@11*@52) */
  w81  = (w11*w52);
  /* #681: @74 = (@74+@81) */
  w74 += w81;
  /* #682: @81 = (@7*@80) */
  w81  = (w7*w80);
  /* #683: @74 = (@74+@81) */
  w74 += w81;
  /* #684: @81 = (@6*@60) */
  w81  = (w6*w60);
  /* #685: @74 = (@74+@81) */
  w74 += w81;
  /* #686: @81 = (@11*@79) */
  w81  = (w11*w79);
  /* #687: @75 = (@12*@52) */
  w75  = (w12*w52);
  /* #688: @81 = (@81-@75) */
  w81 -= w75;
  /* #689: @75 = (@6*@80) */
  w75  = (w6*w80);
  /* #690: @81 = (@81+@75) */
  w81 += w75;
  /* #691: @75 = (@7*@60) */
  w75  = (w7*w60);
  /* #692: @81 = (@81-@75) */
  w81 -= w75;
  /* #693: @75 = (@6*@52) */
  w75  = (w6*w52);
  /* #694: @82 = (@7*@79) */
  w82  = (w7*w79);
  /* #695: @75 = (@75-@82) */
  w75 -= w82;
  /* #696: @82 = (@12*@80) */
  w82  = (w12*w80);
  /* #697: @75 = (@75+@82) */
  w75 += w82;
  /* #698: @82 = (@11*@60) */
  w82  = (w11*w60);
  /* #699: @75 = (@75-@82) */
  w75 -= w82;
  /* #700: @79 = (@6*@79) */
  w79  = (w6*w79);
  /* #701: @52 = (@7*@52) */
  w52  = (w7*w52);
  /* #702: @79 = (@79+@52) */
  w79 += w52;
  /* #703: @80 = (@11*@80) */
  w80  = (w11*w80);
  /* #704: @79 = (@79-@80) */
  w79 -= w80;
  /* #705: @60 = (@12*@60) */
  w60  = (w12*w60);
  /* #706: @79 = (@79-@60) */
  w79 -= w60;
  /* #707: @70 = vertcat(@74, @81, @75, @79) */
  rr=w70;
  *rr++ = w74;
  *rr++ = w81;
  *rr++ = w75;
  *rr++ = w79;
  /* #708: @74 = dot(@42, @70) */
  w74 = casadi_dot(4, w42, w70);
  /* #709: @69 = (@69/@13) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w13;
  /* #710: @73 = (@36*@23) */
  for (i=0, rr=w73, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #711: @69 = (@69-@73) */
  for (i=0, rr=w69, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #712: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #713: @81 = dot(@69, @50) */
  w81 = casadi_dot(4, w69, w50);
  /* #714: @74 = (@74+@81) */
  w74 += w81;
  /* #715: @74 = (@74/@13) */
  w74 /= w13;
  /* #716: @81 = (@78*@23) */
  w81  = (w78*w23);
  /* #717: @74 = (@74-@81) */
  w74 -= w81;
  /* #718: @69 = (@34*@74) */
  for (i=0, rr=w69, cr=w34; i<4; ++i) (*rr++)  = ((*cr++)*w74);
  /* #719: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #720: @73 = dense(@57) */
  casadi_densify((&w57), casadi_s11, w73, 0);
  /* #721: @69 = (@69+@73) */
  for (i=0, rr=w69, cs=w73; i<4; ++i) (*rr++) += (*cs++);
  /* #722: (@29[6:10] += @69) */
  for (rr=w29+6, ss=w69; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #723: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #724: @57 = project(@26) */
  casadi_sparsify(w26, (&w57), casadi_s12, 0);
  /* #725: @74 = @62[0] */
  for (rr=(&w74), ss=(&w62)+0; ss!=(&w62)+1; ss+=1) *rr++ = *ss;
  /* #726: @74 = (-@74) */
  w74 = (- w74 );
  /* #727: @62 = dot(@57, @74) */
  w62 = casadi_dot(1, (&w57), (&w74));
  /* #728: @27 = (@26*@62) */
  for (i=0, rr=w27, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #729: @48 = @27' */
  casadi_copy(w27, 3, w48);
  /* #730: @1 = mac(@48,@32,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w48+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #731: @1 = @1' */
  /* #732: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #733: @27 = @27' */
  /* #734: @48 = mac(@27,@54,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #735: @48 = @48' */
  /* #736: @1 = (@1+@48) */
  for (i=0, rr=w1, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #737: @62 = dot(@26, @1) */
  w62 = casadi_dot(3, w26, w1);
  /* #738: @1 = (@26*@62) */
  for (i=0, rr=w1, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #739: @48 = zeros(3x1) */
  casadi_clear(w48, 3);
  /* #740: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #741: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #742: @2 = mac(@3,@74,@2) */
  casadi_mtimes(w3, casadi_s7, (&w74), casadi_s12, w2, casadi_s6, w, 0);
  /* #743: @30 = @2' */
  casadi_copy(w2, 3, w30);
  /* #744: @27 = mac(@30,@28,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #745: @27 = @27' */
  /* #746: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #747: @2 = @2' */
  /* #748: @30 = mac(@2,@56,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w56+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #749: @30 = @30' */
  /* #750: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #751: @48 = mac(@55,@27,@48) */
  for (i=0, rr=w48; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w55+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #752: @1 = (@1+@48) */
  for (i=0, rr=w1, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #753: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #754: (@29[:3] += @1) */
  for (rr=w29+0, ss=w1; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #755: {@74, @62, @57, @81, @75, @79, @60, @80, @52, @82, @83, @84, @87} = vertsplit(@29) */
  w74 = w29[0];
  w62 = w29[1];
  w57 = w29[2];
  w81 = w29[3];
  w75 = w29[4];
  w79 = w29[5];
  w60 = w29[6];
  w80 = w29[7];
  w52 = w29[8];
  w82 = w29[9];
  w83 = w29[10];
  w84 = w29[11];
  w87 = w29[12];
  /* #756: @70 = (@70/@13) */
  for (i=0, rr=w70; i<4; ++i) (*rr++) /= w13;
  /* #757: @69 = (@35*@23) */
  for (i=0, rr=w69, cr=w35; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #758: @70 = (@70-@69) */
  for (i=0, rr=w70, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #759: {@23, @86, @85, @51} = vertsplit(@70) */
  w23 = w70[0];
  w86 = w70[1];
  w85 = w70[2];
  w51 = w70[3];
  /* #760: @23 = (@23+@60) */
  w23 += w60;
  /* #761: @80 = (@80-@86) */
  w80 -= w86;
  /* #762: @52 = (@52-@85) */
  w52 -= w85;
  /* #763: @82 = (@82-@51) */
  w82 -= w51;
  /* #764: @88 = vertcat(@58, @59, @53, @61, @74, @62, @57, @81, @75, @79, @23, @80, @52, @82, @83, @84, @87) */
  rr=w88;
  *rr++ = w58;
  *rr++ = w59;
  *rr++ = w53;
  *rr++ = w61;
  *rr++ = w74;
  *rr++ = w62;
  *rr++ = w57;
  *rr++ = w81;
  *rr++ = w75;
  *rr++ = w79;
  *rr++ = w23;
  *rr++ = w80;
  *rr++ = w52;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w84;
  *rr++ = w87;
  /* #765: @89 = @88[:14] */
  for (rr=w89, ss=w88+0; ss!=w88+14; ss+=1) *rr++ = *ss;
  /* #766: (@63[4, 5, 6, 7, 19, 20, 21, 28, 29, 30, 38, 39, 40, 41] = @89) */
  for (cii=casadi_s13, rr=w63, ss=w89; cii!=casadi_s13+14; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #767: @89 = @88[:14] */
  for (rr=w89, ss=w88+0; ss!=w88+14; ss+=1) *rr++ = *ss;
  /* #768: (@63[1, 5, 9, 13, 17, 20, 23, 26, 29, 32, 35, 39, 43, 47] = @89) */
  for (cii=casadi_s14, rr=w63, ss=w89; cii!=casadi_s14+14; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #769: @70 = zeros(1x4) */
  casadi_clear(w70, 4);
  /* #770: @66 = 00 */
  /* #771: @67 = 00 */
  /* #772: @69 = ones(17x1,4nz) */
  casadi_fill(w69, 4, 1.);
  /* #773: {NULL, NULL, @58, NULL, NULL, NULL, @59, NULL, NULL, NULL, NULL, NULL, @53, NULL, NULL, NULL, NULL} = vertsplit(@69) */
  w58 = w69[0];
  w59 = w69[1];
  w53 = w69[3];
  /* #774: @68 = 00 */
  /* #775: @61 = vertcat(@66, @67, @58, @68) */
  rr=(&w61);
  *rr++ = w58;
  /* #776: @58 = @61' */
  casadi_copy((&w61), 1, (&w58));
  /* #777: @70 = mac(@58,@43,@70) */
  casadi_mtimes((&w58), casadi_s15, w43, casadi_s2, w70, casadi_s1, w, 0);
  /* #778: @70 = @70' */
  /* #779: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #780: @61 = @61' */
  /* #781: @69 = mac(@61,@45,@69) */
  casadi_mtimes((&w61), casadi_s15, w45, casadi_s2, w69, casadi_s1, w, 0);
  /* #782: @69 = @69' */
  /* #783: @70 = (@70+@69) */
  for (i=0, rr=w70, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #784: {@61, @58, @74, @62} = vertsplit(@70) */
  w61 = w70[0];
  w58 = w70[1];
  w74 = w70[2];
  w62 = w70[3];
  /* #785: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #786: @70 = zeros(4x1) */
  casadi_clear(w70, 4);
  /* #787: @66 = 00 */
  /* #788: @67 = 00 */
  /* #789: @57 = (-@53) */
  w57 = (- w53 );
  /* #790: @68 = 00 */
  /* #791: @81 = vertcat(@66, @67, @57, @68) */
  rr=(&w81);
  *rr++ = w57;
  /* #792: @81 = (@81/@13) */
  w81 /= w13;
  /* #793: @69 = dense(@81) */
  casadi_densify((&w81), casadi_s16, w69, 0);
  /* #794: @81 = project(@34) */
  casadi_sparsify(w34, (&w81), casadi_s16, 0);
  /* #795: @57 = @53[0] */
  for (rr=(&w57), ss=(&w53)+0; ss!=(&w53)+1; ss+=1) *rr++ = *ss;
  /* #796: @53 = dot(@81, @57) */
  w53 = casadi_dot(1, (&w81), (&w57));
  /* #797: @53 = (@53/@13) */
  w53 /= w13;
  /* #798: @73 = (@33*@53) */
  for (i=0, rr=w73, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #799: @69 = (@69-@73) */
  for (i=0, rr=w69, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #800: {@81, @75, @79, @23} = vertsplit(@69) */
  w81 = w69[0];
  w75 = w69[1];
  w79 = w69[2];
  w23 = w69[3];
  /* #801: @80 = (@6*@81) */
  w80  = (w6*w81);
  /* #802: @52 = (@7*@75) */
  w52  = (w7*w75);
  /* #803: @80 = (@80-@52) */
  w80 -= w52;
  /* #804: @52 = (@11*@79) */
  w52  = (w11*w79);
  /* #805: @80 = (@80-@52) */
  w80 -= w52;
  /* #806: @52 = (@12*@23) */
  w52  = (w12*w23);
  /* #807: @80 = (@80-@52) */
  w80 -= w52;
  /* #808: @52 = (@7*@81) */
  w52  = (w7*w81);
  /* #809: @82 = (@6*@75) */
  w82  = (w6*w75);
  /* #810: @52 = (@52+@82) */
  w52 += w82;
  /* #811: @82 = (@12*@79) */
  w82  = (w12*w79);
  /* #812: @52 = (@52+@82) */
  w52 += w82;
  /* #813: @82 = (@11*@23) */
  w82  = (w11*w23);
  /* #814: @52 = (@52-@82) */
  w52 -= w82;
  /* #815: @82 = (@11*@81) */
  w82  = (w11*w81);
  /* #816: @83 = (@12*@75) */
  w83  = (w12*w75);
  /* #817: @82 = (@82-@83) */
  w82 -= w83;
  /* #818: @83 = (@6*@79) */
  w83  = (w6*w79);
  /* #819: @82 = (@82+@83) */
  w82 += w83;
  /* #820: @83 = (@7*@23) */
  w83  = (w7*w23);
  /* #821: @82 = (@82+@83) */
  w82 += w83;
  /* #822: @81 = (@12*@81) */
  w81  = (w12*w81);
  /* #823: @75 = (@11*@75) */
  w75  = (w11*w75);
  /* #824: @81 = (@81+@75) */
  w81 += w75;
  /* #825: @79 = (@7*@79) */
  w79  = (w7*w79);
  /* #826: @81 = (@81-@79) */
  w81 -= w79;
  /* #827: @23 = (@6*@23) */
  w23  = (w6*w23);
  /* #828: @81 = (@81+@23) */
  w81 += w23;
  /* #829: @73 = vertcat(@80, @52, @82, @81) */
  rr=w73;
  *rr++ = w80;
  *rr++ = w52;
  *rr++ = w82;
  *rr++ = w81;
  /* #830: @64 = (@17*@73) */
  for (i=0, rr=w64, cs=w73; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #831: @73 = (@18*@73) */
  for (i=0, rr=w73, cs=w73; i<4; ++i) (*rr++)  = (w18*(*cs++));
  /* #832: @64 = (@64-@73) */
  for (i=0, rr=w64, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #833: @1 = @64[1:4] */
  for (rr=w1, ss=w64+1; ss!=w64+4; ss+=1) *rr++ = *ss;
  /* #834: @80 = dot(@37, @1) */
  w80 = casadi_dot(3, w37, w1);
  /* #835: @80 = (@80/@19) */
  w80 /= w19;
  /* #836: @52 = (@80/@10) */
  w52  = (w80/w10);
  /* #837: @82 = (@15*@80) */
  w82  = (w15*w80);
  /* #838: @81 = @64[0] */
  for (rr=(&w81), ss=w64+0; ss!=w64+1; ss+=1) *rr++ = *ss;
  /* #839: @23 = (@22*@81) */
  w23  = (w22*w81);
  /* #840: @82 = (@82+@23) */
  w82 += w23;
  /* #841: @23 = (@71*@82) */
  w23  = (w71*w82);
  /* #842: @52 = (@52-@23) */
  w52 -= w23;
  /* #843: @52 = (@4*@52) */
  w52  = (w4*w52);
  /* #844: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #845: @27 = (2.*@1) */
  for (i=0, rr=w27, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #846: @30 = (@14*@27) */
  for (i=0, rr=w30, cs=w27; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #847: @23 = (@20*@80) */
  w23  = (w20*w80);
  /* #848: @79 = (@72*@81) */
  w79  = (w72*w81);
  /* #849: @23 = (@23-@79) */
  w23 -= w79;
  /* #850: @2 = (@38*@23) */
  for (i=0, rr=w2, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w23);
  /* #851: @30 = (@30+@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #852: @30 = (@30/@19) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w19;
  /* #853: @2 = (@39*@80) */
  for (i=0, rr=w2, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #854: @30 = (@30-@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #855: @2 = @30' */
  casadi_copy(w30, 3, w2);
  /* #856: @48 = mac(@2,@41,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #857: @48 = @48' */
  /* #858: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #859: @76 = @30' */
  casadi_copy(w30, 3, w76);
  /* #860: @2 = mac(@76,@46,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w76+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #861: @2 = @2' */
  /* #862: @48 = (@48+@2) */
  for (i=0, rr=w48, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #863: @2 = (@48/@19) */
  for (i=0, rr=w2, cr=w48; i<3; ++i) (*rr++)  = ((*cr++)/w19);
  /* #864: @76 = (@49*@80) */
  for (i=0, rr=w76, cr=w49; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #865: @2 = (@2-@76) */
  for (i=0, rr=w2, cs=w76; i<3; ++i) (*rr++) -= (*cs++);
  /* #866: @79 = dot(@38, @2) */
  w79 = casadi_dot(3, w38, w2);
  /* #867: @75 = dot(@27, @44) */
  w75 = casadi_dot(3, w27, w44);
  /* #868: @79 = (@79+@75) */
  w79 += w75;
  /* #869: @75 = (@16*@79) */
  w75  = (w16*w79);
  /* #870: @52 = (@52+@75) */
  w52 += w75;
  /* #871: @52 = (-@52) */
  w52 = (- w52 );
  /* #872: (@70[0] += @52) */
  for (rr=w70+0, ss=(&w52); rr!=w70+1; rr+=1) *rr += *ss++;
  /* #873: @52 = dot(@47, @48) */
  w52 = casadi_dot(3, w47, w48);
  /* #874: @30 = (@30/@19) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w19;
  /* #875: @48 = (@40*@80) */
  for (i=0, rr=w48, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #876: @30 = (@30-@48) */
  for (i=0, rr=w30, cs=w48; i<3; ++i) (*rr++) -= (*cs++);
  /* #877: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #878: @75 = dot(@30, @31) */
  w75 = casadi_dot(3, w30, w31);
  /* #879: @52 = (@52+@75) */
  w52 += w75;
  /* #880: @81 = (@81/@10) */
  w81 /= w10;
  /* #881: @82 = (@77*@82) */
  w82  = (w77*w82);
  /* #882: @81 = (@81-@82) */
  w81 -= w82;
  /* #883: @81 = (@4*@81) */
  w81  = (w4*w81);
  /* #884: @79 = (@9*@79) */
  w79  = (w9*w79);
  /* #885: @81 = (@81+@79) */
  w81 += w79;
  /* #886: @52 = (@52+@81) */
  w52 += w81;
  /* #887: @52 = (@52/@19) */
  w52 /= w19;
  /* #888: @80 = (@5*@80) */
  w80  = (w5*w80);
  /* #889: @52 = (@52-@80) */
  w52 -= w80;
  /* #890: @30 = (@37*@52) */
  for (i=0, rr=w30, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #891: @1 = (@0*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #892: @30 = (@30+@1) */
  for (i=0, rr=w30, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #893: @1 = (@44*@23) */
  for (i=0, rr=w1, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w23);
  /* #894: @2 = (@14*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #895: @1 = (@1+@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #896: @1 = (2.*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #897: @30 = (@30+@1) */
  for (i=0, rr=w30, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #898: (@70[1:4] += @30) */
  for (rr=w70+1, ss=w30; rr!=w70+4; rr+=1) *rr += *ss++;
  /* #899: @64 = (@8*@70) */
  for (i=0, rr=w64, cs=w70; i<4; ++i) (*rr++)  = (w8*(*cs++));
  /* #900: @70 = (@21*@70) */
  for (i=0, rr=w70, cs=w70; i<4; ++i) (*rr++)  = (w21*(*cs++));
  /* #901: @64 = (@64-@70) */
  for (i=0, rr=w64, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #902: {@23, @52, @80, @81} = vertsplit(@64) */
  w23 = w64[0];
  w52 = w64[1];
  w80 = w64[2];
  w81 = w64[3];
  /* #903: @79 = (@12*@81) */
  w79  = (w12*w81);
  /* #904: @82 = (@11*@80) */
  w82  = (w11*w80);
  /* #905: @79 = (@79+@82) */
  w79 += w82;
  /* #906: @82 = (@7*@52) */
  w82  = (w7*w52);
  /* #907: @79 = (@79+@82) */
  w79 += w82;
  /* #908: @82 = (@6*@23) */
  w82  = (w6*w23);
  /* #909: @79 = (@79+@82) */
  w79 += w82;
  /* #910: @82 = (@11*@81) */
  w82  = (w11*w81);
  /* #911: @75 = (@12*@80) */
  w75  = (w12*w80);
  /* #912: @82 = (@82-@75) */
  w82 -= w75;
  /* #913: @75 = (@6*@52) */
  w75  = (w6*w52);
  /* #914: @82 = (@82+@75) */
  w82 += w75;
  /* #915: @75 = (@7*@23) */
  w75  = (w7*w23);
  /* #916: @82 = (@82-@75) */
  w82 -= w75;
  /* #917: @75 = (@6*@80) */
  w75  = (w6*w80);
  /* #918: @83 = (@7*@81) */
  w83  = (w7*w81);
  /* #919: @75 = (@75-@83) */
  w75 -= w83;
  /* #920: @83 = (@12*@52) */
  w83  = (w12*w52);
  /* #921: @75 = (@75+@83) */
  w75 += w83;
  /* #922: @83 = (@11*@23) */
  w83  = (w11*w23);
  /* #923: @75 = (@75-@83) */
  w75 -= w83;
  /* #924: @81 = (@6*@81) */
  w81  = (w6*w81);
  /* #925: @80 = (@7*@80) */
  w80  = (w7*w80);
  /* #926: @81 = (@81+@80) */
  w81 += w80;
  /* #927: @52 = (@11*@52) */
  w52  = (w11*w52);
  /* #928: @81 = (@81-@52) */
  w81 -= w52;
  /* #929: @23 = (@12*@23) */
  w23  = (w12*w23);
  /* #930: @81 = (@81-@23) */
  w81 -= w23;
  /* #931: @64 = vertcat(@79, @82, @75, @81) */
  rr=w64;
  *rr++ = w79;
  *rr++ = w82;
  *rr++ = w75;
  *rr++ = w81;
  /* #932: @79 = dot(@42, @64) */
  w79 = casadi_dot(4, w42, w64);
  /* #933: @69 = (@69/@13) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w13;
  /* #934: @70 = (@36*@53) */
  for (i=0, rr=w70, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #935: @69 = (@69-@70) */
  for (i=0, rr=w69, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #936: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #937: @82 = dot(@69, @50) */
  w82 = casadi_dot(4, w69, w50);
  /* #938: @79 = (@79+@82) */
  w79 += w82;
  /* #939: @79 = (@79/@13) */
  w79 /= w13;
  /* #940: @82 = (@78*@53) */
  w82  = (w78*w53);
  /* #941: @79 = (@79-@82) */
  w79 -= w82;
  /* #942: @69 = (@34*@79) */
  for (i=0, rr=w69, cr=w34; i<4; ++i) (*rr++)  = ((*cr++)*w79);
  /* #943: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #944: @70 = dense(@57) */
  casadi_densify((&w57), casadi_s16, w70, 0);
  /* #945: @69 = (@69+@70) */
  for (i=0, rr=w69, cs=w70; i<4; ++i) (*rr++) += (*cs++);
  /* #946: (@29[6:10] += @69) */
  for (rr=w29+6, ss=w69; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #947: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #948: @57 = project(@26) */
  casadi_sparsify(w26, (&w57), casadi_s17, 0);
  /* #949: @79 = @59[0] */
  for (rr=(&w79), ss=(&w59)+0; ss!=(&w59)+1; ss+=1) *rr++ = *ss;
  /* #950: @79 = (-@79) */
  w79 = (- w79 );
  /* #951: @59 = dot(@57, @79) */
  w59 = casadi_dot(1, (&w57), (&w79));
  /* #952: @1 = (@26*@59) */
  for (i=0, rr=w1, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w59);
  /* #953: @2 = @1' */
  casadi_copy(w1, 3, w2);
  /* #954: @30 = mac(@2,@32,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #955: @30 = @30' */
  /* #956: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #957: @1 = @1' */
  /* #958: @2 = mac(@1,@54,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #959: @2 = @2' */
  /* #960: @30 = (@30+@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #961: @59 = dot(@26, @30) */
  w59 = casadi_dot(3, w26, w30);
  /* #962: @26 = (@26*@59) */
  for (i=0, rr=w26; i<3; ++i) (*rr++) *= w59;
  /* #963: @30 = zeros(3x1) */
  casadi_clear(w30, 3);
  /* #964: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #965: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #966: @1 = mac(@3,@79,@1) */
  casadi_mtimes(w3, casadi_s7, (&w79), casadi_s17, w1, casadi_s6, w, 0);
  /* #967: @48 = @1' */
  casadi_copy(w1, 3, w48);
  /* #968: @2 = mac(@48,@28,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w48+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #969: @2 = @2' */
  /* #970: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #971: @1 = @1' */
  /* #972: @48 = mac(@1,@56,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w56+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #973: @48 = @48' */
  /* #974: @2 = (@2+@48) */
  for (i=0, rr=w2, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #975: @30 = mac(@55,@2,@30) */
  for (i=0, rr=w30; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w55+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #976: @26 = (@26+@30) */
  for (i=0, rr=w26, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #977: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) *rr++ = (- *cs++ );
  /* #978: (@29[:3] += @26) */
  for (rr=w29+0, ss=w26; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #979: {@79, @59, @57, @82, @75, @81, @23, @52, @80, @83, @84, @87, @51} = vertsplit(@29) */
  w79 = w29[0];
  w59 = w29[1];
  w57 = w29[2];
  w82 = w29[3];
  w75 = w29[4];
  w81 = w29[5];
  w23 = w29[6];
  w52 = w29[7];
  w80 = w29[8];
  w83 = w29[9];
  w84 = w29[10];
  w87 = w29[11];
  w51 = w29[12];
  /* #980: @64 = (@64/@13) */
  for (i=0, rr=w64; i<4; ++i) (*rr++) /= w13;
  /* #981: @69 = (@35*@53) */
  for (i=0, rr=w69, cr=w35; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #982: @64 = (@64-@69) */
  for (i=0, rr=w64, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #983: {@53, @85, @86, @60} = vertsplit(@64) */
  w53 = w64[0];
  w85 = w64[1];
  w86 = w64[2];
  w60 = w64[3];
  /* #984: @53 = (@53+@23) */
  w53 += w23;
  /* #985: @52 = (@52-@85) */
  w52 -= w85;
  /* #986: @80 = (@80-@86) */
  w80 -= w86;
  /* #987: @83 = (@83-@60) */
  w83 -= w60;
  /* #988: @88 = vertcat(@61, @58, @74, @62, @79, @59, @57, @82, @75, @81, @53, @52, @80, @83, @84, @87, @51) */
  rr=w88;
  *rr++ = w61;
  *rr++ = w58;
  *rr++ = w74;
  *rr++ = w62;
  *rr++ = w79;
  *rr++ = w59;
  *rr++ = w57;
  *rr++ = w82;
  *rr++ = w75;
  *rr++ = w81;
  *rr++ = w53;
  *rr++ = w52;
  *rr++ = w80;
  *rr++ = w83;
  *rr++ = w84;
  *rr++ = w87;
  *rr++ = w51;
  /* #989: @89 = @88[:14] */
  for (rr=w89, ss=w88+0; ss!=w88+14; ss+=1) *rr++ = *ss;
  /* #990: (@63[8, 9, 10, 11, 22, 23, 24, 31, 32, 33, 42, 43, 44, 45] = @89) */
  for (cii=casadi_s18, rr=w63, ss=w89; cii!=casadi_s18+14; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #991: @89 = @88[:14] */
  for (rr=w89, ss=w88+0; ss!=w88+14; ss+=1) *rr++ = *ss;
  /* #992: (@63[2, 6, 10, 14, 18, 21, 24, 27, 30, 33, 36, 40, 44, 48] = @89) */
  for (cii=casadi_s19, rr=w63, ss=w89; cii!=casadi_s19+14; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #993: @64 = zeros(1x4) */
  casadi_clear(w64, 4);
  /* #994: @66 = 00 */
  /* #995: @67 = 00 */
  /* #996: @68 = 00 */
  /* #997: @90 = ones(17x1,2nz) */
  casadi_fill(w90, 2, 1.);
  /* #998: {NULL, NULL, NULL, @61, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @58, NULL, NULL, NULL} = vertsplit(@90) */
  w61 = w90[0];
  w58 = w90[1];
  /* #999: @74 = vertcat(@66, @67, @68, @61) */
  rr=(&w74);
  *rr++ = w61;
  /* #1000: @61 = @74' */
  casadi_copy((&w74), 1, (&w61));
  /* #1001: @64 = mac(@61,@43,@64) */
  casadi_mtimes((&w61), casadi_s20, w43, casadi_s2, w64, casadi_s1, w, 0);
  /* #1002: @64 = @64' */
  /* #1003: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #1004: @74 = @74' */
  /* #1005: @69 = mac(@74,@45,@69) */
  casadi_mtimes((&w74), casadi_s20, w45, casadi_s2, w69, casadi_s1, w, 0);
  /* #1006: @69 = @69' */
  /* #1007: @64 = (@64+@69) */
  for (i=0, rr=w64, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #1008: {@74, @61, @62, @79} = vertsplit(@64) */
  w74 = w64[0];
  w61 = w64[1];
  w62 = w64[2];
  w79 = w64[3];
  /* #1009: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #1010: @64 = zeros(4x1) */
  casadi_clear(w64, 4);
  /* #1011: @66 = 00 */
  /* #1012: @67 = 00 */
  /* #1013: @68 = 00 */
  /* #1014: @59 = (-@58) */
  w59 = (- w58 );
  /* #1015: @57 = vertcat(@66, @67, @68, @59) */
  rr=(&w57);
  *rr++ = w59;
  /* #1016: @57 = (@57/@13) */
  w57 /= w13;
  /* #1017: @69 = dense(@57) */
  casadi_densify((&w57), casadi_s21, w69, 0);
  /* #1018: @57 = project(@34) */
  casadi_sparsify(w34, (&w57), casadi_s21, 0);
  /* #1019: @59 = @58[0] */
  for (rr=(&w59), ss=(&w58)+0; ss!=(&w58)+1; ss+=1) *rr++ = *ss;
  /* #1020: @58 = dot(@57, @59) */
  w58 = casadi_dot(1, (&w57), (&w59));
  /* #1021: @58 = (@58/@13) */
  w58 /= w13;
  /* #1022: @33 = (@33*@58) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) *= w58;
  /* #1023: @69 = (@69-@33) */
  for (i=0, rr=w69, cs=w33; i<4; ++i) (*rr++) -= (*cs++);
  /* #1024: {@57, @82, @75, @81} = vertsplit(@69) */
  w57 = w69[0];
  w82 = w69[1];
  w75 = w69[2];
  w81 = w69[3];
  /* #1025: @53 = (@6*@57) */
  w53  = (w6*w57);
  /* #1026: @52 = (@7*@82) */
  w52  = (w7*w82);
  /* #1027: @53 = (@53-@52) */
  w53 -= w52;
  /* #1028: @52 = (@11*@75) */
  w52  = (w11*w75);
  /* #1029: @53 = (@53-@52) */
  w53 -= w52;
  /* #1030: @52 = (@12*@81) */
  w52  = (w12*w81);
  /* #1031: @53 = (@53-@52) */
  w53 -= w52;
  /* #1032: @52 = (@7*@57) */
  w52  = (w7*w57);
  /* #1033: @80 = (@6*@82) */
  w80  = (w6*w82);
  /* #1034: @52 = (@52+@80) */
  w52 += w80;
  /* #1035: @80 = (@12*@75) */
  w80  = (w12*w75);
  /* #1036: @52 = (@52+@80) */
  w52 += w80;
  /* #1037: @80 = (@11*@81) */
  w80  = (w11*w81);
  /* #1038: @52 = (@52-@80) */
  w52 -= w80;
  /* #1039: @80 = (@11*@57) */
  w80  = (w11*w57);
  /* #1040: @83 = (@12*@82) */
  w83  = (w12*w82);
  /* #1041: @80 = (@80-@83) */
  w80 -= w83;
  /* #1042: @83 = (@6*@75) */
  w83  = (w6*w75);
  /* #1043: @80 = (@80+@83) */
  w80 += w83;
  /* #1044: @83 = (@7*@81) */
  w83  = (w7*w81);
  /* #1045: @80 = (@80+@83) */
  w80 += w83;
  /* #1046: @57 = (@12*@57) */
  w57  = (w12*w57);
  /* #1047: @82 = (@11*@82) */
  w82  = (w11*w82);
  /* #1048: @57 = (@57+@82) */
  w57 += w82;
  /* #1049: @75 = (@7*@75) */
  w75  = (w7*w75);
  /* #1050: @57 = (@57-@75) */
  w57 -= w75;
  /* #1051: @81 = (@6*@81) */
  w81  = (w6*w81);
  /* #1052: @57 = (@57+@81) */
  w57 += w81;
  /* #1053: @33 = vertcat(@53, @52, @80, @57) */
  rr=w33;
  *rr++ = w53;
  *rr++ = w52;
  *rr++ = w80;
  *rr++ = w57;
  /* #1054: @70 = (@17*@33) */
  for (i=0, rr=w70, cs=w33; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #1055: @33 = (@18*@33) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w18*(*cs++));
  /* #1056: @70 = (@70-@33) */
  for (i=0, rr=w70, cs=w33; i<4; ++i) (*rr++) -= (*cs++);
  /* #1057: @26 = @70[1:4] */
  for (rr=w26, ss=w70+1; ss!=w70+4; ss+=1) *rr++ = *ss;
  /* #1058: @18 = dot(@37, @26) */
  w18 = casadi_dot(3, w37, w26);
  /* #1059: @18 = (@18/@19) */
  w18 /= w19;
  /* #1060: @17 = (@18/@10) */
  w17  = (w18/w10);
  /* #1061: @15 = (@15*@18) */
  w15 *= w18;
  /* #1062: @53 = @70[0] */
  for (rr=(&w53), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  /* #1063: @22 = (@22*@53) */
  w22 *= w53;
  /* #1064: @15 = (@15+@22) */
  w15 += w22;
  /* #1065: @71 = (@71*@15) */
  w71 *= w15;
  /* #1066: @17 = (@17-@71) */
  w17 -= w71;
  /* #1067: @17 = (@4*@17) */
  w17  = (w4*w17);
  /* #1068: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #1069: @2 = (2.*@26) */
  for (i=0, rr=w2, cs=w26; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1070: @48 = (@14*@2) */
  for (i=0, rr=w48, cs=w2; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #1071: @20 = (@20*@18) */
  w20 *= w18;
  /* #1072: @72 = (@72*@53) */
  w72 *= w53;
  /* #1073: @20 = (@20-@72) */
  w20 -= w72;
  /* #1074: @1 = (@38*@20) */
  for (i=0, rr=w1, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w20);
  /* #1075: @48 = (@48+@1) */
  for (i=0, rr=w48, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #1076: @48 = (@48/@19) */
  for (i=0, rr=w48; i<3; ++i) (*rr++) /= w19;
  /* #1077: @39 = (@39*@18) */
  for (i=0, rr=w39; i<3; ++i) (*rr++) *= w18;
  /* #1078: @48 = (@48-@39) */
  for (i=0, rr=w48, cs=w39; i<3; ++i) (*rr++) -= (*cs++);
  /* #1079: @39 = @48' */
  casadi_copy(w48, 3, w39);
  /* #1080: @30 = mac(@39,@41,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w39+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1081: @30 = @30' */
  /* #1082: @39 = zeros(1x3) */
  casadi_clear(w39, 3);
  /* #1083: @1 = @48' */
  casadi_copy(w48, 3, w1);
  /* #1084: @39 = mac(@1,@46,@39) */
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1085: @39 = @39' */
  /* #1086: @30 = (@30+@39) */
  for (i=0, rr=w30, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #1087: @39 = (@30/@19) */
  for (i=0, rr=w39, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)/w19);
  /* #1088: @49 = (@49*@18) */
  for (i=0, rr=w49; i<3; ++i) (*rr++) *= w18;
  /* #1089: @39 = (@39-@49) */
  for (i=0, rr=w39, cs=w49; i<3; ++i) (*rr++) -= (*cs++);
  /* #1090: @72 = dot(@38, @39) */
  w72 = casadi_dot(3, w38, w39);
  /* #1091: @71 = dot(@2, @44) */
  w71 = casadi_dot(3, w2, w44);
  /* #1092: @72 = (@72+@71) */
  w72 += w71;
  /* #1093: @16 = (@16*@72) */
  w16 *= w72;
  /* #1094: @17 = (@17+@16) */
  w17 += w16;
  /* #1095: @17 = (-@17) */
  w17 = (- w17 );
  /* #1096: (@64[0] += @17) */
  for (rr=w64+0, ss=(&w17); rr!=w64+1; rr+=1) *rr += *ss++;
  /* #1097: @17 = dot(@47, @30) */
  w17 = casadi_dot(3, w47, w30);
  /* #1098: @48 = (@48/@19) */
  for (i=0, rr=w48; i<3; ++i) (*rr++) /= w19;
  /* #1099: @40 = (@40*@18) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) *= w18;
  /* #1100: @48 = (@48-@40) */
  for (i=0, rr=w48, cs=w40; i<3; ++i) (*rr++) -= (*cs++);
  /* #1101: @48 = (-@48) */
  for (i=0, rr=w48, cs=w48; i<3; ++i) *rr++ = (- *cs++ );
  /* #1102: @16 = dot(@48, @31) */
  w16 = casadi_dot(3, w48, w31);
  /* #1103: @17 = (@17+@16) */
  w17 += w16;
  /* #1104: @53 = (@53/@10) */
  w53 /= w10;
  /* #1105: @77 = (@77*@15) */
  w77 *= w15;
  /* #1106: @53 = (@53-@77) */
  w53 -= w77;
  /* #1107: @4 = (@4*@53) */
  w4 *= w53;
  /* #1108: @9 = (@9*@72) */
  w9 *= w72;
  /* #1109: @4 = (@4+@9) */
  w4 += w9;
  /* #1110: @17 = (@17+@4) */
  w17 += w4;
  /* #1111: @17 = (@17/@19) */
  w17 /= w19;
  /* #1112: @5 = (@5*@18) */
  w5 *= w18;
  /* #1113: @17 = (@17-@5) */
  w17 -= w5;
  /* #1114: @37 = (@37*@17) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) *= w17;
  /* #1115: @26 = (@0*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #1116: @37 = (@37+@26) */
  for (i=0, rr=w37, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #1117: @44 = (@44*@20) */
  for (i=0, rr=w44; i<3; ++i) (*rr++) *= w20;
  /* #1118: @39 = (@14*@39) */
  for (i=0, rr=w39, cs=w39; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #1119: @44 = (@44+@39) */
  for (i=0, rr=w44, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #1120: @44 = (2.*@44) */
  for (i=0, rr=w44, cs=w44; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1121: @37 = (@37+@44) */
  for (i=0, rr=w37, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #1122: (@64[1:4] += @37) */
  for (rr=w64+1, ss=w37; rr!=w64+4; rr+=1) *rr += *ss++;
  /* #1123: @70 = (@8*@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++)  = (w8*(*cs++));
  /* #1124: @64 = (@21*@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w21*(*cs++));
  /* #1125: @70 = (@70-@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #1126: {@21, @8, @14, @20} = vertsplit(@70) */
  w21 = w70[0];
  w8 = w70[1];
  w14 = w70[2];
  w20 = w70[3];
  /* #1127: @0 = (@12*@20) */
  w0  = (w12*w20);
  /* #1128: @17 = (@11*@14) */
  w17  = (w11*w14);
  /* #1129: @0 = (@0+@17) */
  w0 += w17;
  /* #1130: @17 = (@7*@8) */
  w17  = (w7*w8);
  /* #1131: @0 = (@0+@17) */
  w0 += w17;
  /* #1132: @17 = (@6*@21) */
  w17  = (w6*w21);
  /* #1133: @0 = (@0+@17) */
  w0 += w17;
  /* #1134: @17 = (@11*@20) */
  w17  = (w11*w20);
  /* #1135: @5 = (@12*@14) */
  w5  = (w12*w14);
  /* #1136: @17 = (@17-@5) */
  w17 -= w5;
  /* #1137: @5 = (@6*@8) */
  w5  = (w6*w8);
  /* #1138: @17 = (@17+@5) */
  w17 += w5;
  /* #1139: @5 = (@7*@21) */
  w5  = (w7*w21);
  /* #1140: @17 = (@17-@5) */
  w17 -= w5;
  /* #1141: @5 = (@6*@14) */
  w5  = (w6*w14);
  /* #1142: @18 = (@7*@20) */
  w18  = (w7*w20);
  /* #1143: @5 = (@5-@18) */
  w5 -= w18;
  /* #1144: @18 = (@12*@8) */
  w18  = (w12*w8);
  /* #1145: @5 = (@5+@18) */
  w5 += w18;
  /* #1146: @18 = (@11*@21) */
  w18  = (w11*w21);
  /* #1147: @5 = (@5-@18) */
  w5 -= w18;
  /* #1148: @6 = (@6*@20) */
  w6 *= w20;
  /* #1149: @7 = (@7*@14) */
  w7 *= w14;
  /* #1150: @6 = (@6+@7) */
  w6 += w7;
  /* #1151: @11 = (@11*@8) */
  w11 *= w8;
  /* #1152: @6 = (@6-@11) */
  w6 -= w11;
  /* #1153: @12 = (@12*@21) */
  w12 *= w21;
  /* #1154: @6 = (@6-@12) */
  w6 -= w12;
  /* #1155: @70 = vertcat(@0, @17, @5, @6) */
  rr=w70;
  *rr++ = w0;
  *rr++ = w17;
  *rr++ = w5;
  *rr++ = w6;
  /* #1156: @0 = dot(@42, @70) */
  w0 = casadi_dot(4, w42, w70);
  /* #1157: @69 = (@69/@13) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w13;
  /* #1158: @36 = (@36*@58) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) *= w58;
  /* #1159: @69 = (@69-@36) */
  for (i=0, rr=w69, cs=w36; i<4; ++i) (*rr++) -= (*cs++);
  /* #1160: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #1161: @17 = dot(@69, @50) */
  w17 = casadi_dot(4, w69, w50);
  /* #1162: @0 = (@0+@17) */
  w0 += w17;
  /* #1163: @0 = (@0/@13) */
  w0 /= w13;
  /* #1164: @78 = (@78*@58) */
  w78 *= w58;
  /* #1165: @0 = (@0-@78) */
  w0 -= w78;
  /* #1166: @34 = (@34*@0) */
  for (i=0, rr=w34; i<4; ++i) (*rr++) *= w0;
  /* #1167: @24 = (@24*@59) */
  w24 *= w59;
  /* #1168: @69 = dense(@24) */
  casadi_densify((&w24), casadi_s21, w69, 0);
  /* #1169: @34 = (@34+@69) */
  for (i=0, rr=w34, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #1170: (@29[6:10] += @34) */
  for (rr=w29+6, ss=w34; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #1171: {@24, @59, @0, @78, @17, @5, @6, @12, @21, @11, @8, @7, @14} = vertsplit(@29) */
  w24 = w29[0];
  w59 = w29[1];
  w0 = w29[2];
  w78 = w29[3];
  w17 = w29[4];
  w5 = w29[5];
  w6 = w29[6];
  w12 = w29[7];
  w21 = w29[8];
  w11 = w29[9];
  w8 = w29[10];
  w7 = w29[11];
  w14 = w29[12];
  /* #1172: @70 = (@70/@13) */
  for (i=0, rr=w70; i<4; ++i) (*rr++) /= w13;
  /* #1173: @35 = (@35*@58) */
  for (i=0, rr=w35; i<4; ++i) (*rr++) *= w58;
  /* #1174: @70 = (@70-@35) */
  for (i=0, rr=w70, cs=w35; i<4; ++i) (*rr++) -= (*cs++);
  /* #1175: {@58, @13, @20, @18} = vertsplit(@70) */
  w58 = w70[0];
  w13 = w70[1];
  w20 = w70[2];
  w18 = w70[3];
  /* #1176: @58 = (@58+@6) */
  w58 += w6;
  /* #1177: @12 = (@12-@13) */
  w12 -= w13;
  /* #1178: @21 = (@21-@20) */
  w21 -= w20;
  /* #1179: @11 = (@11-@18) */
  w11 -= w18;
  /* #1180: @88 = vertcat(@74, @61, @62, @79, @24, @59, @0, @78, @17, @5, @58, @12, @21, @11, @8, @7, @14) */
  rr=w88;
  *rr++ = w74;
  *rr++ = w61;
  *rr++ = w62;
  *rr++ = w79;
  *rr++ = w24;
  *rr++ = w59;
  *rr++ = w0;
  *rr++ = w78;
  *rr++ = w17;
  *rr++ = w5;
  *rr++ = w58;
  *rr++ = w12;
  *rr++ = w21;
  *rr++ = w11;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w14;
  /* #1181: @91 = @88[:20:10;:4] */
  for (rr=w91, ss=w88+0; ss!=w88+20; ss+=10) for (tt=ss+0; tt!=ss+4; tt+=1) *rr++ = *tt;
  /* #1182: (@63[:68:34;12:16] = @91) */
  for (rr=w63+0, ss=w91; rr!=w63+68; rr+=34) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *ss++;
  /* #1183: @91 = @88[:20:10;:4] */
  for (rr=w91, ss=w88+0; ss!=w88+20; ss+=10) for (tt=ss+0; tt!=ss+4; tt+=1) *rr++ = *tt;
  /* #1184: (@63[:68:34;3:19:4] = @91) */
  for (rr=w63+0, ss=w91; rr!=w63+68; rr+=34) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *ss++;
  /* #1185: @92 = @63' */
  casadi_trans(w63,casadi_s22, w92, casadi_s22, iw);
  /* #1186: output[2][0] = @92 */
  casadi_copy(w92, 50, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s23;
    case 1: return casadi_s24;
    case 2: return casadi_s25;
    case 3: return casadi_s26;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s27;
    case 1: return casadi_s28;
    case 2: return casadi_s22;
    case 3: return casadi_s25;
    case 4: return casadi_s29;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_1_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 419;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
